### ISSUE TITLE
p-table: Unable to reorder to the last element in the table after a scroll occurs

### ISSUE THREAD

**Issue by casetolleson** [primefaces/primeng#10003]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/primeng-tablereorder-demo-akydrg

**Current behavior**
After scrolling the page you are no longer able to reorder a row into the last row of the table.

**Expected behavior**
You should be able to reorder a row into the last element of the table at all times.

**Minimal reproduction of the problem with instructions**
1. https://stackblitz.com/edit/primeng-tablereorder-demo-akydrg
2. Ensure the screen is large enough to to display the entire table, but small enough to be able to scroll.  There is a 200px filler div at the end of the table.
3. Without scrolling attempt to reorder a row to the last element. (it works)
4. Scroll the page down and attempt to reorder a row to the last element.

**What is the motivation / use case for changing the behavior?**
To allow users to move a row into the last position.

**Please tell us about your environment:**
Windows

* **Angular version:** 5.X
~11.0.0

* **PrimeNG version:** 5.X
"^11.3.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
- Chrome 89.0.4389.82
- Firefox 86.0.1
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
- Typescript ~4.0.2

* **Node (for AoT issues):** `node --version` =

**Comment by JanneckLange** [comment]
Same Problem, when the table is in a p-dialog component and the parent site is scrolled.

Angular version: 5.X
~13.1.1

PrimeNG version: 5.X
^13.0.4

**Comment by syafiqit** [comment]
Also having the same problem, can't reorder any element to the last element of the table after scrolling the page. Is it already fixed?

**Comment by cetincakiroglu** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,

**Comment by smadbe** [comment]
The bug is still present on the [official PrimeNg showcase](https://www.primefaces.org/primeng/table/reorder), so I suppose the problem is not fixed in your latest version.

To reproduce it:
- go the [official PrimeNg showcase for table reordering](https://www.primefaces.org/primeng/table/reorder)
- resize your browser so that the height is lower than the list height
- scroll down to see the bottom of the table
- try to drag an element at the last position -> still not possible

(@cetincakiroglu how do I reopen the issue?)

**Comment by talitagoulart** [comment]
This is still a problem. I guess only the owner can reopen the issue. Should a new one be created?

**Comment by talitagoulart** [comment]
I recorded a video to demonstrate the issue in the official doc page:
https://user-images.githubusercontent.com/3587657/222754594-3cb1ab32-d653-4114-aec3-bf0f2e8966e0.mov

First I drag and drop a row to the last position. Since the table is completely in the visible area, it works.
Then I zoom in so the end of the table is outside the visible area. I scroll down to see the end of the table and try to move a row to the last position. The drop marker doesn't show so I can't drop the row in the last position.

**Comment by neverlose-lv** [comment]
Same problem here!

**Comment by AravindThinkpalm** [comment]
same problem here while row reordering scrollbar is not scrolling while dragging .
