### ISSUE TITLE
Error in captcha component when language parameter is passed

### ISSUE THREAD

**Issue by jsanz1209** [primefaces/primeng#10112]
As a result of this fix  #9985 , I now get the following error when I passed the language property to captcha:

ERROR Error: reCAPTCHA has already been rendered in this element
at recaptcha__es.js:55
at Captcha.init (primeng-captcha.js:46)
at Captcha.ngAfterViewInit (primeng-captcha.js:36)

The captcha is working on, but it breaks javascript code.

Regards.

**Comment by mcrtricolor** [comment]
I'm having the same issue but worse. When i set a language i can't even see the captcha nor render the page.

**Comment by brazso** [comment]
Inserting the following line to PrimeNG (v14.1.2) _Captcha_ component (captcha.ts)'s _init_ function, the issue is solved in my case.
`this.el.nativeElement.innerHTML = "<div></div>";`
It drops the placeholder _div_ element and creates a new one just before the render is invoked. After this modification, I have not experienced the mentioned rendering error more. I can select the active language in my form and the labels inside the captcha are altered to that language automatically.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
