### ISSUE TITLE
Restore Column Widths of Dynamically created table

### ISSUE THREAD

**Issue by aikene** [primefaces/primeng#10317]
[ ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ x ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35

**Expected behavior**

```this.dataTable.reset();```
would automatically resize the column

OR

Saving the column state before manually resizing the column 
```(via Save State Button: this.dataTable.saveState();)```
then manually changing the column width then resetting the table
```(via Reset Button: this.dataTable.restoreState();)```
would restore the column widths to their original values

Inspecting the underlying HTML, you can see this widths value is being changed every time a column is manually created here, but I have been unable to clear this value: 
```body > app-root > div:nth-child(1) > p-table > div > div.p-datatable-wrapper > table```

Question:
How to I reset the column widths in this example without fully reloading the table via a button? 

**Stack Blitz Link**
https://stackblitz.com/edit/primeng-tablecolresize-demo-9xdlh3?file=src%2Fapp%2Fapp.component.ts

**Comment by easyping** [comment]
Since saveState is always called whenever the table design is changed, restoreState cannot load any other setting.
I have solved the problem as follows:
- When clicking on the "SAVE STATE" button, after calling saveState save away the settings from the corresponding storage.
- When clicking on the "RESET" button, first put the temporarily saved setting back into the storage and only then call restoreState.
Then also call the restoreColumnWidths function and possibly restoreColumnOrder if a sort order was also saved.

**Comment by yigitfindikli** [comment]
Please use the forum or discord channel for questions and help requests.
