### ISSUE TITLE
ExpressionChangedAfterItHasBeenCheckedError in table virtual scrolling after upgrading to 12.1.1

### ISSUE THREAD

**Issue by john8329** [primefaces/primeng#10659]
**I'm submitting a ...** 
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/github-w67ny3?file=src/app/app.component.html

**Current behavior**
I'm trying to follow the provided example for a virtual scroller with lazy loading, but it throws the `ExpressionChangedAfterItHasBeenCheckedError` error. This is happening everywhere in my app where it was working fine with 12.0.0. Seems to have to do something with the CDK.

Apparently the migration guide doesn't mention anything about this.

**Expected behavior**
It shouldn't throw this error, it might create unpredictable situations in production.

* **Angular version:** 12.2.7

* **PrimeNG version:** 12.1.1

**Comment by EzaBlade** [comment]
I have exactly the same issue

![VirtualScrollError](https://user-images.githubusercontent.com/1561611/140905058-3f9ccccf-6329-42f3-8e6f-c50f5a29d55a.PNG)

**Comment by giesmininkas** [comment]
Same here
![image](https://user-images.githubusercontent.com/11162236/142917134-3580f6c8-8ed4-434a-8960-cf544d748bf5.png)

**Angular version**: 12.2.13
**PrimeNG version**: 12.2.2

**Comment by Epameinondas-Theodoropoulos** [comment]
Any solution for that ? I still have the same problem. I have a service that should call to fill the empty array that I have in [value]. But the same problem appears whatever I tried.

`<p-table #reviewsTable
  [value]="reviews"
  [scrollable]="true"
  [rows]="5"
  scrollHeight="250px"
  [virtualScroll]="true"
  [virtualRowHeight]="34"
  [lazy]="true"
  (onLazyLoad)="loadReviewsLazy($event)"
  [columns]="reviewsColumns"
>`


`reviews: any[] = [];


  loadReviewsLazy(event: LazyLoadEvent): void {
    this.loading = true;
    this.myStoreReservationsService.fetchStoreReviews(this.storeId, event.first, event.rows, event.sortField, event.sortOrder).subscribe(reviews => {
      this.reviews = this.reviews.concat(reviews);
    });
  }

`

The reviews filled with data after the call but after that I have the problem

Expected behavior
It shouldn't throw this error, it might create unpredictable situations in production.

Angular version: 12.2.7

PrimeNG version: 12.2.2

**Comment by Epameinondas-Theodoropoulos** [comment]
![image](https://user-images.githubusercontent.com/49025564/181915855-d491af01-514f-4c78-bbf9-ca05480b2208.png)
