### ISSUE TITLE
MultiSelect | Indeterminate State for SelectAllCheckbox

### ISSUE THREAD

**Issue by OldBuddy** [primefaces/primeng#10926]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => Search github for a similar issue or PR before submitting
[x ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
**Current behavior**
'Select All' checkbox doesn't have indeterminate state.

**Expected behavior**
'Select All' checkbox should have indeterminate state (to show something is selected).

**Comment by yigitfindikli** [comment]
Hi @OldBuddy,

This is not a bug. This is a feature request so I'm gonna edit your report.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,

**Comment by OldBuddy** [comment]
hi @mertsincan, I checked latest [demo ](https://primefaces.org/primeng/multiselect)for version 14.2.0 and it's still not there. Should I reopen it?

**Comment by xanderflood** [comment]
I'd like to suggest a change to this ticket. If this is going to be implemented at all, presumably it should be implemented as part of the `p-checkbox` component itself. The indeterminate state is part of the W3C spec for a standard checkbox, and currently it appears that the Tree and TreeSelect components support this by essentially re-implementing the `p-checkbox` instead of using it directly.

If the indeterminate state were simply part of the `p-checkbox` component, the functionality could be used by MultiSelect, Tree, TreeSelect, _and_ Checkbox itself would be more useful and more compatible with the W3C spec.

This is relevant for my team because we attempted to reimplement something analogous to the TreeSelect ourselves (in order to step around certain shortcomings and unresolved bugs in the TreeSelect component) such as https://github.com/primefaces/primeng/issues/12989 and https://github.com/primefaces/primeng/issues/12714, but found that since the checkboxes in TreeSelect feature functionality that isn't part of the Checkbox component itself, we would essentially need to rebuild the Checkbox component from scratch as well, making the project considerably more expensive.

**Comment by mehmetcetin01140** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
