### ISSUE TITLE
Scrollable TabMenu support

### ISSUE THREAD

**Issue by vaiso** [primefaces/primeng#11154]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

It would be really nice if TabMenus could also have scrolling behaviour similar to TabViews, as addressed in [this PR](https://github.com/primefaces/primeng/issues/10119).

Thank you! :)

**Comment by stephanebouget** [comment]
Hello,

is it possible to autohide right arrow according to the layout width ?

For instance, in this case right arrow is usefull: 
![image](https://user-images.githubusercontent.com/13203455/155178700-dacb6269-abec-448c-b058-d529b61189b1.png)

But not in this case because tabs does not fill all the available space : 
![image](https://user-images.githubusercontent.com/13203455/155178436-c9266c2b-a0c8-404e-9693-e07142a9d577.png)

tks for this feature !
