### ISSUE TITLE
Dismissable property in OverlayPanel is not dynamic

### ISSUE THREAD

**Issue by nlachancedev** [primefaces/primeng#11212]
Hi

I found that property "dismissable" in OverlayPanel component is not dynamic. My case is that I want to let the panel be dismissable at first and in certain conditions change his value. For now, this is only handled at component creation as i found here in the code:  https://github.com/primefaces/primeng/blob/ab016d3c33ff83578e6d3d4a229b6b647c4b8b85/src/app/components/overlaypanel/overlaypanel.ts#L125

Thank you.

**Comment by cetincakiroglu** [comment]
Hi, 

Dismissible property works dynamically

Here is a working example.
https://stackblitz.com/edit/primeng-overlaypanel-demo-qe2psz?file=src%2Fapp%2Fapp.component.html

Regards.

**Comment by nlachancedev** [comment]
At creation yes, but when the overlaypanel is shown, and you changed the property afterward it's not considered. Even in your example, we can reproduce. Like open with the dismissable "false" and after change it to "true" when the overlay is still shown, and try to click outside to dismiss it.

In your demo, we can't test from true to false, but in my case, I changed it programmatically in the .ts, but the flow is the same.

**Comment by jurt** [comment]
This issue is still reproducible on provided stackblitz example
STR:
1. Click 'select a product' to open panel
2. Click 'change dismissible' to change it to true
3. Click outside panel 
Observe: Panel not dismisses 

For those who also came across this issue and need a workaround:
get a reference to the panel via ViewChild, and manually call bindDocumentClickListener to make it dismissible, and unbindDocumentClickListener to make it not dismissible
