### ISSUE TITLE
Property target dos not working on p-menu

### ISSUE THREAD

**Issue by guillaume-f** [primefaces/primeng#11226]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/primeng-menu-demo-pxmvs1?file=src/app/app.component.ts

**Current behavior**
I want a property target (_blank) on a menu using using p-menu component. The item is corretly showed inside the menu, but the target does not working and, the code is not present inside de dev console

**Expected behavior**
When the property target is set on a menu item, the target should be work

**Minimal reproduction of the problem with instructions**
The item named "Router" does not working correctly

**Please tell us about your environment:**
Windows, Google chrome, Firefox,...

* **Angular version:** 12.2.16

* **PrimeNG version: 12.2.3

  * **Browser:** all
 
* **Language:** TypeScript 4.3.5

* **Node (for AoT issues):** `node --version` = 14.17.5

**Comment by jayee** [comment]
This problem is not solved correctly.
When using url with no target the page should open with _self (default).
See example "Angular" on https://www.primefaces.org/primeng/menu

Generated source:
<a role="menuitem" class="p-menuitem-link ng-star-inserted" target="undefined" href="http://angular.io" tabindex="0"><span class="p-menuitem-icon pi pi-external-link ng-star-inserted"></span><span class="p-menuitem-text ng-star-inserted">Angular</span></a>

**Comment by Xample** [comment]
Hi, I agree there is a real problem, when passing the url into the `MenuItem`, the target argument is added to the `<a>` tag…. A possible workaround is either to set the property `target` to an empty string `''` or not to use the url and rely on the `routerLink` property
