### ISSUE TITLE
Selectable datatable highlights every row matching selected row

### ISSUE THREAD

**Issue by ryanwawr** [primefaces/primeng#1129]
I have a table with selection mode set to 'single' that happened to have two rows with identical models. Checking one of the rows highlighted both rows as selected. It appears that this is because the [checked] attribute on the table row is set based on the results of isSelected(rowData), which causes any row that exactly matches the selected row to be highlighted/checked. 

This isn't a critical issue for me, since it's easy enough to add more detail to the table and eliminate duplicate rows, but it could cause problems for anyone with a table where repeated rows are valid and expected.

**Comment by SprintDeveloper46** [comment]
I ran into the same situation. However, I believe this is a non-issue. If selection was done on a row and it had a duplicate, I suppose you would want that one selected as well. For selectable rows, there shouldn't be duplicate rows. If there were, how would the user know which one to select?

**Comment by cagataycivici** [comment]
Please provide a test case based on plunkr below and we'll review again.

http://plnkr.co/edit/VZbdZfQ7SuTV87tTkbYR

**Comment by bjansen** [comment]
Hi there, having a similar issue with a `p-tableCheckbox`. This can happen when a row's identifier is set by the server when saving a form for example. If I add two identical lines to a table without saving my form, selecting one line will also select the other one because the discriminating value has not yet been set by the server.

Here's an example based on the docs:

https://primeng-tableselection-demo-xzjea1.stackblitz.io/

**Comment by bjansen** [comment]
Oh, I see there's a workaround: https://github.com/primefaces/primeng/issues/1856#issuecomment-558567845
