### ISSUE TITLE
BUG in p-spinner

### ISSUE THREAD

**Issue by cyberrranger** [primefaces/primeng#1146]
hi, i found a little bug in spinner component

example

`<p-spinner [(ngModel)]="value" [min]="5" [step]="10"></p-spinner>`

if value == 5 and i click down (2x), the value change to 5-10
 i click down (3x), the value change to 5-10-10
...

Kind regards

**Comment by cagataycivici** [comment]
I can't replicate, could it be that your value is a string?

**Comment by cagataycivici** [comment]
Somehow I can't replicate now, is your value an integer?

**Comment by cyberrranger** [comment]
i check this today

**Comment by cyberrranger** [comment]
sry, no bug. 

`import {Component, Input, Output, EventEmitter} from '@angular/core';

@Component({
	selector: 'p-number',
	template: `
		 <label>{{header}}</label>
		 <p-spinner [(ngModel)]="value" [min]="min" [step]="step"></p-spinner>
	`
})
export class InputNumber {
	@Input() header: string = this.header;
	@Input() content: any = this.content;

	value: number = 5;
	min: number = 5;
	step: number = 10;

	constructor() {
	}
}`

works

**Comment by samuller** [comment]
This is often triggered when making the following mistake:
`<p-spinner [(ngModel)]="value" min="0" [step]="step"></p-spinner>`
The minimum value will seem to work correctly, but this error will occur. It is caused by forgetting to add Angular's square brackets for inputs and is harder to detect when using constant values where things will still partially work.

**Comment by dkrysiak** [comment]
In addition to [comment by samuller](#issuecomment-372276668): The same can occur when value is not a number type.
