### ISSUE TITLE
Table: Rows shifting on scroll down

### ISSUE THREAD

**Issue by sladutska-incomm** [primefaces/primeng#11959]
### Describe the bug

When scroll a table with virtualScroll and lazy options, rows are slightly shifted.

[Demo.webm](https://user-images.githubusercontent.com/68010196/191511922-7f54b2d9-114c-40c9-be78-acccfea25e1c.webm)

### Environment

Any

### Reproducer

https://stackblitz.com/edit/primeng-autocomplete-demo-fvgqve?file=src%2Fapp%2Fapp.component.html

### Angular version

14.0.4

### PrimeNG version

14.1.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.17.0

### Browser(s)

Chrome 105

### Steps to reproduce the behavior

1. open example
2. scroll the table

**Comment by cetincakiroglu** [comment]
Hi,

It's not a bug, this happens because you need to set virtualScrollItem size as well. Both virtualScrollItemSize and row height in table body should be same (34px in the example). Here is a refactored working version of your example 
https://stackblitz.com/edit/primeng-autocomplete-demo-r79vnc?file=src%2Fapp%2Fapp.component.html

Regards
