### ISSUE TITLE
Menu: How to set MenuItem's disabled value dynamically in runtime?

### ISSUE THREAD

**Issue by RobersonLuo** [primefaces/primeng#12029]
### Describe the feature you would like to see added

I want the menu item's disabled value to be changed in runtime. 
The scenario is like this, the menu item's disabled value is 'True' by default, once the user select at least one product, the menu item's disabled value  shoud be changed to 'False'.  
I don't know how to set a callback funtion to the menu item's disabled property.

**Comment by ndagovic** [comment]
Since ive had something similar to this problem I'll share the solution I came up with. Personally I have used it to enable dynamic localization or rather language changing but the same logic applies here.

For the menu that is set up in component.ts you would probably have " this.items = [ ... ] "

Entire idea is that you want to re-generate that items array so that it gets updated on demand in the app.

So instead of simply declaring an array (and no, you cant just do a fn call for the true/false on the button props inside the items array since on runtime it will "compile" to a string and then only the string will be returned, I've tried it before) you can replace the array with an anon fn that will return said array.

this.items = () => { return [ <actual array of menu items here>] } and inside that you can do the function calls or checking or what have you to make the buttons enabled or disabled.

Since this can be quite taxing on the performance, an alternative solution would be to have a "fake" items array and a "real" items array.

The "fake" would be the function that is generating the array (in the above example it would be the () => { return [...] } part) and it will be called on demand (when something should be enabled or disabled or what have you and it needs to be updated) and the fake one would then set the actual, or rather the "real" items array to a new value with the button having a different property.

Once the new "real" array is set, it should automatically update.

**Comment by mehmetcetin01140** [comment]
Hi, 

Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog. For enhancement requests and other topics, you can open a new topic in [PrimeNG Discussions](https://github.com/orgs/primefaces/discussions/categories/primeng).
