### ISSUE TITLE
Component: Ripple. Click inside not working

### ISSUE THREAD

**Issue by VolodymyrKornetskyi** [primefaces/primeng#12045]
### Describe the bug

I can't handle click on buttons inside card with Ripple.

### Environment

Angular 14.1.2
primeng 14.1.1

### Reproducer

https://stackblitz.com/edit/primeng-ripple-demo-aftkhw?file=src/app/app.component.html

### Angular version

14.1.2

### PrimeNG version

14.1.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.7.0

### Steps to reproduce the behavior

1. Create card/div with ripple directive
2. Add button with click handler inside created element in step 1
3. Try to click on button from step 2.
4. Ripple effect is working but handler for button - doesn't

**Comment by volvachev** [comment]
Hi, for a quick fix you can use `mousedown` instead of `click`.

**Comment by VolodymyrKornetskyi** [comment]
Ok, I've figured our what is going on. Basically click is not working as ripple is listening mousedown event and if you want listen click inside ripple you can just add mousedown listener to element inside and add preventDefault and stopPropagation

**Comment by amoretti-dev** [comment]
I know it's old topic, but I will give an update, maybe it will help someone.
I'm actually using primeng v. 17.18.8 and if you use `pRipple` directive on `<p-button>` component, you need to click on it for like 1 sec to trigger the `(onClick)` event. I just found out an easy solution: instead of using `<p-button>`, you can use `<button>` element with `pButton` directive and this bug disappear.
