### ISSUE TITLE
Dropdown: Wrong preselected element when both optionValue and dataKey are present

### ISSUE THREAD

**Issue by skkskine** [primefaces/primeng#12135]
### Describe the bug

If a preselected element is provided to a dropdown, and both optionValue and dataKey are present, the selection is _always_ (regarless of the provided value) the first element of the list. If dataKey is removed, the preselected element is set correctly based on the value.

### Environment

Any browser/Stackblitz

### Reproducer

https://stackblitz.com/edit/angular-ivy-cf5fya

### Angular version

14.2.9

### PrimeNG version

14.1.2

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.13.0

### Steps to reproduce the behavior

1. Run the stackblitz example and confirm that the preselection is wrong (always the first element of the list)
2. Remove dataKey from the dropdown tag and check that the preselection is correct

### Expected behavior

The preselection should be correct even if both dataKey and optionValue are provided.

**Comment by hamzajazyri** [comment]
@skkskine this is a simple example to understand clearly how optionValue and dataKey works !

```
// .ts file
cities = [
   {country: "Tunisia", info : { code: "TUN" } },
   {country: "New York", info : { code: "NY" } },
   {country: "Italy", info : { code: "IT" } }
]
selectedCity =  { code: "TUN" };
```
```
// .html file
<p-dropdown
  [formControl]="selectedCity"
  [options]="cities"
  optionLabel="name"
  optionValue="info"
  dataKey="code"
></p-dropdown>
```

In this example, the `info` object is returned as the selected item value. 
so we use the `dataKey` property for comparison between items. 
The `dataKey` should be a path to a field within the `optionValue`. 
In this case, the `dataKey` is set to `code`, so the comparison will be based on the `code` field of the `info` object.

-----
in your example optionValue[dataKey] is undefined, that's why it returns the first item.

**Comment by acampon-sw** [comment]
Im having the same issue, has this been resolved, it is really anoying ?

**Comment by acampon-sw** [comment]
Hi guys, is anyone form prime checking this ? I'm struggling with this issue and its really annoying.
