### ISSUE TITLE
Component: InputNumber

### ISSUE THREAD

**Issue by ProfEibe** [primefaces/primeng#12167]
### Describe the bug

There is an issue with the p-inputnumber currency localization.
Using the currency "EUR" and locale "de-DE" everything works fine. But when I change the locale to "de-AT" for Austria, I can't input more than 4 digits

### Environment

?

### Reproducer

https://stackblitz.com/edit/primeng-inputnumber-demo-eaone5?file=src/app/app.component.html

### Angular version

13

### PrimeNG version

13

### Build / Runtime

Angular CLI App

### Language

ALL

### Node version (for AoT issues node --version)

16.17

### Browser(s)

Chrome

### Steps to reproduce the behavior

#10754
I have created an example stackblitz where you can see and test it:
https://stackblitz.com/edit/primeng-inputnumber-demo-eaone5?file=src/app/app.component.html

### Expected behavior

working input number^^

**Comment by Alhajras** [comment]
The issue is that the regular expression does not work for the Austria format because they use [Replacing `nbsp` as a seperator which is a single white space unlike the german uses `,`. 

Solution:
Use the suggestion from this [link](https://stackoverflow.com/questions/1495822/replacing-nbsp-from-javascript-dom-text-node)
to replace the line: 
https://github.com/primefaces/primeng/blob/0a00cfc25c987850de7bae47be89db6c1005d380/src/app/components/inputnumber/inputnumber.ts#L586

**Comment by mehmetcetin01140** [comment]
Hi,

The issue you mentioned seems to appear in an outdated version of ours. Between the version you referred to and our current version (v17x), we've made numerous improvements, bug fixes, and enhancements, so the issue might have been addressed. If you encounter it in the current version as well, please open an issue with a Stackblitz example.

**Comment by ray-kay** [comment]
We have the exact same issue on PrimeNG 14.2.17-lts
Would there be a fix available for PrimeNG 14 as it is a LTS Version?
