### ISSUE TITLE
Calendar with milliseconds

### ISSUE THREAD

**Issue by GermanoGuerrini** [primefaces/primeng#12190]
### Describe the feature you would like to see added

Hello,

Referring to https://github.com/primefaces/primeng/issues/4571, I'm reopening the request because, looking at the documentation, it has not been implemented yet.
The request is pretty simple to explain: currently, the time widget of the calendar only supports hours, minutes, and seconds.
Some use cases require even higher precision, that's why in my project I extended the class to support it.
I'm not sure my implementation is still compatible with the current version of PrimeNG.
In any case, I think it would be a nice feature to have directly in the framework.

Thanks,
Germano

**Comment by ArteLuke** [comment]
Hello, I also have a use case where I would need the calender to support milliseconds - since you can tell the calendar to use the format unix: [dateFormat]="'@'", which according to the documentation is in [ms], it is kind of odd for me that there isn't a parameter called "showMilliseconds" similar to the parameter "showSeconds", which is already implemented.

It would be great to get some short-term updates on this issue.

br
Lukas

**Comment by mehmetcetin01140** [comment]
Hi, 

Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog. For enhancement requests and other topics, you can open a new topic in [PrimeNG Discussions](https://github.com/orgs/primefaces/discussions/categories/primeng).
