### ISSUE TITLE
Crud | pre-selected option of the dropdown is not displayed if placeholder exist in template mode

### ISSUE THREAD

**Issue by PythonPriya891** [primefaces/primeng#12227]
The selected element is not visible while editing a record in the crud.

**Comment by volvachev** [comment]
Hi, Can you add an example on stackblitz?

**Comment by PythonPriya891** [comment]
![IMG_20221117_145855](https://user-images.githubusercontent.com/109975788/202408615-55727e1b-ad39-4e91-baec-19b67bd59271.jpg)
This is the screenshot when I click on the edit button, here the pre-selected Inventory status is not visible



![IMG_20221117_145917](https://user-images.githubusercontent.com/109975788/202408828-c550f7d6-01b4-41e7-9d7b-e72f7d0e87c3.jpg)
Now after changing the status, and saving it, again if I click on edit button....it shows the changed Inventory status.


Conclusion: Pre selected item in the drop-down for CRUD is not showing

**Comment by cetincakiroglu** [comment]
Hi,

This issue is not related to the Table CRUD, after I reproduce the issue I found that it's related with dropdown templating. The pre-selected option is not displayed if a placeholder exists in templating mode. Changing the issue title and adding it to the 15.0.0 milestone.

Thanks for reporting!

**Comment by cetincakiroglu** [comment]
Hi,

I checked the issue, it seems that it's not related to the dropdown component too. It's just a basic typo in the crud demo.
