### ISSUE TITLE
Add Angular 15 support

### ISSUE THREAD

**Issue by PeterHewat** [primefaces/primeng#12243]
### Describe the bug

PrimeNG 14.2.2 is restricted to Angular < 15
Unable to update to Angular 15

### Environment

Standard Angular / PrimeNG application.

### Angular version

15.0.0

### PrimeNG version

14.2.2

### Build / Runtime

Angular CLI App

### Language

ALL

### Node version (for AoT issues node --version)

18.12.1

**Comment by kyjus25** [comment]
Don't mind me just watchin 👀

**Comment by AndrewAKovalenko** [comment]
Also it would be great to migrate components and directives to standalone versions to be able to use Directive Composition API and etc.

**Comment by slyk** [comment]
Like and subscribe it :) wait it

**Comment by j-s-fesfwd** [comment]
What are the plans about standalone components?
Will be a big refactoring needed with `XxxModule`, e.g. `MessagesModule`?
Or will e.g. `MessagesModule` have the same name, but be converted to a standalone component under the hood instead?

**Comment by kyjus25** [comment]
@j-s-fesfwd Given how opinionated Angular is, I would be very surprised to see them using the `XxxModule` naming convention if it is not truly a module. 

Since standalone components are interop-able with normal ones, I'd speculate they will unblock people from being able to use v15 first before worrying about making them standalone which could come at a release at a later date.

They could either introduce a breaking change and force every component to standalone, or they could include both module and standalone options (which seems like a pain to tree-shake and would probably require import changes). 

I guess we will see what the community does. If it becomes customary in the library community to provide both options, I reckon they will follow suit.

However, I'm just speculating and would love to hear from a PrimeNG dev. Angular 15 is the hot topic right now, I'm sure they've got it covered. With such an integral library like PrimeNG is I'd imagine they will get an update out relatively quickly.

**Comment by kyjus25** [comment]
🙌 🙌 🙌 YES

Thank you @cetincakiroglu 🫡. You are the hero this world needed

**Comment by cetincakiroglu** [comment]
> 🙌 🙌 🙌 YES
> 
> Thank you @cetincakiroglu 🫡. You are the hero this world needed

Happy to help, you're welcome :)
