### ISSUE TITLE
TreeTable: paginator doesn't work nicely with VirtualScroll

### ISSUE THREAD

**Issue by yukie1412** [primefaces/primeng#12262]
### Describe the bug

a treetable with virtualScroll & paginator doesn't render initially hidden rows properly.

![treetableScroll](https://user-images.githubusercontent.com/2449212/202997410-939907ba-7949-4fdc-b1bb-9645669cb0cb.gif)

### Environment

prod

### Reproducer

https://stackblitz.com/edit/primeng-treetablescroll-demo-tj4i9s

### Angular version

15.0.0

### PrimeNG version

14.2.2

### Build / Runtime

TypeScript

### Language

TypeScript

### Node version (for AoT issues node --version)

14.17.3

### Browser(s)

edge 107.0, chrome 107.0

### Steps to reproduce the behavior

1. go to https://primeng-treetablescroll-demo-tj4i9s.stackblitz.io
2. scroll down
3. notice the whitespace in table & number of rows (6) < than allowed rows (30)

### Expected behavior

should see additional rows when scrolling down the page, instead of whitespace that preserves the row space

**Comment by cetincakiroglu** [comment]
Hi,

One of the main purposes of the virtual scroll is to scroll through data without the need to change the page. Your use case is invalid since two components shouldn't be used together. They serve different purposes and do not fit or complement each other and it's inevitable to experience such a defect.

Closing the issue since the use case is invalid.

Regards

**Comment by yukie1412** [comment]
@cetincakiroglu why can't virtual scroll be combined with pagination? i understand virtual scroll is designed for large amount of data, but that doesn't prevent it from having pagination to split the large data even more.

**Comment by cetincakiroglu** [comment]
Hi @yukie1412,

The virtual scroll is meant to scroll through and manage large amounts of data without changing the page. So pagination is not a discussion in this case. It's just like trying to eat soup with a fork, not a user-friendly combination. Irrelevant and different purposes. Why do you need to change the page if you want unlimited scroll? It's not feasible. Splitting data is up to your API calls and how you manage it. In virtual scroll, it renders a large amount of data partially by calculating item height to prevent performance issues while loading it so the user can scroll unlimited. All the data you want to separate by pagination is already rendered partially by virtual scroll as the user scrolls, so you don't need a page action.  Here, you don't need pagination since it won't solve your problem, you need to customize your API calls depending on your needs. 

Regards
