### ISSUE TITLE
p-toggleButton: The icon is left aligned but it should be centered

### ISSUE THREAD

**Issue by ruskovweb** [primefaces/primeng#12288]
### Describe the bug

The icon of the component should be centered if the button doesn't have a label. It is broken even in the docs: https://www.primefaces.org/primeng/togglebutton

![image](https://user-images.githubusercontent.com/24957807/204229134-9589c977-6e6a-41f6-b90e-5259ebc36d59.png)
![image](https://user-images.githubusercontent.com/24957807/204229164-f5d94cc1-3850-4843-8e52-8801d849c934.png)

### Environment

Firefox 102.3.0esr (64-bit)

### Angular version

~14.0.0

### PrimeNG version

^14.2.2 | v15.0.0-rc.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.15.0

### Browser(s)

All

### Expected behavior

Centered icon

**Comment by kyjus25** [comment]
The offending styling appears to be some padding that has been broken since v14

https://github.com/primefaces/primeng/blob/a7c7b1585b692088d6d44fbbb015bc8080c44bbb/src/assets/components/themes/lara-light-blue/theme.css#L1971

![Screenshot from 2022-11-28 16-52-46](https://user-images.githubusercontent.com/6710794/204397714-004a0006-83f6-427d-852c-435862f5ec58.png)

**Comment by kyjus25** [comment]
Fixed in #12301, this can be resolved

**Comment by cetincakiroglu** [comment]
Hi,

Issue is fixed in https://github.com/primefaces/primeng/pull/12301

Closing the issue, thanks for your support!
