### ISSUE TITLE
Autocomplete event doesn't get fired in Model Driven Form

### ISSUE THREAD

**Issue by bogacg** [primefaces/primeng#1241]
Example in documentation is pretty straight-forward for model driven forms and I wanted to use it like so.
When page loaded at first all array elements are present under ul, as soon as I type I expect completeMethod bound event handler gets executed. But it doesn't and yet li elements under ul gets deleted.

Do I need to make extra changes in order to use autocomplete with reactive forms?

```
    this.userForm = this.formBuilder.group({
      brand: [''] });
```

```
<form class="form-inline" [formGroup]="userForm" novalidate autocomplete="off">
	<p-autoComplete formControlName="brand" [suggestions]="brands" (completeMethod)="filterBrands($event)"></p-autoComplete>
</form>
```

**Comment by bogacg** [comment]
Deleting **node_modules** folder and installing packages fresh solved this.

**Comment by cagataycivici** [comment]
@Mrtcndkn review for RC5.

**Comment by Mrtcndkn** [comment]
I've replicated the issue and working on it.

**Comment by Mrtcndkn** [comment]
Sorry for the wrong information the problem is that minLength attribute default value is 3 so for firing completeMethod you should write at least 3 characters or you can change [minLength]=1.But this default value is not very handy so we decided to change it to 1 after RC5.This means after RC5 your code will be fine.

**Comment by cagataycivici** [comment]
You may also try with [minLength]="1" to see if it helps now.
