### ISSUE TITLE
Component: Messages

### ISSUE THREAD

**Issue by Rahulvr7** [primefaces/primeng#12887]
### Describe the bug

There is no onClose event available on the PrimeNg Messages component. Users can't perform actions when closing the Messages.

### Environment

Visual Studio Code

### Angular version

13.3.8

### PrimeNG version

13.4.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.17.0

**Comment by BallisticPain** [comment]
I need this functionality too. I do not use the MessageService as I am using NGRX Store to manage the messages themselves. I need the ability to know not just when someone closed the message with the closing icon, but also if the message was closed due to the `life` expiring. This way I can remove the message from the Store so it won't show up the next time I need to display a message.

**Comment by mehmetcetin01140** [comment]
Hi,

The issue you mentioned seems to appear in an outdated version of ours. Between the version you referred to and our current version (v17x), we've made numerous improvements, bug fixes, and enhancements, so the issue might have been addressed. If you encounter it in the current version as well, please open an issue with a Stackblitz example.
