### ISSUE TITLE
Calendar | Overlay misaligned (w/ multiple months)

### ISSUE THREAD

**Issue by cetincakiroglu** [primefaces/primeng#12889]
<img width="1458" alt="Screenshot 2023-04-14 at 18 46 19" src="https://user-images.githubusercontent.com/69278826/232092361-4b04572f-2e79-4288-8bec-4947cfda04a8.png">

**Comment by arthur-alvesaf** [comment]
Hi @cetincakiroglu, I don't know if the fix has already been worked on, but I investigated this same bug yesterday and created a PR with the fix. Please look at the issue #13008 where I have described the problem.

I see this is tagged to fix for v15 and v16, but the bug is also present in v14, as I describe in the issue I logged.

Thanks in advance for the review, and I hope this fix can make its way into the next patch release for v14 also.

**Comment by arthur-alvesaf** [comment]
Hey @cetincakiroglu, I'm bumping this to request a review of my PR in #13009. My PR is a one-line fix, please take a look when you have a chance.

**Comment by arthur-alvesaf** [comment]
Hi @cetincakiroglu. I realized my PR still didn't address the issue fully. There was just one small change to be made, so now this is a 2 line PR 😬 

I tested with the overlay component and the calendar component, specifically for the case where the 'popup' (dropdown style) overflowed over the right side of the screen. In my branch, it seems this is fixed for both of these cases now.

**Comment by brunocrg** [comment]
Hi @arthur-alvesaf, thanks a lot for the fix, I also tested your changes and now it works like a charm. Great job! 🚀

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
