### ISSUE TITLE
DropDown: open even if disabled

### ISSUE THREAD

**Issue by ikiliki** [primefaces/primeng#12973]
### Describe the feature you would like to see added

I would like to be able to open the dropdown even if it is disabled.

### Describe the solution you'd like

Add a boolean input that allows this behavior

**Comment by mbenrey** [comment]
The problem is even worse with the multiselect component in readonly mode when there are multiple selected options. 
Users may only see the beginning of the list because the dropdown might be too small, which prevents them from viewing their selections. 
To solve this issue, users should be able to open the dropdown in disable mode and view the options without making any changes.

![image](https://user-images.githubusercontent.com/40571116/235490741-e5707d1a-5ae3-4bab-8064-3b4196324aeb.png)

**Comment by mertsincan** [comment]
Unfortunately, we can't add the disabled behavior @ikiliki requested. But, @mbenrey yes this may be a bug. Could you please create a Github issue? When HTML select element has readonly attribute, it opens its panel.

Best Regards,
