### ISSUE TITLE
Tooltip: Doesn't work. Show console error

### ISSUE THREAD

**Issue by SoyDiego** [primefaces/primeng#13190]
### Describe the bug

When I'm doing hover on an element, the component tooltip doesn't appear and show an error on console.

![image](https://github.com/primefaces/primeng/assets/19764334/7160d48a-e561-4c59-b478-8db39ac347d7)

### Environment

Angular 16
PrimeNG 16

### Angular version

16.0.5

### PrimeNG version

16.0.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.16.18

### Steps to reproduce the behavior

1) Hover on an element that has tooltip option
2) Open the Console and you can see the error.

![image](https://github.com/primefaces/primeng/assets/19764334/aabb54ab-af04-41ee-8113-16210c969861)

### Expected behavior

Show the tooltip correctly

**Comment by algragon** [comment]
The error message on the console is "Cannot append null to [object HTMLDivElement]".

This comment is just a helper for search engines to find the actual text of the error message (instead of an non-machine-readable picture) and come up with this issue, when some future developer runs into this error.
