### ISSUE TITLE
zIndex of ConfirmDialog is not adaptive (always less by one)

### ISSUE THREAD

**Issue by gitkhartmann** [primefaces/primeng#13498]
### Describe the bug

The modal ConfirmDialog opened after a normal modal dialog has a zIndex lower than the normal dialog and is not visible anymore.

### Environment

Angular version:  14.2.0
PrimeNG version:  14.2.3

### Angular version

14.2.0

### PrimeNG version

14.2.3

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

9.1.2

**Comment by dkhrunov** [comment]
Same issue

**Comment by SoyDiego** [comment]
Can you share a stackblitz, please?

**Comment by dkhrunov** [comment]
### Demo
[Stackblitz](https://stackblitz.com/edit/primeng-sidebar-demo-rndae4?file=src%2Fapp%2Fapp.component.ts)

![Screenshot 2023-08-15 at 09 06 39](https://github.com/primefaces/primeng/assets/25565058/4f897973-1cb2-4082-be51-0992442fb712)

### Steps to reproduce

1. Open sidebar
2. In the opened sidebar invoke confirm dialog

### Expected behavior

- Since the ConfirmDialog opens after the Sidebar, the ConfirmDialog must be on top of the Sidebar.

### Supposed Problem
I deep to styles and source code, and this is what I found out:

Dialog modals (Dialog/DynamicDialog/ConfirmDialog components) uses backdrop as wrapper over dialog content. **This leads to this problem described above.**

ConfirmDialog [moveOnTop](https://github.com/primefaces/primeng/blob/14.2.3/src/app/components/confirmdialog/confirmdialog.ts#L454) method call ZIndexUtils.set() util and sets this ConfirmDialog z-indexes styles and his backdrop (current z-index - 1).

And finally wrapper (backdrop) has same z-index (as the screenshot above = _z-index: 1101_) the same as the previously opened sidebar z-index (as the screenshot above = _z-index: 1101_)

**Comment by dkhrunov** [comment]
I can suggest such a solution - increment the current z-index, which is stored in the _ZIndexUtils_ utility for the Dialog, not by one, but by two points at once, then the backdrop value will be higher than the sidebar value.

**Comment by dkhrunov** [comment]
> I can suggest such a solution - increment the current z-index, which is stored in the _ZIndexUtils_ utility for the Dialog, not by one, but by two points at once, then the backdrop value will be higher than the sidebar value.

This is what we did in our code to get around this problem, and it works fine.

**Comment by SoyDiego** [comment]
Hi @dkhrunov, thanks for your examples and explanation.
I did a PR with your solution, you can check here: https://github.com/primefaces/primeng/pull/13501.
When I have tested the problem, always I saw all perfectly and anything affect the functionality, only I saw the zIndex position repeated like you `1102` but doesn't affect my functionality or I don't know I didn't notice because all was working fine.
By the way, I did the PR increasing the zIndex to have differents. Thanks!

**Comment by dkhrunov** [comment]
> Hi @dkhrunov, thanks for your examples and explanation. I did a PR with your solution, you can check here: #13501. When I have tested the problem, always I saw all perfectly and anything affect the functionality, only I saw the zIndex position repeated like you `1102` but doesn't affect my functionality or I don't know I didn't notice because all was working fine. Anyway, I did the PR increasing the zIndex to have differents. Now we should wait if PrimeNG Team approve it. Thanks!

Thank you!
