### ISSUE TITLE
DynamicDialog: ExpressionChangedAfterItHasBeenCheckedError for attr.aria-labelledby

### ISSUE THREAD

**Issue by yarikwest** [primefaces/primeng#13497]
### Describe the bug

ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value for 'attr.aria-labelledby': 'pn_id_157_header'. Current value: 'pn_id_159_header'. Expression location: DynamicDialogComponent component.

aria-labeledby is assign for div with class 'p-dynamic-dialog'

### Environment

Basic as possible, Angular + PrimeNG only

### Reproducer

https://stackblitz.com/edit/pfqjsp?file=package.json

### Angular version

16.2.0

### PrimeNG version

16.2.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.16.0

### Browser(s)

Firefox 116.0

### Steps to reproduce the behavior

1. Open dynamic dialog

**Comment by VolodymyrKornetskyi** [comment]
The same issue

**Comment by johanrg** [comment]
Same issue here too.

**Comment by chillapp** [comment]
The same issue

**Comment by SoyDiego** [comment]
I was checking the problem and try using changeDetectorRef, but I still have't been able to fix the error.
I will continue trying 👍🏾

**Comment by tysoc1222** [comment]
Same issue here

**Comment by sergeiglikstein** [comment]
My work around, example code that I am working on.
I'll stop using it once the issue is fixed.

`import { Injectable } from '@angular/core';
import { DialogService, DynamicDialogComponent } from 'primeng/dynamicdialog';
import { ConfirmDialogComponent } from '../../components/confirm-dialog/confirm-dialog.component';
import { ConfirmDialog } from '../../models/confirm-dialog.model';

@Injectable({
  providedIn: 'root'
})
export class SharedDialogService {
  constructor(public dialogService: DialogService) {}

  openConfirmDialog(data: ConfirmDialog, width?: string) {
    const ref = this.dialogService.open(ConfirmDialogComponent, {
      header: data.title,
      data,
      width: width || '600px',
      dismissableMask: false,
      modal: true
    });

    const dialogRef = this.dialogService.dialogComponentRefMap.get(ref);
    const dynamicCOmponent = dialogRef?.instance as DynamicDialogComponent;

    const ariaLabelledBy = dynamicCOmponent.getAriaLabelledBy();
    dynamicCOmponent.getAriaLabelledBy = () => ariaLabelledBy;
    return ref;
  }
}
`

**Comment by kwood-gmr** [comment]
@sergeiglikstein 
> My work around, example code that I am working on. I'll stop using it once the issue is fixed.
> 
> ```

Thank you - this has worked for me

**Comment by gucal** [comment]
@SoyDiego sent a PR that resolved the issue.
Thanks for report.

**Comment by fbobbio** [comment]
> @SoyDiego sent a PR that resolved the issue. Thanks for report.

@gucal and @SoyDiego thanks!
I think the actions failed due to missing prettier:

Sent this PR https://github.com/primefaces/primeng/pull/13511

First time contributing here so I am not sure about the workflow to get a new version/tag published :) Would be good to have this fix available.

Thanks again ✌️

**Comment by mountpoint** [comment]
in which release will this bug be fixed?

**Comment by SoyDiego** [comment]
> in which release will this bug be fixed?

Wil be in 16.2.1

![image](https://github.com/primefaces/primeng/assets/19764334/afb84d06-2c77-42a1-bfde-b45a385c5300)

**Comment by gucal** [comment]
The current solution has been replaced with a better solution. https://github.com/primefaces/primeng/pull/13538

**Comment by Tilesto** [comment]
Just in case) The same error for 16.2.0. Looking forward to 16.2.1)

**Comment by SoyDiego** [comment]
> Just in case) The same error for 16.2.0. Looking forward to 16.2.1)

Yes, will be fixed in next release and the currently 16.2.0 has the problem
