### ISSUE TITLE
OrderList: Does not sort correctly when data is refreshed while item is selected

### ISSUE THREAD

**Issue by TheMeerkat** [primefaces/primeng#13544]
### Describe the bug

Selecting an item in an OrderList Component and then refreshing the data causes the OrderList component to become non-functional.  Causes undefined references and the array in the component now has negative indexing and undefined values inserted.

![image](https://github.com/primefaces/primeng/assets/1631493/585fe921-20a5-41df-96a5-2094589969f5)

### Environment

 dev

### Reproducer

https://stackblitz.com/edit/primeng-orderlist-demo-6qysau?file=src%2Fapp%2Fapp.component.tshttps://stackblitz.com/edit/primeng-orderlist-demo-6qysau?file=src%2Fapp%2Fapp.component.ts

### Angular version

14.0.1

### PrimeNG version

14.0.2

### Build / Runtime

TypeScript

### Language

TypeScript

### Node version (for AoT issues node --version)

18

### Steps to reproduce the behavior

1. Load an OrderList Component with data.
2. Select an Item.
3. Refresh Data.
4. Click down arrow.
5. View console logs & OrderList view, errors and item data disappear.

Note: Logging out OrderList shows odd values in list and negative array indexes after these steps are taken.

### Expected behavior

Data refreshes and selects the previously selected items or the selections are removed.

**Comment by melloware** [comment]
@SoyDiego can you look at this one since you were recently in Orderlist?  Definitely looks like a bug

**Comment by SoyDiego** [comment]
> @SoyDiego can you look at this one since you were recently in Orderlist? Definitely looks like a bug

I was checking a little bit but I didn't have luck with this problem :(
Sorry

**Comment by SoyDiego** [comment]
@melloware @TheMeerkat 

I don't know if is a problem of the Orderlist.
If I'm not wrong the problem is because:

(The buttons are disabled on init)

1) You are selecting 1 item (the buttons will be enabled)
2) You press refreshData (Here start your problem, the items are updated again **but you lost the selected item (you don't have more the border in the item and the buttons continue enabled)**
3) You are pressing the Down Arrow **(and show an error because you don't have item selected, you lost in the previous step)**

When you are doing a refreshData you should try to restart your component or disable the buttons If you don't have selected any item.

I don't know if what I'm saying is correct, but it's what I could see doing the research.

Try to follow this step:

1) Select an Item.
2) Refresh Data.
3) Select an Item again (because you lost in the previous step)
3) Click down arrow.
4) No errors :)

Thanks

**Comment by FlipWarthog** [comment]
I think the root issue might be an object equality problem. Since the value list is being recreated but the old selection still exists in the component, each item in selection is _not equal_ to any item in the value list based on the logic in ObjectUtils.findIndexInList:
```js
    public static findIndexInList(item: any, list: any): number {
        let index: number = -1;

        if (list) {
            for (let i = 0; i < list.length; i++) {
                if (list[i] == item) {
                    index = i;
                    break;
                }
            }
        }

        return index;
    }
```

This seems to lead to an invalid state within the component because the methods for move up/down/top/bottom guard check for selection being populated but don't guard for -1 indexes being returned from the ObjectUtils call:
```js
    moveUp() {
        if (this.selection) {
            for (let i = 0; i < this.selection.length; i++) {
                let selectedItem = this.selection[i];
                let selectedItemIndex: number = ObjectUtils.findIndexInList(selectedItem, this.value);

                if (selectedItemIndex != 0 && this.value instanceof Array) {
                    let movedItem = this.value[selectedItemIndex];
                    let temp = this.value[selectedItemIndex - 1];
                    this.value[selectedItemIndex - 1] = movedItem;
                    this.value[selectedItemIndex] = temp;
                } else {
                    break;
                }
```

Based on what I'm seeing in equivalent code on the React side, this may be solved with a dataKey for object comparison:
```js
    static findIndexInList(value, list, dataKey) {
        if (list) {
            return dataKey ? list.findIndex((item) => this.equals(item, value, dataKey)) : list.findIndex((item) => item === value);
        }

        return -1;
    }
```

As a workaround, it looks like you can simply bind the selection to an array you control and clear it when the values are refreshed (or fill it with the equivalent items from the newly created products list if you want to retain he selection):
```js
export class AppComponent {
  products: Product[];
  selectedProducts: Product[];

  // omitted
  refreshData() {
    this.selectedProducts = [];
    this.productService
      .getProductsSmall()
      .then((cars) => (this.products = cars));
  }
}
```
```html
<p-orderList
  [value]="products"
  [selection]="selectedProducts"
  [listStyle]="{ height: 'auto' }"
  header="List of Products"
  filterBy="name"
  filterPlaceholder="Filter by name"
  dragdrop="true"
  (onReorder)="dump()"
  #orderList
>
```

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
