### ISSUE TITLE
16.3.1 regression: p-overlayPanel dismisses when making changes to nested p-multiSelect

### ISSUE THREAD

**Issue by NateRadebaugh** [primefaces/primeng#13601]
### Describe the bug

I have a p-multiSelect inside of p-overlayPanel. When the user toggles selection of a p-multiSelect, the p-overlayPanel dismisses.

### Environment

browser

### Angular version

16.2

### PrimeNG version

16.3.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

v18.17.1

### Browser(s)

Chrome

### Steps to reproduce the behavior

1. Open overlay panel
2. Open multiselect
3. Choose an item
4. Overlay panel closes automatically!

### Expected behavior

Overlay panel should stay open until I click away or programatically close it.

**Comment by penihel** [comment]
i think i have the same problem with p-calendar here #13605

**Comment by penihel** [comment]
nothing about this?

**Comment by penihel** [comment]
nothing ? :(

**Comment by bbehling** [comment]
I found a workaround for this was to not append to the body, but append to another div then adjust the placement of the popup with some css.

**Comment by gamerish96** [comment]
Hi, I have the same problem by using a p-listbox component inside the OverlayPanel. The problem is present starting from version 16.3.0, as I found out by testing the versions from 16.0.0 to 16.3.1 the last "safe" version where the bug is not present is 16.2.0.

By navigating the issues I think the regression was introduced with the fix from #13480.

**Comment by penihel** [comment]
nothing ? :(

**Comment by anlampe** [comment]
Hi @gamerish96, I created a second PR #13810  which restores even more of the original code of the OverlayPanel, because your fix alone didn't work for us (See [stackblitz example](https://stackblitz.com/edit/ixhekz?file=src%2Fapp%2Fdemo%2Foverlay-panel-template-demo.html)). Maybe you could have a look.

**Comment by gamerish96** [comment]
Hi @anlampe, I tested your example with the dropdown with my fix applied and without the _appendTo="body"_ it works, you could try it too.

**Comment by anlampe** [comment]
> Hi @anlampe, I tested your example with the dropdown with my fix applied and without the _appendTo="body"_ it works, you could try it too.

Sure, but it also worked with `appendTo="body"` before, so I'd perfer to fix both. Thanks for having a look.

**Comment by zakharenkov** [comment]
I confirm. Appears in version 16.5.0

**Comment by jayee** [comment]
Please fix this annoying bug

**Comment by NateRadebaugh** [comment]
This is not fixed in `16.7.1` still

**Comment by anlampe** [comment]
Yes, I'm aware of this issue. Unfortunately only #13809 was merged, so I updated #13810 and am still waiting for a review.

**Comment by NateRadebaugh** [comment]
Thanks -- @cetincakiroglu is this something on your radar?

**Comment by NateRadebaugh** [comment]
Good idea, I've opened a new bug with the updated details #14120 14120
