### ISSUE TITLE
Component: Inplace component issue.

### ISSUE THREAD

**Issue by RightCursorTech** [primefaces/primeng#13610]
### Describe the bug

Inplace closeicon custom template is wrapped around button. There is no option to customize the closeicon button.

### Environment

Angular v16.2.0
PrimeNG v16.3.1

### Angular version

16.2.0

### PrimeNG version

16.3.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.16.1

### Steps to reproduce the behavior

https://stackblitz.com/edit/erpc4f-sw39lc?file=src%2Fapp%2Fdemo%2Finplace-input-demo.html

1. closeicon template is wrapped arount button tag.
2.  Modified value in edit mode should be updated when switched back to view mode.

**Comment by SoyDiego** [comment]
Stackblitz? Screenshot?

**Comment by RightCursorTech** [comment]
https://stackblitz.com/edit/erpc4f?file=src%2Fapp%2Fdemo%2Finplace-input-demo.html

Additionally I'm unable to bind same input field in the view mode and edit mode.

**Comment by SoyDiego** [comment]
> https://stackblitz.com/edit/erpc4f-sw39lc?file=src%2Fapp%2Fdemo%2Finplace-input-demo.html
> 
> Additionally I'm unable to bind same input field in the view mode and edit mode.

Put the issue in your post and all the information in your first post. 
It's better to all the people who will try to help you or PrimeNG Team

**Comment by cetincakiroglu** [comment]
Hi,

closeicon template is not suitable to put components inside. It's designed for SVG icons or custom icons in general. The reason this happens, you're trying to put a button inside an icon template of a button. 

The reason why you can't bind a value because you're not using ngModel. For more info about ngModel and form inputs please visit the official angular docs.

How to use inputtext directive: https://primeng.org/inputtext#basic

Here is a refactored version of your example: https://stackblitz.com/edit/erpc4f-zmdph5?file=src%2Fapp%2Fdemo%2Finplace-input-demo.html,src%2Fapp%2Fdemo%2Finplace-input-demo.ts

Closing the issue since there isn't a bug.
