### ISSUE TITLE
Multiselect: Incorrect view with selected items

### ISSUE THREAD

**Issue by BearsPunch** [primefaces/primeng#13654]
### Describe the bug

After update in common.css.p-icon-wrapper  from display: flex to display: inline-flex; with selected items, control renders incorrect, with additional row.
![image](https://github.com/primefaces/primeng/assets/66436099/47a09531-96ef-4ee9-a56d-d2c1cac93742)

### Environment

any

### Angular version

16.2.2

### PrimeNG version

16.3.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.14.0

### Browser(s)

any

### Steps to reproduce the behavior

1) Create Multiselect
2) Select values

### Expected behavior

Correct render
![image](https://github.com/primefaces/primeng/assets/66436099/4af2afa9-d6a0-4aac-ab76-65b45ddfd75b)

**Comment by SoyDiego** [comment]
Hi, can you share a stackblitz, please?

**Comment by MayerMar** [comment]
Demo: one p-multiselect with the problem, one p-multiselect with the fix (forced via styles.css)
https://stackblitz.com/edit/7qd5w1?file=src%2Fstyles.scss

Only happens when the Input `[showClear]` is used. 
Class that causes the Problem:
```
.p-icon-wrapper {
    display: inline-flex;
}
```

**Comment by SoyDiego** [comment]
Hi, I created a PR in the project `primeng-sass-theme` because is the correct place in this case.
You can check here: https://github.com/primefaces/primeng-sass-theme/pull/54.

![fixed multiselect](https://github.com/primefaces/primeng/assets/19764334/4dc723bf-7354-4b1d-b74d-a37790d11e25)

I cannot modify the line that you suggested @MayerMar because will affect another styles.
Now it's solved and we should wait PrimeNG Team approve it.

Thanks
