### ISSUE TITLE
tab navigation broken on p-dropdown

### ISSUE THREAD

**Issue by stephanebouget** [primefaces/primeng#13774]
### Describe the bug

Since 16.3.X version, navigation with tabulation key is broken by p-dropdown component
![image](https://github.com/primefaces/primeng/assets/13203455/b193c272-7123-4bf5-998c-4487e3ff9ade)

You can try  here it's KO:
https://primeng.org/dropdown

It's OK on 16.2.X and older version:
https://www.primefaces.org/primeng-v15-lts/dropdown

### Environment

prime ng 16.3.X and newer

### Angular version

16.4.X

### PrimeNG version

16.X

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.14

### Browser(s)

chrome

### Steps to reproduce the behavior

- click on the page
- navigate with tab key

when focus comes to p-dropdown, tab key lost navigation

### Expected behavior

when focus comes to p-dropdown, and after another tab keypress, focus must going to next element

**Comment by VilleKoo** [comment]
When enabling filter or editable options it works as expected.

**Comment by mnhock** [comment]
We run into this issue as well.

**Comment by lixaotec** [comment]
+1

**Comment by JesusMurua** [comment]
The problem is that the new components, for some reason, don't take the new attributes. Just need to apply this in global style.scss file

/**

Fix for p-dropdown item highlight on keyboard navigation.
The legacy theme is missing styles for the .p-highlight class,
making keyboard navigation invisible. This rule restores that visibility.
/
.p-dropdown-panel .p-dropdown-items .p-dropdown-item.p-highlight {
background: #e9ecef !important;
color: #495057 !important;
}
/*

Fix for keyboard navigation highlight in list components (Dropdown, MultiSelect, etc.).
PrimeNG v17 uses the data-p-focused="true" attribute for keyboard focus,
which is not styled by legacy themes like Olympia. This rule adds the
necessary visual feedback.
*/
[data-p-focused="true"] {
background: #e9ecef !important;
color: #495057 !important;
}
