### ISSUE TITLE
Focus trapped in Dropdown component 

### ISSUE THREAD

**Issue by JenWue** [primefaces/primeng#13778]
### Describe the bug

When I tab through a form mask containing multiple different input elements using the Tab key after getting the focus inside a PrimeNG Dropdown element the focus is trapped so there is not way to get the focus out using the keyboard navigation. The issue can be easily reproduced on the PrimeNG documentation and example website. Dropdown component should not react with "preventDefault()" on the Tab keydown event.

### Environment

Angular 16 (16.2.4) and PrimenNG 16.3.1

### Angular version

16.2.4

### PrimeNG version

16.3.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.20.1

### Browser(s)

Chrome 117

**Comment by ashikjs** [comment]
@JenWue   What is your expected behavior ??

**Comment by ashikjs** [comment]
I guesses this issue already reported by others. #13774

**Comment by arjunreddy-001** [comment]
I am also facing this issue in v16.5.1
It was working fine in v15.4.1

Below code in v16.5.1 doesn't work with tab traversing -
`<p-dropdown
    [options]="options"
    optionLabel="name"
    optionValue="value"
    styleClass="p-dropdown-sm"
    [formControlName]="controlName"
  ></p-dropdown>`

But, without options it's working - (without options dropdown is of no use 🤷‍♂️)
`<p-dropdown
    styleClass="p-dropdown-sm"
    [formControlName]="controlName"
  ></p-dropdown>`

**Comment by mnhock** [comment]
We run into this issue as well.

**Comment by richard-collette-precisely** [comment]
Seems to still be an issue and is related to 
https://github.com/primefaces/primeng/issues/13957

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation and try the latest PrimeNG version(v19). If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,

**Comment by richard-collette-precisely** [comment]
This is an AWFUL way to manage a backlog.  Closing out issues with no related commit.  No validation of the issue.  You're basically dismissing the input of your paying customers.

**Comment by mertsincan** [comment]
PLEASE SEE https://github.com/primefaces/primeng/issues/16105#issuecomment-2562951043

**Comment by JesusMurua** [comment]
The problem is that the new components, for some reason, don't take the new attributes. Just need to apply this in global style.scss file

/**

Fix for p-dropdown item highlight on keyboard navigation.
The legacy theme is missing styles for the .p-highlight class,
making keyboard navigation invisible. This rule restores that visibility.
/
.p-dropdown-panel .p-dropdown-items .p-dropdown-item.p-highlight {
background: #e9ecef !important;
color: #495057 !important;
}
/*

Fix for keyboard navigation highlight in list components (Dropdown, MultiSelect, etc.).
PrimeNG v17 uses the data-p-focused="true" attribute for keyboard focus,
which is not styled by legacy themes like Olympia. This rule adds the
necessary visual feedback.
*/
[data-p-focused="true"] {
background: #e9ecef !important;
color: #495057 !important;
}
