### ISSUE TITLE
Component: Accordion Component Allows Tab Navigation Into Closed Accordion Tabs

### ISSUE THREAD

**Issue by willmca** [primefaces/primeng#13845]
### Describe the bug

When navigating an Accordion component via the keyboard, if there are focusable elements inside of a closed accordion tab, the 'tab' key focuses on and accesses these focusable elements. The tab key should only focus on elements inside of an accordion tab when the tab is open.

### Environment

Windows

### Reproducer

https://stackblitz.com/edit/admo5t?file=src%2Fapp%2Fdemo%2Faccordion-basic-demo.html

### Angular version

16.2.1

### PrimeNG version

16.3.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.19.0

### Steps to reproduce the behavior

1. Create an accordion component with one or more focusable elements inside of a closed accordion tab
2. Use tab key to navigate through the accordion component until you get to the closed accordion tab containing focusable elements
3. Use tab key to attempt to navigate to the next closed accordion tab
4. Tab key will shift focus to focusable elements inside of a closed accordion tab

### Expected behavior

When navigating via keyboard, the focus should not enter a closed accordion tab,

**Comment by cetincakiroglu** [comment]
Hi,

The visibility state of the accordion tab causes this issue. In angular, we cannot append `display:none` to the element in the animations. The solution provided in your PR is not wrong, however it's not acceptable because selecting all the elements within the content and tweaking tabindex properties is not a best practice. Instead, solution should be provided in the animation states. New solution is provided in here https://github.com/primefaces/primeng/commit/f28fb531dc882c599467dd694f2f62339fac93a5 by simply managing `visibility` of the component inside the animation.

Closing your PR as well.

Thanks a lot for reporting the issue!
