### ISSUE TITLE
ColumnToggler for DataTable

### ISSUE THREAD

**Issue by mcwebdev** [primefaces/primeng#139]
Implementation os Show/Hide Columns via toggle icon or some other controller. 

example: http://issues.wenzhixin.net.cn/bootstrap-table/

I really like those table admin buttons and feel they fall inline with ng-prime dropdown component.

**Comment by cagataycivici** [comment]
Instead of a new component, I've used multiselect and created a demo at DataTable Showcase, here is how it looks like until it is deployed online.
<img width="789" alt="screen shot 2016-04-09 at 14 33 27" src="https://cloud.githubusercontent.com/assets/686247/14403493/b0ddaeae-fe60-11e5-8c8a-6da80735223a.png">

**Comment by mcwebdev** [comment]
This is fantastic, many thanks!!
