### ISSUE TITLE
Component: p-dropdown won't focus to next input when pressing tab key

### ISSUE THREAD

**Issue by manutaitrmn** [primefaces/primeng#13957]
### Describe the bug

When focused on a p-dropdown element with the "options" attribute defined, it is impossible to focus on the next input with the tab key.
However, when "options" attribute is not defined, it works.

### Environment

Running node locally on my computer and use Angular / Primeng. The identified problem is only within PrimeNg/Angular.

### Reproducer

https://stackblitz.com/edit/g27iot?file=src%2Fapp%2Fdemo%2Fdropdown-basic-demo.html

### Angular version

16.2.10

### PrimeNG version

16.5.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.2.10

### Steps to reproduce the behavior

In the stackblitz :
1. Click on the first input text.
2. Press tab key to go to the first p-dropdown (with options attribute not defined)
3. Once focused on p-dropdown, press tab key to go to next input text (it works)
4. Once on input text, press tab key to go to the second p-dropdown (options attribute defined)
5. Once focused on the second p-dropdown, press tab key to go to last input text
6. Blocked, it stays focused on the p-dropdown

### Expected behavior

From the second p-dropdown focused, when pressing tab key, it should focus on the next input text.

**Comment by lslocumwrb** [comment]
I am experiencing the same issue after upgrading to 16.5.0

**Comment by AlexisDefranoux** [comment]
Same on 16.3.1

**Comment by macedo8** [comment]
Same on 17.18.15

**Comment by JesusMurua** [comment]
The problem is that the new components, for some reason, don't take the new attributes. Just need to apply this in global style.scss file

/**

Fix for p-dropdown item highlight on keyboard navigation.
The legacy theme is missing styles for the .p-highlight class,
making keyboard navigation invisible. This rule restores that visibility.
/
.p-dropdown-panel .p-dropdown-items .p-dropdown-item.p-highlight {
background: #e9ecef !important;
color: #495057 !important;
}
/*

Fix for keyboard navigation highlight in list components (Dropdown, MultiSelect, etc.).
PrimeNG v17 uses the data-p-focused="true" attribute for keyboard focus,
which is not styled by legacy themes like Olympia. This rule adds the
necessary visual feedback.
*/
[data-p-focused="true"] {
background: #e9ecef !important;
color: #495057 !important;
}
