### ISSUE TITLE
P-Chips component enter function not working in any Android devices

### ISSUE THREAD

**Issue by leoademi** [primefaces/primeng#13981]
### Describe the bug

Im using the p-chips component from PrimeNG. In the mobile ( Android only ) the enter function does not create the chip in Android , but in IOS works fine. In Android it behaves the enter like the next tab ( next input )

### Environment

Android devices only

### Angular version

Angular 16

### PrimeNG version

 "primeflex": "3.3.1",     "primeicons": "6.0.1",     "primeng": "16.0.2",

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18

### Browser(s)

Android Devices

**Comment by GustavoCostaW** [comment]
![Screenshot_20240210-184616](https://github.com/primefaces/primeng/assets/874909/448530df-c612-4047-aaf0-db42d824fba5)
 

Same here, @SoyDiego I'm using pixel 7, it only happens on Android, even using commas or pressing enter does not work on any demo, testing the same page on chrome desktop works fine.

![Screenshot_20240210-184713](https://github.com/primefaces/primeng/assets/874909/b884b42e-a586-49ff-a667-ff5361da5f0c)

**Comment by SoyDiego** [comment]
> Same here, @SoyDiego I'm using pixel 7, it only happens on Android, even using commas or pressing enter does not work on any demo, testing the same page on chrome desktop works fine.

Thanks for report it. I have checked with my mobile again (when I left my previous comment was 3 months ago) and now yes, I can replicate and see the problem in mobile. PRs are welcome too.
I'm only a contributor here, i'm not working for PrimeNG :)

**Comment by SoyDiego** [comment]
I was trying to fix the problem, but after a lot of investigation and trying many things, I don't know what else I can do. Maybe someone has another idea. **[I found that there was a big discussion about this issue on Android created and closed in the Chromium bugs](https://bugs.chromium.org/p/chromium/issues/detail?id=118639)**. They closed it as **WontFix**.

Also I found this reply in [StackOverflow](https://stackoverflow.com/a/61255937/8818885):
![image](https://github.com/primefaces/primeng/assets/19764334/7e3009fc-5a11-463b-b236-d9216018cb68)

So, will be complicated. I write here all the information because maybe @cetincakiroglu you have some another idea to continue with this issue, but it's not PrimeNG, it's Android problem :(

**Comment by Lukasss93** [comment]
See this:
https://github.com/primefaces/primevue/issues/3694#issuecomment-1944589785

**Comment by mehmetcetin01140** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
