### ISSUE TITLE
Accordion Component

### ISSUE THREAD

**Issue by cagataycivici** [primefaces/primeng#14]
Create accordion panel component.

**Comment by zamrokk** [comment]
I tried to display a LineChart inside an accordion but it does not show anything.
Another component with a map from angular2-google-maps, does the same : not shown.

I will try do do my own angular 2 simple accordion because I do not have time to understand what is not working. Outside of the accordion, I have no problem displaying theses 2 components

**Comment by cagataycivici** [comment]
Could you please post your questions to PrimeNG forum?

http://forum.primefaces.org/viewforum.php?f=35
