### ISSUE TITLE
Accordion: Keydown handler on accordion prevents default behavior of editable elements such as inputs and textareas

### ISSUE THREAD

**Issue by televic-education-ruben** [primefaces/primeng#14038]
### Describe the bug

When I put an input or textarea (or any other editable element) inside an accordion, the keydown event of the input is propagated up and the handler of the accordion changes the accordion focus and prevents the default behavior of the input/textarea/...
https://github.com/primefaces/primeng/blob/master/src/app/components/accordion/accordion.ts#L441
Maybe check the target of the event and not do this when it's an editable component so that the default editing behavior is not broken?
This is probably also the cause of this issue: https://github.com/primefaces/primeng/issues/13488

### Environment

Normal environment

### Angular version

16

### PrimeNG version

16

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18

**Comment by snjak** [comment]
This issue still exists. Angular - 18.3.10, PrimeNG - 17.18.0

**Comment by colfin-96** [comment]
We are also facing this issue with the Quill editor. We are not using p-editor due to other reasons, so I'm not sure if it works with that. We are using [ngx-quill](https://github.com/KillerCodeMonkey/ngx-quill), however, this issue doesn't seem to be limited to just that editor. If I can provide any more information, please let me know.

**Comment by gianluca-moro** [comment]
It's still an issue in PrimeNG 21, lmao
