### ISSUE TITLE
Setting minimum on slider allows sliding beyond slider

### ISSUE THREAD

**Issue by rolandoldengarm** [primefaces/primeng#1436]
**I'm submitting a ...**  (check one with "x")
```
[X ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
Setting the minimum for the slider allows the slider to go outside the slider box:

![image](https://cloud.githubusercontent.com/assets/14539000/20646761/be72a4f6-b4e6-11e6-984c-b9f080cecf30.png)

**Expected behavior**
The slider should not go outside the slider box.

**Minimal reproduction of the problem with instructions**
<p-slider [(ngModel)]="searchRadius"  [min]="10" [max]="80"></p-slider>

**Comment by Mrtcndkn** [comment]
What is your primeng version it's working fine locally

**Comment by rolandoldengarm** [comment]
@Mrtcndkn I'm so sorry, I was still on RC.3...
Updated to latest version, fixed!

**Comment by Mrtcndkn** [comment]
I'm glad it works =)

**Comment by msfanous** [comment]
I'm running 2.0.1 and I'm seeing this issue.  If I set the min value to 1, I can slide past the end of the slider.

**Comment by msfanous** [comment]
@Mrtcndkn I was able to resolve my issue with this syntax.

`<p-slider [min]="1" [max]="6"></p-slider>`

The issue seems to manifest itself only if you remove the square brackets.  I could be wrong, but isn't that valid syntax when you are passing in the value directly and not binding to a variable?

`<p-slider min="1" max="6"></p-slider>`

I only have the problem with the min property.  I can set max with or without the square brackets without any issues.
