### ISSUE TITLE
Component: PanelMenu repeated rendering

### ISSUE THREAD

**Issue by Silvora** [primefaces/primeng#14373]
### Describe the bug

When rendering the PanelMenu component, repeatedly render a PanelMenu data

### Environment

![MG162](https://github.com/primefaces/primeng/assets/57209830/4ce90d50-e04c-4e68-9b32-8f862e7ac8cb)

### Angular version

v17

### PrimeNG version

v17.1.0

### Build / Runtime

TypeScript

### Language

TypeScript

### Node version (for AoT issues node --version)

v20.9.0

### Steps to reproduce the behavior

![MG163](https://github.com/primefaces/primeng/assets/57209830/1e4b6ec7-64ef-4e39-aca1-079dcbe544e1)
![MG164](https://github.com/primefaces/primeng/assets/57209830/ec951c1f-8357-45e5-98bc-635364c89870)

### Expected behavior

![MG165](https://github.com/primefaces/primeng/assets/57209830/e18914f0-a925-4c06-bf1b-7ca9f158a704)

**Comment by DanielGabbay** [comment]
+1 
I have the same issue from version 17.0.0

**Comment by VianneyAccart** [comment]
Hello, I have the same problem with version 17.1.0. I had no problem with 16.0.2 version.

- With prime 16.0.2, only white menu was displayed, which is the expected behavior. 

![image](https://github.com/primefaces/primeng/assets/67595652/b4f39bd5-51fb-4366-a9ca-92bfcac2638f)

- Since prime 17.1.0, there's a duplication. White menu is only displayed when I click on blue "Administration" link as it was a child.

![panelMenu_repeated_bug](https://github.com/primefaces/primeng/assets/67595652/6aca5e72-69a5-4a9e-b13f-ab574502e03a)

My object didn't change from 16.0.2 to 17.1.0 : 

![panelMenu_object](https://github.com/primefaces/primeng/assets/67595652/e5c9116f-b41a-4b91-8d6d-ed34d427a19d)

Thanks for your help

**Comment by cetincakiroglu** [comment]
Hi,

Thanks a lot for reporting the issue, we'll address it in the upcoming release (17.1.1) tomorrow.

**Comment by jalley3** [comment]
Can we reopen this (or should I create a new bug?). This was working as normal in 17.16 but in 17.17 and 17.18 this seems to be broken again. 
Now (17.17 and 17.18): 
![image](https://github.com/primefaces/primeng/assets/17911817/c4fa284d-795f-4460-a892-cb2e7de05cc5)

Expected (17.16):
![image](https://github.com/primefaces/primeng/assets/17911817/556ea79f-2304-4848-a31f-0f1e0f7ba29c)

**Comment by M-Faham** [comment]
Same here 17.18
![image](https://github.com/user-attachments/assets/4d067879-2a0e-466e-b4c3-121c0ab7fc25)

**Comment by SippieCup** [comment]
Reproduction:
https://stackblitz.com/~/github.com/SippieCup/panelMenu-duplication
