### ISSUE TITLE
Impossible to asign component styles to automatically generated elements.

### ISSUE THREAD

**Issue by vazham** [primefaces/primeng#1447]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**

Conmonent-specific styles now are not assignable to elements generated by PrimeNG(any elements). This bug aapears because all component elements generated by Angular 2 have unique html attribute that doesn't appears on PrimeNG generated elements.

**Expected behavior**

Without bug all generated elements should have unique html attribute generated by Angular 2.

**Minimal reproduction of the problem with instructions**

Use calendar in any component. Add some component styles to calendar. Calendar will not be affected by that styles.

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

Any

* **Angular version:** 2.0.X

2.2.3

* **PrimeNG version:** 2.0.X

1.0.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Chrome 54(but should be in all browsers).
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript 2.0.10

* **Node (for AoT issues):** `node --version` =   
6.9.1

**Comment by cagataycivici** [comment]
Create a plunkr please, it is not clear.

http://plnkr.co/edit/NtWWnN

**Comment by mischkl** [comment]
@vadimzham I think this might be a case where you need to set `encapsulation: ViewEncapsulation.None` in your component decorator. Try that and see if it works for your use case. It admittedly prevents you from  encapsulating any other styling in that component, but you can work around that by either adding your component's element to the beginning of all your selectors, create an extra wrapper component for this purpose, or you could add the custom styling to a global stylesheet.

Note that this is an "issue" with all Angular components, not just PrimeNG, since by default they all have Shadow DOM emulation (ViewEncapsulation.Emulated) turned on.

**Comment by vadimzham** [comment]
@cagataycivici i'v tried to represent it on plunkr [(here)](http://plnkr.co/edit/HhX5sSDwmcUHe6LeJ26H?p=preview) but it doen't work(idk why, i hate plunkr for that).
I added it to my repo [(here)](https://github.com/vadimzham/primeng-bug) where it have minimal representation that works.

**Comment by vadimzham** [comment]
@mischkl It's terrible solution. Whole idea for dedicated component styling will be killed by this solution.

**Comment by mjsgreen01** [comment]
use the `:host` `/deep/` selectors to style elements generated by primeng

**Comment by cagataycivici** [comment]
I think this is Angular architecture related, not PrimeNG.
