### ISSUE TITLE
P-messages push method is not working for multiple messages

### ISSUE THREAD

**Issue by deekshacse1999** [primefaces/primeng#14507]
Multiple messages was working in primeng 8 version but after migrating it to primeng v13, push method is not working to display multiple messages 
We have Message[] everywhere in the application. But its not working post primeng v8

**Comment by Cr3aHal0** [comment]
Could you provide a sample code or reproduction stackblitz about the current way you're using messages please ? Are you using MessageService or straight p-messages with input ?

**Comment by deekshacse1999** [comment]
Hi 
I am using p-messages directly with Value property for binding. Pls find below sample code. 

Sample Code:
App.component.html
<p-messages [(value)]="msgs"></p-messages>

<button type="button" (click)="show()">Show</button>
<button type="button" (click)="clear()">Hide</button>

App.component.ts
 import {Component, OnInit} from '@angular/core';
    import {Message,MessageService} from 'primeng/api';
    
    @Component({
        templateUrl: './messagesdemo.html',
        providers: [MessageService]
    })
    export class [Messages](https://www.primefaces.org/primeng-v13-lts/#/messages)Demo implements OnInit {
    
        msgs1: Message[] = [];
        
        constructor() {}

        ngOnInit() {
            
        }
        
show() {
    this.msgs.push({severity:'info', summary:'Info Message', detail:'PrimeNG rocks'});
}

hide() {
    this.msgs = [];
}

    }

**Comment by Cr3aHal0** [comment]
Because of p-messages being onPush & the `value` input not being used verbatim by the component (e.g. in a `*ngFor`) but being proxied by a setter, you may need to update `msgs` reference by submitting a new array of message rather than using `Array.push`. I'm pretty sure this was specified someday within the official documentation but I could not find it in a 5 minutes window.

A better approach (generally when working with onPush sub components) would be :

```
show() {
  this.msgs = [...this.msgs, {severity:'info', summary:'Info Message', detail:'PrimeNG rocks'}];
}

hide() {
  this.msgs = [];
}
```

**Comment by mertsincan** [comment]
Thanks @Cr3aHal0 ;)
