### ISSUE TITLE
GalleriaThumbnail afterViewInit use platformBrowser instead of isPlatformBrowser

### ISSUE THREAD

**Issue by LudoGilloTools** [primefaces/primeng#14534]
### Describe the bug

When creating a p-galleria component, I have the following error :

**ERROR Error: NG0400: A platform with a different configuration has been created. Please destroy it first.**

This came from the AfterViewInit of GalleriaThumbnail component where this is done :   

`if (platformBrowser(this.platformId))`

Our angular app is launched with platformBrowserDynamic.

### Environment

angular 17 app launching with platformBrowserDynamic

### Angular version

17.0.10

### PrimeNG version

17.3.2

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.10.0

**Comment by cetincakiroglu** [comment]
Hi,

Thanks a lot for reporting the issue, good catch!

**Comment by nazem0** [comment]
Yes! same bug here but I noticed it only happens if **[showThumbnails]="true"**, so without thumbnails everything is just fine..

`
<p-galleria [value]="product.pictures" [showIndicators]="true" [showThumbnails]="false" [showIndicatorsOnItem]="true" indicatorsPosition="left" [containerStyle]="{ 'max-width': '100%','margin-top': '2em' }">
                <ng-template pTemplate="item" let-item>
                    <img [src]="item" style="width: 100%; display: block;" />
                </ng-template>
                <ng-template pTemplate="indicator" let-index>
                    <span style="color: #e9ecef; cursor: pointer">
                        {{index + 1}}
                    </span>
                </ng-template>
            </p-galleria>
`
