### ISSUE TITLE
p-cascadeSelect options: not change after new data in array of options

### ISSUE THREAD

**Issue by AlexKuturkin** [primefaces/primeng#14698]
### Describe the bug

Hello everyone!

Earlier p-cascadeSelect options change after data was changed.
Also changed html, so in dropdown were new values.
This behavior was work in version  "primeng": "15.4.15-lts",
example in stackblitz

Now, in version  "primeng": "~17.3.2", this not working, unfortunately.
Any suggestions?

Thank you

### Environment

angular app 

### Reproducer

https://stackblitz.com/edit/1pszed?file=src%2Fapp%2Fdemo%2Fcascade-select-basic-demo.html,package.json

### Angular version

17.0.9

### PrimeNG version

17.3.2

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.10.0

### Browser(s)

Chrome 121.0.6167.86

**Comment by fridolin-koch** [comment]
Having the same issue after upgrading from 16.x to `17.9.0`

I'm not yet sure I totally the whole signals concept, but as far as I understand it:

https://github.com/primefaces/primeng/blob/5dae6e5757e7af4c5550756cbd092ab8a092dbc3/src/app/components/cascadeselect/cascadeselect.ts#L685-L687

Will only be called once. `this.options` needs to be a signal as well, otherwise it is never updated

Ref: https://angular.io/guide/signals#computed-signals

As a workaround I just re-render the cascade select after changing the options

**Comment by AlexKuturkin** [comment]
> As a workaround I just re-render the cascade select after changing the option

Hello!
Can you show how you did this, please.

**Comment by fridolin-koch** [comment]
Just use `ngIf` to toggle the element when you change the data 

e.g. https://stackblitz.com/edit/clx9ov-7xf8sh

**Comment by cetincakiroglu** [comment]
Hi,

I've just clicked the button and options are updated https://stackblitz.com/edit/1pszed-tuskv8?file=src%2Fapp%2Fdemo%2Fcascade-select-basic-demo.html,src%2Fapp%2Fdemo%2Fcascade-select-basic-demo.ts

Could you please tell us how to reproduce the issue?

**Comment by fridolin-koch** [comment]
> Hi,
> 
> I've just clicked the button and options are updated https://stackblitz.com/edit/1pszed-tuskv8?file=src%2Fapp%2Fdemo%2Fcascade-select-basic-demo.html,src%2Fapp%2Fdemo%2Fcascade-select-basic-demo.ts
> 
> Could you please tell us how to reproduce the issue?

@cetincakiroglu The code you linked uses `15.4.15-lts` which works fine. It also worked fine in `16.0.2`

Here you can find the bug reproduction with `17.9.0` https://stackblitz.com/edit/clx9ov

The bug can also reproduced with `17.11.0` https://stackblitz.com/edit/clx9ov-rqfmhu
