### ISSUE TITLE
DataTable Single Mode Selection doesn't unselect - 1.0.0

### ISSUE THREAD

**Issue by praveens4all** [primefaces/primeng#1470]
Still Datatable unselect not firing.

**Comment by praveens4all** [comment]
tried with 1.0.0 release also..same issue.

**Comment by dzhavat** [comment]
The unselect happens only when you hold Ctrl + click on the row (on desktop). On mobile works just by taping. This was implemented in one of the RCs.

**Comment by praveens4all** [comment]
Thanks for reply. 
But user not aware of Ctrl key. can you please advise how can i fix with out holding Ctrl key.

**Comment by Mrtcndkn** [comment]
It's by design and a known use of selection of a table you can change it from source but it's not recommended.

**Comment by dzhavat** [comment]
It actually mimics the way Windows works. Try selecting an item and unselecting it :)
Anyway, on a web app it can be intuitive. One way is to make the selection with [a radio button](http://www.primefaces.org/primeng/#/datatable/selection) instead of clicking on the whole row.

Another way is to just rely on the mouse cursor being changed to a hand for indicating clicking.
