### ISSUE TITLE
Tooltip: disable autoHide doesn't with positionLeft property

### ISSUE THREAD

**Issue by AMZALE** [primefaces/primeng#14714]
### Describe the bug

Tooltip: disable autoHide doesn't work with positionLeft property
https://stackblitz.com/edit/wszuks?file=src%2Fapp%2Fdemo%2Ftooltip-auto-hide-demo.html

### Environment

Angular project

### Reproducer

https://stackblitz.com/edit/wszuks?file=src%2Fapp%2Fdemo%2Ftooltip-auto-hide-demo.html

### Angular version

16

### PrimeNG version

16.9.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.18

### Browser(s)

Chrome

**Comment by Cr3aHal0** [comment]
Hi,

A word from PrimeNG here is necessary as autoHide:false only prevent tooltip deactivation when the cursor immediately leave the bound field or element to the tooltip container (since by default the arrow/tooltip is stuck to the bound element). Is it okay for this feature to still work even if there is a 100px gap between the two ?

**Comment by mehmetcetin01140** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
