### ISSUE TITLE
Dropdown: selected option is not displaying correctly.

### ISSUE THREAD

**Issue by vaibhavsingh-09** [primefaces/primeng#14734]
### Describe the bug

On selecting value for the first time, the selected value is not displayed on UI. In subsequent selections, previously selected value is being displayed. My component is using **OnPush** change detection strategy and listing to **onChange** emitter from p-dropdown to invoke callback when value of dropdown changes. Inside my callback i am calling **markForCheck() and detectChanges()**.

This code was working as expected till version primeng 17.3.2.

I have created a similar stackblitz example as a reproducer.

### Environment

Mac OS 13.6.4

### Reproducer

https://stackblitz.com/edit/ifkxeb?file=src%2Fapp%2Fdemo%2Fdropdown-basic-demo.html

### Angular version

17.1.2

### PrimeNG version

17.5.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.11.0

### Browser(s)

Chrome Version 121.0.6167.139

**Comment by rosenthalj** [comment]
To get your  reproducer to work change:

```
oncahnge(){
    this.cdr.markForCheck();
    
     this.cdr.detectChanges()
}
```

To:

```
oncahnge(){
    setTimeout(()=>{
        this.cdr.markForCheck();
    
        this.cdr.detectChanges()
    },0);
}
```

Note:  Your callback  is consistently misspelled in your reproducer.

**Comment by Cr3aHal0** [comment]
Hi [vaibhavsingh-09](https://github.com/vaibhavsingh-09),

I don't get the need of using such a mechanism for something that is already done on PrimeNG side, could you tell us why you're trying to do with markForCheck() & detectChanges ? FYI, markForCheck() is the way to go with OnPush components and is only required when bound data outside of events and inputs has changed. Since this mechanism on dropdown value change is already triggered by primeNG, your onChange callback is useless there.

**Comment by vaibhavsingh-09** [comment]
Hi @Cr3aHal0 ,

The reproducer that i have given is just an example of my actual use case. The reason for using **detectChanges()**  in my project is that we have a reusable form component which is acting a wrapper over primeng components like input, dropdown, autocomplete etc. 
So in our component we have certain data which needs to be updated onchange of primeng component for example i am creating a dynamic form field on certain condition. And this component is being hosted as private npm repo and used by many teams.

And this behaviour was working till version primeng 17.3.2. And we have this wrapper in place since 3-4 years.

**Comment by rosenthalj** [comment]
An alternative solution (that has not been tested)  to fix this issue would be to modify PrimeNG's dropwdown.ts.   

throughout the  file replace

`this.onChange.emit(...)`

with

```
setTimeout(()=>{
       this.onChange.emit(...))
},0);
```

Note:   there are 3 instances of  the call to emit and 1 (corresponding  to editable) actual is inside a setTimeout.

**Comment by MaciejSzczurek** [comment]
This error occurs for many developers, myself included. It is related to the programmatic setting of the form value, which destroys the user interface. A simple example edit shows what this error looks like. A quick workaround for this problem is to reset this value u set it again with some delay, but this is a very ugly solution.

https://stackblitz.com/edit/xbdmk9?file=src%2Fapp%2Fdemo%2Fdropdown-reactive-forms-demo.ts

**Comment by jacqueslareau** [comment]
Might be a related to https://github.com/primefaces/primeng/issues/14734

**Comment by reidecarvalho** [comment]
I need same problema with optionValue.

[options]="(gruposServico$ | async)!"

gruposServicos$ is an object with this structure: {id: number, nome: string}

Dropdown config:
optionLabel="nome"
optionValue="id"
dataKey="id"
formControlName="idGrupoServico"

I dont want the whole object as values, but just the id, and that's ok, it's works.

However, when I am editing the form and loading with values, using "setValue" method from form your value is loaded but not update the component on screen (if I to print the form, "idGrupoServico" is equal to value passed in the "setValue", but on the screen is not reflected, stay no selected)
