### ISSUE TITLE
dropdown: selected, disabled option not rendered when using selectedItem template

### ISSUE THREAD

**Issue by capc0** [primefaces/primeng#14809]
### Describe the bug

Same as https://github.com/primefaces/primeng/issues/14716 but only when using a template to render the dropdown differently:

```html
<ng-template let-item pTemplate="selectedItem">
    {{ item }}
  </ng-template>
```

### Environment

see below

### Reproducer

https://stackblitz.com/edit/github-npixcr-zf149n?file=src%2Fapp%2Fapp.component.html

### Angular version

17.1.2

### PrimeNG version

17.7.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18

### Steps to reproduce the behavior

open the stackblitz (see above)

<img width="1016" alt="image" src="https://github.com/primefaces/primeng/assets/27284008/a842b679-5ab3-4aad-b0b8-6b2660bb82e9">

### Expected behavior

The selected item should be rendered

**Comment by rosenthalj** [comment]
This issue is the result of the PrimeNG's [dropdown.ts](https://github.com/primefaces/primeng/blob/master/src/app/components/dropdown/dropdown.ts) passes selectedOption to the "selectedItem" template, but disabled options are currently not allowed to be the selectedOption.

See the annotated screenshot of your reproducer listed below:

![Primefaces_-_Primeng_Issue_Template__forked__-_StackBlitz_and_dropdown__selected__disabled_option_not_rendered_when_using_selectedItem_template_·_Issue__14809_·_primefaces_primeng](https://github.com/primefaces/primeng/assets/45439491/79ff1ce2-09b2-446c-a69f-e110e8ae93c2)

If PrimeNG is changed to allow the selectedOption to be set to a disabled option,  the following is an untested fix to  [dropdown.ts](https://github.com/primefaces/primeng/blob/master/src/app/components/dropdown/dropdown.ts):


![primeng_src_app_components_dropdown_dropdown_ts_at_master_·_primefaces_primeng](https://github.com/primefaces/primeng/assets/45439491/1d016f39-fd31-442b-937c-69bab9787181)

**Comment by thetric** [comment]
This was working in 17.4.0 but broke in 17.5.0 due to the refactoring introduced in https://github.com/primefaces/primeng/pull/13991
