### ISSUE TITLE
Dropdown: Dropdown no longer closes when clicking the currently selected option

### ISSUE THREAD

**Issue by Airdevelopments** [primefaces/primeng#14873]
### Describe the bug

The closed issue #14811 is still present in version 17.8.0

### Environment

see below

### Reproducer

https://stackblitz.com/edit/github-fz8npg-qsccos?file=src%2Fapp%2Fapp.component.ts

### Angular version

17.1.0

### PrimeNG version

17.8.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.16.0

### Browser(s)

Chrome 120

### Expected behavior

When clicking the already selected option in the dropdown, the dropdown should just be dismissed / closed.

**Comment by capc0** [comment]
The original PR (https://github.com/primefaces/primeng/pull/14812) has been merged, but the changes are not present in the code base anymore. Propably because of commit https://github.com/primefaces/primeng/commit/92e3310d44658d0765f099733c048b42202aedb5

Merging the PR https://github.com/primefaces/primeng/pull/14812 again would fix this issue.

**Comment by rosenthalj** [comment]
I had identified the cause for this issue during the integration of v17.8.0 in the comment I added to https://github.com/primefaces/primeng/commit/24ea912ca58a83bb8ee469490c75b0b588c9bf1f
