### ISSUE TITLE
p-dropdown: Focus doesn't came out of dropdown field after tabbing

### ISSUE THREAD

**Issue by akashuwtw** [primefaces/primeng#14924]
### Describe the bug

While tabbing through all the fields in the form, keyboard focus doesn't came out of the `p-dropdown` field.

### Environment

OS: Windows 10

### Angular version

16.2.7

### PrimeNG version

16.5.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.16.0

### Browser(s)

Chrome 121.0.6167.161, Edge 121.0.2277.112

### Steps to reproduce the behavior

`<p-dropdown [options]="dropdownOptions" [ngModel]="selectedOption" optionLabel="name"></p-dropdown>`

### Expected behavior

On tab key, focus should move to next field

**Comment by cetincakiroglu** [comment]
Hi,

We can't replicate the behavior in the latest version of PrimeNG. This issue is fixed between 16.5x and 17x versions. Please try latest version you'll see that the next element receives focus by pressing tab if the overlay is closed. See the example: https://stackblitz.com/edit/rswtum?file=src%2Fapp%2Fdemo%2Fdropdown-basic-demo.html

Closing the issue since it doesn't exist with the latest version.
