### ISSUE TITLE
Component: Card

### ISSUE THREAD

**Issue by BenoitPE** [primefaces/primeng#15013]
### Describe the bug

Given a card with style like so:
```html
<p-card [style]="cardStyle">
</p-card>
```

When updating style:
```ts
  cardStyle = { background: 'lightblue' };

  ngAfterViewInit(): void {
      this.cardStyle = { background: 'red' };
  }
```

Style is not updating on the card

### Environment

Using Angular 17 and PrimeNG in 17.10.0 version.

### Angular version

17.2.2

### PrimeNG version

17.10.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

21.4.0

### Browser(s)

Chrome

**Comment by RemiPeruto** [comment]
Hello @BenoitPE 
I investigated a bit and I found that in the card component you are not allowed to do such modifications because of the Change detection strategy is set to onPush. https://angular.io/api/core/ChangeDetectionStrategy

I propose a modification to allow the Default Change Detection Strategy but it is a breaking change in the card component.
