### ISSUE TITLE
Treetable column resize misalign header and body when columnResizeMode="expand" in combination with [virtualScroll]="true"

### ISSUE THREAD

**Issue by scheelu** [primefaces/primeng#15059]
### Describe the bug

The bug appeard in v14, and is still reproducible in v16 and v17
When you use a p-treetable with columnResizeMode="expand" and [virtualScroll]="true"
And you resize a column, there is a missmatch bewteen width of the header and the body.

There is a second thing, still with  columnResizeMode="expand" and [virtualScroll]="true"
The column resize do not work at all if you don't put a colgroup. I don't know if this is intended or not.

### Environment

see below

### Reproducer

https://stackblitz.com/edit/github-dtgjk2?file=src%2Fapp%2Fapp.component.html,src%2Fapp%2Fservice%2Fnodeservice.ts,src%2Fapp%2Fapp.component.ts

### Angular version

17.3.0

### PrimeNG version

17.11.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.8.0

### Steps to reproduce the behavior

1. Resize the last column (Type in the exemple)
2. The column header is misaligned with the body

### Expected behavior

The column header is aligned with the body

**Comment by scheelu** [comment]
![2024-03-15 09_51_56-Window](https://github.com/primefaces/primeng/assets/79078984/c3733345-8aca-4fd3-bd03-0be6b7f1dfef)

**Comment by MonishSannathi** [comment]
Hello @scheelu ,

I had almost similar issue that you mentioned. It looks like only in Chrome and Edge, padding-right is being added for class "p-treetable-scrollable-header-box". In Firefox, this issue is not there since padding-right is set as 0px. So Overriding that padding-right to 0px, will fix the issue  I think.

<img width="1235" alt="Primeng" src="https://github.com/primefaces/primeng/assets/39125844/f0291f23-94a9-49e3-8313-8d79f40e978a">
<img width="479" alt="chrome" src="https://github.com/primefaces/primeng/assets/39125844/c1bb7050-80c2-4452-a49c-13af106cbf93">

**Comment by mehmetcetin01140** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
