### ISSUE TITLE
Menubar: menuicon and submenuicon templates not working

### ISSUE THREAD

**Issue by giovannijunior** [primefaces/primeng#15068]
### Describe the bug

`Menuicon` and `submenuicon` [templates](https://primeng.org/menubar#api.menubar.templates) of the Menubar component are not working as expected, likely because of `ng-template` being used instead of `ng-container` in https://github.com/primefaces/primeng/commit/d1930e51c6a50d1fe136159f73000d8acb049457

### Environment

Not relevant

### Reproducer

https://stackblitz.com/edit/github-pur4jg?file=src%2Fapp%2Fapp.component.html

### Angular version

17.1.1

### PrimeNG version

17.4.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.11.0

### Steps to reproduce the behavior

1. Create a menu bar
2. Configure a template named `menuicon`, to set the item icons
3. The template is ignored

### Expected behavior

The icon of each menu item should be set as specified in the template

**Comment by cetincakiroglu** [comment]
Hi,

`menuicon` template does not set the icons of items. It changes the default `<BarsIcon />` which used to toggle menu in mobile view, and I see that it works in your example. To customize the item icons, you can use `item` template https://primeng.org/menubar#template

`submenuicon` template allows users to change arrow-down icon of a menuitem that has a submenu. Please see the difference: https://stackblitz.com/edit/dxg6fl?file=src%2Fapp%2Fmenubar-basic-demo.html

PS: Menubar has different representation in mobile and desktop.

Closing the issue since it doesn't related to ng-template or ng-container.
