### ISSUE TITLE
Menubar: The bug where the menuitems don't close when clicking outside the menuitem in mobile mode.

### ISSUE THREAD

**Issue by okjinweigelt** [primefaces/primeng#15240]
### Describe the bug

For example, look at the primeng documentation, https://primeng.org/menubar#basic menubar basic:

![image](https://github.com/primefaces/primeng/assets/149393804/bd3ad333-b408-41f9-aeaf-4a9916fd8c7d)

In mobile mode (just shrinking the screen), when  menuitems are opened, clicking outside the menuitems does not close the menuitems until you click the icon.  
![image](https://github.com/primefaces/primeng/assets/149393804/afa23b12-b5d5-4425-98d0-8f461caf7916)
This bug was not present until version 15, but it appeared starting from version 16.

### Environment

window

### Angular version

17.1.3

### PrimeNG version

17.12.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.16.1

### Browser(s)

All

### Steps to reproduce the behavior

1. shrink the screen so that only the icon of the menu bar is displayed.
2. click the icon to expand the menuitems.
3. click outside the menuitems in this state.

### Expected behavior

When clicking outside the menuitem, the menuitem should close.

**Comment by mehmetcetin01140** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,

**Comment by klerick** [comment]
@mehmetcetin01140
 This bug is still present in v21.1.1.                                                                                     
                                                                                                                            
  PR #15636 had the correct fix but was closed without merging. The buggy code is still there:                              
   
  // Current (buggy):                                                                                                       
  if (isOutsideContainer) {                                                                                               
      isOutsideMenuButton ? (this.mobileActive = false) : this.hide();
  }

  // Should be (from PR #15636):
  if (isOutsideContainer && isOutsideMenuButton) {
      this.hide();
  }

  Can this fix be revisited?
