### ISSUE TITLE
p-dropdown does not let you type single letter to select options that begin with that letter

### ISSUE THREAD

**Issue by emorin** [primefaces/primeng#15279]
### Describe the bug

In version 15.x, you could expand a dropdown and type a single character and the dropdown would cycle through the options that begin with that letter.  

For example, 
Rome
Rodeo

If you type r, it should select Rome.  Then if you type r again it should jump to the next element which would be Rodeo.  

It stopped working like that in version 16.x and now in 17.x.  This is common for dropdowns to work like this.  You should be able to keep typing the letter and the dropdown will cycle through the options that start with that letter.

### Environment

N/A

### Angular version

17.3.1

### PrimeNG version

17.13.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

n/a

### Browser(s)

Chrome and Edge

### Expected behavior

Type a single character and have the dropdown cycle through the options that begin with that letter.

**Comment by emorin** [comment]
Anything for this?  Our users really miss this feature.

**Comment by av-code-crafter** [comment]
@mertsincan  This issue is still not resolved in version 17.18.15. Typing the first character does not cycle through all matching options which starts with that character. It just stays on the first item. This was a really good feature in older version which users are used to use a lot. Is there any chance that this feature is going to be back?
