### ISSUE TITLE
Menubar, MegaMenu: Submenu doesn't open on mouseover, when using touchscreen notebook with mouse

### ISSUE THREAD

**Issue by can-oezkan** [primefaces/primeng#15570]
### Describe the bug

When using a touchscreen notebook, the submenu's dont show on mouseover. You have to click the menu first.

I assume that this bug got introduced by this PR: #13447 

The underlying issue seems to be this method, that gets called to determine if a mouseover should show the submenu or not:

https://github.com/primefaces/primeng/blob/21b49bce19a7677162c788294a743efc61ceee82/src/app/components/dom/domhandler.ts#L485-L487

### Environment

angular business application

### Angular version

17.3.7

### PrimeNG version

17.16.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

v20.12.2

### Steps to reproduce the behavior

1. Use a notebook with touchscreen
2. use the touchpad or external mouse to hover over menu

### Expected behavior

The submenu should show on mouseover when using a touchpad or external mouse.

**Comment by DerekBolger** [comment]
Same Issue here tested using multiple variants of Microsoft Sufrace with external mouse and touchscreen enabled and on Microsoft Surfacebook Laptops 3&4

### Describe the bug
In past version of PrimeNG, submenus in **Menubar Component** were shown immediately when hovering over an item using a touch enabled device.

![touchscreen enabled](https://github.com/user-attachments/assets/4a13dc37-4b3a-4fda-9f5e-7c493df7d5fa)

### Environment
N/A

### Reproducer
See below

### Angular version
17.3.11

### PrimeNG version
17.18.11

### Build / Runtime
Angular CLI App

### Language
TypeScript

### Node version
18.18.2

### Browser(s)
Chrome, Edge & Firefox

### Steps to reproduce the behavior
Use PrimeNG's showcase for the Menubar: [](https://primeng.org/menubar) utilising a touchscreen enabled device.

### Behaviour
Hover over the Projects menu item and note that it's submenus do not show on hover on a device with touchscreen enable, either using external mouse on Surfacebook or built in mouspad on Surface Laptop.

### Expected behavior
Submenus should immediately appear when hovering over an item with Submenus.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation and try the latest PrimeNG version(v19). If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
