### ISSUE TITLE
Component: p-inputNumber [min] property NaN

### ISSUE THREAD

**Issue by danielvieira1** [primefaces/primeng#15659]
### Describe the bug

When I specify [min]=null in the p-inputNumber component, this happens:
![image](https://github.com/primefaces/primeng/assets/130975026/88a11176-dda2-4380-b137-42a86a7444bc)

NaN is set instead of null. I can not enter negative values anymore unless I use the arrow keys.

### Environment

I am using regular Angular with PrimeNG

### Angular version

17.3.5

### PrimeNG version

17.15.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.18.2

### Browser(s)

Chrome

### Steps to reproduce the behavior

<p-inputNumber
  mode="currency"
  locale="de-DE"
  [min]="null"
  currency="EUR"
  [ngModel]="null"
>

Now try to add a negative value without using the step buttons or arrow keys

### Expected behavior

if null is specified in the "min" property, you should be able to add negative values.

**Comment by danielvieira1** [comment]
Yes, if you don't define it, its fine. It happened for me because I wrapped the primeNG component and default value that is parsed into the primeNG component is null.

**Comment by quentin-ineat-ca** [comment]
Same problem here.

If min is defined as : null | undefined => impossible to go below 0.
if min is not defined => Works fine

Here is the stackblitz : https://stackblitz.com/edit/j7uken?file=src%2Fapp%2Finput-number-numerals-demo.html
Last version Primeng 17.18.3

**Comment by quentin-ineat-ca** [comment]
@RogueTea Same problem here.

If min is defined as : null | undefined => impossible to go below 0.
if min is not defined => Works fine

Here is the stackblitz : https://stackblitz.com/edit/j7uken?file=src%2Fapp%2Finput-number-numerals-demo.html
Last version Primeng 17.18.3

**Comment by salimmenari** [comment]
> If min is defined as : null | undefined => impossible to go below 0. if min is not defined => Works fine

Same situation here with PrimeNG 17.18.11. 

It was working fine with PrimeNG 16.9.15 as we can see here : https://stackblitz.com/edit/vrfmbo

**Comment by Werffios** [comment]
<hr></hr> 
Hi, I am experiencing the same issue with the _p-inputNumber_ component in PrimeNG. When I specify [min]=null, I cannot enter negative values, even if I use the arrow keys. Removing the min attribute or setting it to null does not resolve the issue. Here is the relevant code snippet:

`<div>
  <label for="maxStatic">Estática Max</label>
  <p-inputNumber id="maxStatic" ngDefaultControl formControlName="maxStatic" placeholder="-40 - 40"
                 [min]="-40" [max]="40"
                 mode="decimal" [minFractionDigits]="1" [maxFractionDigits]="2" suffix=" kV"/>
</div>`

**Environment:**  

- Angular CLI: 18.2.11
- Angular version: 18.2.11
- PrimeNG version: 17.18.11
- Node version: 23.4.0 (Unsupported)
- Package Manager: npm 10.9.2
- OS: win32 x64
- Browser: Microsoft Edge Version 131.0.2903.99 (Official build) (64-bit)

**Steps to reproduce:**  
Use the p-inputNumber component with [min]=-40.
Try to enter a negative value, even using the arrow keys.
Expected behavior: If null is specified in the min property, it should be possible to add negative values.  
<hr></hr> 

This should provide enough detail for others to understand and potentially reproduce the issue.

**Comment by Werffios** [comment]
<hr></hr> 
Hi, I am experiencing the same issue with the _p-inputNumber_ component in PrimeNG. When I specify [min]=null, I cannot enter negative values, even if I use the arrow keys. Removing the min attribute or setting it to null does not resolve the issue. Here is the relevant code snippet:

![image](https://github.com/user-attachments/assets/335a0248-b38c-455f-8200-d858c3a9cdfd)


**Environment:**  

- Angular CLI: 18.2.11
- Angular version: 18.2.11
- PrimeNG version: 17.18.11
- Node version: 23.4.0 (Unsupported)
- Package Manager: npm 10.9.2
- OS: win32 x64
- Browser: Microsoft Edge Version 131.0.2903.99 (Official build) (64-bit)

**Steps to reproduce:**  
Use the p-inputNumber component with [min]=-40.
Try to enter a negative value, even using the arrow keys.
Expected behavior: If -40 is specified in the min property, it should be possible to add negative values.  
<hr></hr> 

This should provide enough detail for others to understand and potentially reproduce the issue.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation and try the latest PrimeNG version(v19). If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,

**Comment by shlomiah** [comment]
The issue is still not resolved
As mentioned before: @quentin-ineat-ca 
If min is defined as : null | undefined => impossible to add "-" before the number
if min is not defined => Works fine

**Comment by figlerdavid** [comment]
I don’t fully agree with the situation. If you wrap the component and reuse it, and you can’t define in advance whether the min/max fields will have a value, then the solution should be undefined. Not null, but undefined. This still worked in PrimeNG 16.

**Comment by vladdy-dotcom** [comment]
How is this still active, seems like a major issue ?

**Comment by danielvieira1** [comment]
Ok i just created a new issue. hopefully it wont be closed this time!
https://github.com/primefaces/primeng/issues/18429
