### ISSUE TITLE
Support for Angular 18

### ISSUE THREAD

**Issue by swami-sanapathi** [primefaces/primeng#15661]
### Describe the bug

Angular 18 has been released, please consider adding support for it.

- https://github.com/angular/angular/releases
- eslint support PR is in WIP: https://github.com/angular-eslint/angular-eslint/pull/1830

### Environment

all envs

### Angular version

18.0.0

### PrimeNG version

17.17.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

0.0.0

**Comment by Tenmak** [comment]
They have an on-going branch for Angular v18, so they just need some time to spend on migrating.

https://github.com/primefaces/primeng/tree/v18

**Comment by NateRadebaugh** [comment]
@mehmetcetin01140  it looks like you've been contributing to that v18 branch -- is angular 18 support something planned in the near future? I understand there's additional features/updates that may be part of that branch, but I'm wondering if there's anything the community can do to help you all get the initial ng18 support released in the meantime?

cc @cetincakiroglu  @cagataycivici

**Comment by MAN-Sendance** [comment]
Angular v18 support would be great. I hope it does not take too long until we get it. :)

**Comment by cetincakiroglu** [comment]
Hi all,

We are currently working on PrimeNG 18. This update will bring significant changes not only in terms of Angular 18 support but also in theming. Our current theming application progresses through scss files, and updating theming is only possible to a limited extent with primeng-sass-theme or ng-deep. With PrimeNG 18, we will change this situation and introduce the new theming with a more modern approach. All theming elements will now be customizable with browser variables, eliminating the need for the primeng-sass-theme library. We have already tested this with primevue v4, which you can review at [v4.primevue.org](http://v4.primevue.org/). In addition to theming, we are also making improvements to some components. This update will not happen quickly like past major updates because completely changing theming from scratch and creating a custom build mechanism are significant tasks and will take a certain amount of time, but we plan not to prolong this time too much, with a maximum estimate of 1 month.

@NateRadebaugh @Tenmak @swami-sanapathi @vincent

**Comment by NateRadebaugh** [comment]
@cetincakiroglu  thank you I understand and appreciate the larger scope of the Angular 18 release.

What I am wondering is whether it would be possible to more quickly have a release that purely updates the dependency versions so unblock consumers of the application to fully and safely update to angular 18 without dependency mismatch errors. And then have a subsequent primeng 18.x release that would include the more thorough theming revamp.

I'm not sure how semantic versioning would support that, as it would depend on whether the theming refactor would be considered breaking change, or backwards compatible with existing CSS.

**Comment by MAN-Sendance** [comment]
@NateRadebaugh that's exactly what I thought too when I read @cetincakiroglu's comment.

**Comment by cetincakiroglu** [comment]
Hi @NateRadebaugh @MAN-Sendance 

We've tested the PrimeNG v17 with Angular 18 and found that we don't need to wait for PrimeNG 18 for Angular 18 support. We're planning to release v17.18.0 this week with peer dependency fixes. This will allow users to use PrimeNG 17 with both Angular 17 and 18. Other breaking changes and theming updates will be introduced in PrimeNG 18.

**Comment by MAN-Sendance** [comment]
> Hi @NateRadebaugh @MAN-Sendance
> 
> We've tested the PrimeNG v17 with Angular 18 and found that we don't need to wait for PrimeNG 18 for Angular 18 support. We're planning to release v17.18.0 this week with peer dependency fixes. This will allow users to use PrimeNG 17 with both Angular 17 and 18. Other breaking changes and theming updates will be introduced in PrimeNG 18.

Wow, thanks a million!

**Comment by swami-sanapathi** [comment]
Thanks @cetincakiroglu ❤️

**Comment by swami-sanapathi** [comment]
[ES Lint](https://github.com/angular-eslint/angular-eslint/releases/tag/v18.0.0) support for v18 was released a few hours ago.
