### ISSUE TITLE
Ability to export specific columns

### ISSUE THREAD

**Issue by jdpearce** [primefaces/primeng#1567]
**I'm submitting a ...**
```
[ x] feature request
```

I'd like the capability to export only selected columns from the DataTable.

e.g. `dt.exportCSV(['columnTwo', 'columnFour'])`

As it currently stands, it is impossible to select only the content of a single column for cut and paste, custom export would solve this in lieu of cell selection (and probably be easier to implement)

**Comment by pchristou** [comment]
@cagataycivici any plans on including something like this in a future release? I checked the roadmap and the only thing I saw related to export was "More export options like pdf and excel"

**Comment by pchristou** [comment]
Any update on this?

**Comment by cagataycivici** [comment]
Planned for 4.1.1.

**Comment by kenisteward** [comment]
@cagataycivici @jdpearce 

Just to give info on my research of the component I'll lay this here.  You can currently actually say which columns you want to export but it is slightly hacky (in my opinion) and definitely not recorded in the docs.

As you can see here
https://github.com/primefaces/primeng/blob/master/src/app/components/datatable/datatable.ts#L2137

the exportCsv function is base don the data table and specifically makes sure you have data AND a column with the FIELD property that is truthy (e.g. not null / undefined /empty string).

Because of this you can actually do something sneaky and say

in html
``
    <p-dataTable #dt [value]="data" exportFilename="data-objects">
      <p-header>
          <button type="button" pButton icon="fa-download" iconPos="left" label="Download CSV" (click)="export(dt)"></button>
      </p-header>
      <p-column *ngFor="let col of cols" [hidden]="col.hide" [sortable]="col.sortable" [field]="col.field [header]="col.header">
      </p-column>
    </p-dataTable>
``

in component
``
  public export(e: DataTable) {
// store the columns you want to not export
    const hiddenColumns: any[] = [];
    e.columns.forEach((c) => {
// search for whatever criteria you care for.  in my use case if the column is hidden i don't want to export that data
      if (c.hidden === true ) {
        hiddenColumns.push({field: c.field, col: c});
        c.field = '';
      }
    });

    e.exportCSV();
// restore their fields so databinding and such still works in the future
    hiddenColumns.forEach((hc) => {
      hc.col.field = hc.field;
    });
  }
``

so instead of just calling dt.exportCSV() I've done some pre processing the datatable's data that it uses in the export function.  

What would probably be preferable is there are API settings  that hook into this function that only show fields based on either callback criteria or setting criteria.  But this works fine currently.

**Comment by pantonis** [comment]
Any news on this feature?

**Comment by cagataycivici** [comment]
Planned for 4.1.1

**Comment by pantonis** [comment]
Thanks

**Comment by pantonis** [comment]
Was this implemented in 4.1.1?

**Comment by Mrtcndkn** [comment]
No, We rescheduled it for another release 4.1.2 

Regards

**Comment by kenisteward** [comment]
I made a response about being able to export a specific column. Basically
if it is hidden it won't get exported so you can. Loop though on export and
hide the ones you don't want exported

**Comment by pantonis** [comment]
@kenisteward although it works is not ideal

**Comment by kenisteward** [comment]
It gives you the funtional you want that was thought to not exist. That
makes it ideal for me at least. Until either they start accepting pr or
they implement it themselves

**Comment by pantonis** [comment]
@Mrtcndkn did you implement it in 4.1.2?

**Comment by saunandrea** [comment]
@cagataycivici & @pantonis Is this a feature now? I haven't been able to find the documentation.

**Comment by pantonis** [comment]
@saunandrea exactly
