### ISSUE TITLE
Table | Multiple Selection with dataKey shows wrong selected row count upon CTRL+A

### ISSUE THREAD

**Issue by mehmetcetin01140** [primefaces/primeng#15903]
Steps to reproduce:
Create a p-table with multiple selection enabled and use the dataKey property.
Populate the table with sample data.
Click on the Top rows in the table and press CTRL+A to select all rows.

Expected Result: All rows should be selected, and the selected row count should display the correct number of rows.

Actual Result: All rows are selected, but the selected row count is incorrect.

Sample Application: https://stackblitz.com/edit/z1cdw3-crjdxm?file=angular.json

**Comment by quentin-ineat-ca** [comment]
@cetincakiroglu Unfortunately still not functional. Same stackblitz than above but updated primeng 17.18.2.
Cmd + a is now working but selection with datakey is now broken.

1. CMD + A : ok
2. CMD + Click on a line : The total is broken and duplicate all selected lines.

Please add unit tests for table because it's such a critical function 🙏
A bit disappointed that this ticket mentions 'datakey' and 'ctrl + a' but 'datakey' alone was not even tested after the fix.
