### ISSUE TITLE
Table: Performance degradation for the table with pFrozenColumn

### ISSUE THREAD

**Issue by sd-git** [primefaces/primeng#15922]
### Describe the bug

After upgrading PrimeNG 17.14.1 -> 17.15.0 screen resize events started to flood components with change detection event and for non-trivial table with a lot of rows this is significant performance impact (up to the hanging devtools in debug mode).

After looking through the code changes between 17.14.1 and 17.15.0 this could be the potential trigger for degradation: https://github.com/primefaces/primeng/pull/15302

The latest version of PrimeNG 17.18.2 is also affected.

### Environment

Reproducible with stackblitz example and simplest table

### Reproducer

https://stackblitz.com/edit/github-my8zxt?devToolsHeight=33&file=src%2Fapp%2Fmy-table%2Fmy-table.component.html

### Angular version

17.3.11

### PrimeNG version

17.18.2

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.20.3

### Browser(s)

Chrome 126

### Steps to reproduce the behavior

1. Open stackblitz example project
2. Click on 'Add row' button to add some more rows
3. Resize preview window and monitor change detection counter rapidly raising.
4. Downgrade to PrimeNG version 17.14.1 and repeat steps 1-3
5. Notice that resizing preview does not trigger massive CD events/ impact performance

### Expected behavior

Same as in 17.14.1 - no massive CD events during screen/viewport resizing when table with pFrozenColumn is rendered.

**Comment by phalla-doll** [comment]
+1

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation and try the latest PrimeNG version(v19). If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,

**Comment by Loic-fr** [comment]
It is not fixed in latest v19.1.3.
Performances are awful when you have frozen columns directive in a table with a lot a columns and rows.
All our columns need to have the pFrozenColumn directive and we play with the frozen attribute to activate the frozen status : a window resize takes more than 30 seconds to render.

After analyzing, even if the recalculateColumns do nothing at all (empty function) the rendering takes a lot of time.

It seems the reason is the spamming of event listeners on window:resize (one for each cell in the table so row*columns). Removing that resolves the performances problems.

To add to that problem, the window:resize isn't even a good solution because the table can be resized through other means and frozen column width is not recalculate then. Examples : 
- adding columns might reduce the frozen column size
- having resizable columns makes frozen columns react weirdly
- allow resize of the container of the table through slider might change column size without recalculating the left or right value of the frozen columns.
