### ISSUE TITLE
p-dropdown keyboard navigation

### ISSUE THREAD

**Issue by vikore** [primefaces/primeng#16105]
### Describe the bug

Keyboard navigation issue -
Drop down value is not getting selected while navigating the item list through keyboard up/down arrow keys in the latest release version - 17 - https://primeng.org/dropdown#accessibility. It was working in previous release version - 15 - https://www.primefaces.org/primeng-v15-lts/dropdown#accessibility.

### Environment

Development

### Angular version

17.3.6

### PrimeNG version

17.16.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.16.1

### Steps to reproduce the behavior

1. Navigate to p-dropdown using keyboard tab key
2. Press space key or enter key to open dropdown
3. Then press up/down arrow keys
4. Observe the drop down value. It is not getting selected with arrow key navigation. User has to press enter key to select the highlighted value.

### Expected behavior

Drop down value should get selected while navigating with up/down arrow keys as in previous version - 15  along with enter key and spacebar key.

**Comment by richard-collette-precisely** [comment]
It is apparent on the docmentation screen
https://www.primefaces.org/primeng-v14-lts/dropdown

That tabbing between inputs is broken.

Additionally, when tabbing into a drop down, if the dropdown is editable, keyboard input is not enabled until the field is clicked on.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation and try the latest PrimeNG version(v19). If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,

**Comment by richard-collette-precisely** [comment]
This is an AWFUL way to manage a backlog.  Closing out issues with no related commit.  No validation of the issue.  You're basically dismissing the input of your paying customers.

**Comment by mertsincan** [comment]
We had about 1k–2k open issues, and many users have told us that most are already fixed in newer versions. Most reports come from different users, not the original reporters.
If you think the issue still exists, you can create a new issue using our new issue template and select supported versions in it. You can also help by sending a PR to fix the issue. PrimeNG is an open-source project, and it grows with contributions from the community. We appreciate your support!

Version data;
[92 issues FIXED for v18](https://github.com/orgs/primefaces/projects/4/insights/2)
[42 issues FIXED for v19(includes all 18.0.1 fixes)](https://github.com/orgs/primefaces/projects/4/insights/3)
[35 issues FIXED for v19.0.2](https://github.com/orgs/primefaces/projects/4/insights/4)

New issue roadmap; https://github.com/orgs/primefaces/projects/4

LTS version support;
https://primeng.org/lts
> STS means open source short term support whereas LTS stands for commercial long term support. Legacy versions are only supported by [PrimeNG PRO.](https://primeng.org/support)

**Comment by JesusMurua** [comment]
The problem is that the new components, for some reason, don't take the new attributes. Just need to apply this in global style.scss file

/**

Fix for p-dropdown item highlight on keyboard navigation.
The legacy theme is missing styles for the .p-highlight class,
making keyboard navigation invisible. This rule restores that visibility.
*/
.p-dropdown-panel .p-dropdown-items .p-dropdown-item.p-highlight {
background: #e9ecef !important;
color: #495057 !important;
}
/**

Fix for keyboard navigation highlight in list components (Dropdown, MultiSelect, etc.).
PrimeNG v17 uses the data-p-focused="true" attribute for keyboard focus,
which is not styled by legacy themes like Olympia. This rule adds the
necessary visual feedback.
*/
[data-p-focused="true"] {
background: #e9ecef !important;
color: #495057 !important;
}
