### ISSUE TITLE
Dropdown: Keyboard selection incorrect

### ISSUE THREAD

**Issue by emorin** [primefaces/primeng#16158]
### Describe the bug

We are having 2 big issues with the dropdown component that started with version 16.x.

In version 15.x, you could expand a dropdown and type a single character and the dropdown would cycle through the options that begin with that letter.

For example,
Rome
Rodeo

If you type r, it should select Rome. Then if you type r again it should jump to the next element which would be Rodeo.

It stopped working like that in version 16.x and now in 17.x. This is common for dropdowns to work like this. You should be able to keep typing the letter and the dropdown will cycle through the options that start with that letter.

The second issue is as follows.
Dropdown has a list of values that has a scroll bar. If you tab into the select and type a letter for a value that is past the view, the option overlay does not scroll down to see the selected value.

### Environment

Angular 17

### Angular version

17.1.2

### PrimeNG version

17.18.5

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.16.0

**Comment by JohnHuynh** [comment]
I've experienced the same issue here. I opened up p-dropdown and it does not highlight the correct list item on keyboard event "up" or "down". The highlight sticks on the pre-selected value and does not change.

**Comment by mkduer** [comment]
I was also running into both of the issues listed in the first comment. Currently running v17.18.11 with Angular v18.

1. Looking in the dev tools when using the keyboard up/down arrows to change focus showed that the aria logic was correctly updating as well as the focus values. To fix the issue, I had to add an explicit override for the focus.

Example
```
.p-dropdown-item {
  // preferred styling or empty

  &.p-focus {
    background: {focusColor} !important;  // fix for focus
    color: {fontColorWhenFocused} !important;  // optional color for font when focused
  }
}
```

2.. Looking at dev tools when using the keyboard to select a specific dropdown items did not show working functionality. I do see this working as expected on the PrimeNG website's examples of the dropdown. 

I'm not sure why the keyboard entries are not being detected. Our workaround for now is to add an explicit `[filter]="true"` field with the hopes that this will be fixed in later versions (or we can continue using the explicit filter).

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation and try the latest PrimeNG version(v19). If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
