### ISSUE TITLE
DynamicDialog: Style.Width not applying to Dialog

### ISSUE THREAD

**Issue by cz260** [primefaces/primeng#16177]
### Describe the bug

Using DialogService.open and passing style with width set in the config options no longer applies the width to the dialog. This worked in v17.18.3 and stopped working in v17.18.4.

### Environment

Using angular, vite & primeNg.

### Angular version

18.0.5

### PrimeNG version

17.18.4

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.11.1

### Expected behavior

Expect width to apply as it did before.

**Comment by cz260** [comment]
It does not work for me in any version about v17.18.4. 

This is the object I pass to the the primeNg service as config.style: 
![image](https://github.com/user-attachments/assets/d65459ed-d08e-43d1-b1cb-455f3f4afb8d)

In v17.18.7, these are the style attributes that get applied to the dialog: 
![image](https://github.com/user-attachments/assets/da43e4f8-cda4-4c67-a524-18eafb3e76b3)

when using v17.18.3, these are the style attributes that get applied:
![image](https://github.com/user-attachments/assets/62eaabd2-c599-4654-a14c-d3d88d6bdb0c)

I have made no changes to my code or environment other than upgrading primeNg between these screenshots. I am confused why this would work differently from one version to the next and will not apply the width attribute in the newer version.

**Comment by EnricoMessall** [comment]
@cz260 There was actually a change after v17.18.3 for v17.18.4 where the Prime team changed some stuff to use CSP compliant ngStyle instead of setting width and height direct in style.width and style.height for multiple components
<img width="494" alt="Screenshot 2024-08-06 at 20 19 07" src="https://github.com/user-attachments/assets/1e8b2f68-8f2f-4abd-89c8-aac7c77ada10">

With that: https://github.com/primefaces/primeng/commit/73e37250947e9511f6394769154941ed994c71c5

it changed into applying the config style and then width and height will be added from this.config.width and this.config.height overwriting your config.style.width and height probably. So i guess the wanted behaviour is to use this.config.width and this.config.height instead

**Comment by cz260** [comment]
@EnricoMessall Thank you so much for the information! That competely solved my problem and I will close this issue. Have a great day!
