### ISSUE TITLE
ngc Command fails with DropdownModule in angular-cli

### ISSUE THREAD

**Issue by Mage111** [primefaces/primeng#1627]
"primeng": "^1.0.1"
"angular-cli": "1.0.0-beta.21"

I got this error when using AoT compilation in Angular 2 (using angular-cli).

When I try to run ngc, it errors out as following:

C:>"node_modules/.bin/ngc" "tsconfig-aot.json"

`Error: Unexpected value 'DropdownModule' imported by the module 'SharedModule' at ..\node_modules\@angular\compiler\bundles\compiler.umd.js:17768:46 at Array.forEach (native) at CompileMetadataResolver.getNgModuleMetadata (..\node_modules\@angular\compiler\bundles\compiler.umd.js:17753:51) at addNgModule (..\node_modules\@angular\compiler\bundles\compiler.umd.js:24349:60) at ..\node_modules\@angular\compiler\bundles\compiler.umd.js:24360:16 at Array.forEach (native) at _createNgModules (..\node_modules\@angular\compiler\bundles\compiler.umd.js:24359:28) at analyzeNgModules (..\node_modules\@angular\compiler\bundles\compiler.umd.js:24238:16) at analyzeAndValidateNgModules (..\node_modules\@angular\compiler\bundles\compiler.umd.js:24248:37) at AotCompiler.compileAll (..\node_modules\@angular\compiler\bundles\compiler.umd.js:23987:20)`

I think it has resemblance to the issue [#31](https://github.com/yuyang041060120/ng2-validation/issues/31)

The metadata.json files are missing from the library which are required by ngc.

Can those missing files be added soon?
Thanks.

**Comment by cagataycivici** [comment]
Strange, I can see the metadata.json files at the distribution. Don't you have them?

**Comment by bradseefeld** [comment]
I was getting the same, but with the calendar module (see #858 which seems related to this).
```
ERROR in Unexpected value 'CalendarModule' imported by the module 'ProjectsModule'
```

`ProjectsModule` is a child module which gets imported into our `AppModule`. For kicks, I have tried importing `CalendarModule` into AppModule directly, but get the same error.

We are using primeng 1.1.3, angular 2.3.1, and angular-cli 1.0.0-beta.24

We are importing like:
```
import { CalendarModule } from "primeng/primeng";
```

Based on your previous reply @cagataycivici, I looked at the primeng module that was installed, and did not find any `*.metadata.json` in the root of the package (where the above import is importing from!).

However, there are metadata files in each component directory. So if you change the import to be:

```
import { CalendarModule } from "primeng/components/calendar/calendar";
```

It will work, since the metadata.json file is found in this directory.

I would suggest we leave this issue open until either the documentation is clarified that you need to be more explicit with your import path if you want to use AOT, or you also add the metadata.json file to the root of the repo too.

**Comment by Mage111** [comment]
It solved for me by upgrade to latest primeng version.

**Comment by cagataycivici** [comment]
Glad to hear.
