### ISSUE TITLE
p-dropdown: selected item is not changing when typing the first character of the items in the list

### ISSUE THREAD

**Issue by av-code-crafter** [primefaces/primeng#16462]
### Describe the bug

Before primeng version 16, when we just focus on the dropdown(with the drop down panel closed) and type the first character in the list, it used to change the selected item. 

For example check the behavior in version 15:
[Recording-20241001_121315.webm](https://github.com/user-attachments/assets/ef8f5c80-4ab5-424d-b2e7-f86aa7ca9c81)

But after version 16 this behavior is changed. The selected item doesnot change when typing first character of list items.

How can we achieve the same behavior ?

### Environment

Windows 10

### Angular version

17

### PrimeNG version

16

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18

**Comment by capc0** [comment]
You can set `selectOnFocus` to `true` in order to have the selection set correctly. However, the panel will be shown. So you effectivly have to confirm the selection with either tab or enter.

I have create a PR to add the property `autoShowPanelOnPrintableCharacterKeyDown`. In combination this restores the original behaviour.
