### ISSUE TITLE
18.0.0-beta.3 - base-style is affecting all elements

### ISSUE THREAD

**Issue by DbkMG** [primefaces/primeng#16640]
### Describe the bug

Testing primeng 18.0.0-beta.3 - some of our components are visible broken because the primeng base-style is affecting all html-elements.
![image](https://github.com/user-attachments/assets/82447f78-12cc-4ddb-9c05-387045061059)
is forcing all elements to be box-sizing: border-box

### Environment

primeng 18.0.0-beta.3

### Angular version

18.2.8

### PrimeNG version

18.0.0-beta.3

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.11.1

### Expected behavior

i would expect a scoping via css-class and not defining the box-sizing for all elements

**Comment by cagataycivici** [comment]
That CSS is a must have, we've also added box-sizing to before and after as well. All CSS libraries like Tailwind and Bootstrap use border-box sizing as well which is suggested. I'd definitely suggest switching your app to border-box otherwise you'll always have issues when trying to import a 3rd party UI widget whether it is PrimeNG or not.
