### ISSUE TITLE
Component: Table (bug visible on the docs page)

### ISSUE THREAD

**Issue by HockeyTrafalgar** [primefaces/primeng#16743]
### Describe the bug

Footer row for tables gets cramped up in the first column.

### Environment

https://v18.primeng.org/table#column-group

### Reproducer

https://v18.primeng.org/table#column-group

### Angular version

18.2.11

### PrimeNG version

18.0.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.15

### Steps to reproduce the behavior

Go to https://v18.primeng.org/table#column-group

**Comment by jamesrusso** [comment]
Just came across this issue here as well trying to create a foot with a sum of the columns. 

### Current Behavior
<img width="856" alt="Screenshot 2024-11-17 at 7 08 13 PM" src="https://github.com/user-attachments/assets/beb10810-16fe-4d8c-a35d-158a62dbe586">

It seems to be wrapping the &lt;tr&gt; in a div with p-datatable-foote class. If you remove this div and place the &lt;tr&gt; as the first child of the tfoot (as is the case with the tbody) it seems to render ok, however it is still not lined up perfectly due to the padding being wrong. Adding padding-left: 16px to the td makes it perfect. 

<img width="473" alt="Screenshot 2024-11-17 at 7 10 19 PM" src="https://github.com/user-attachments/assets/889016d9-2d71-4381-9316-beb71e914979">

### After moving the <tr> directly under the tfoot and not in the div.
<img width="966" alt="Screenshot 2024-11-17 at 7 11 15 PM" src="https://github.com/user-attachments/assets/f9aa696e-9494-4ec4-b0ea-001e24f5225d">

**Comment by cetincakiroglu** [comment]
Fixed in 18.0.0-rc.2
