### ISSUE TITLE
MultiSelect: pTemplate selectedItems does not work

### ISSUE THREAD

**Issue by delrem32** [primefaces/primeng#17063]
### Describe the bug

When pTemplate="selectedItems" is defined, the multiselect ignores it.

```
<p-multiselect
  [options]="countries"
  [(ngModel)]="selectedCountries"
  optionLabel="name"
  placeholder="Select Countries"
  display="chip"
  appendTo="body"
>
  <ng-template let-selectedCountries pTemplate="selectedItems"> //<--Always ignored
    <div *ngFor="let country of selectedCountries">
      {{ 'TEST' + country.name }}
    </div>
  </ng-template>
  <ng-template let-country pTemplate="item">
    <div>
      <div>{{ 'TEST INNER ITEM ' + country.name }}</div>
    </div>
  </ng-template>
</p-multiselect>
```

![image](https://github.com/user-attachments/assets/69781779-4424-47ad-ae4e-55d6fec05d43)

### Environment

ng18, primeng18

### Reproducer

https://stackblitz.com/edit/github-wcuxbgyk-b2wvspkg

### Angular version

18

### PrimeNG version

18

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.11

### Expected behavior

Selected items template should be defined regarding pTemplate='selectedItems'

**Comment by chumbalum** [comment]
There seems to be a general issue with pTemplate in PrimeNG 18. I'm having several issues with pTemplate in multiple context (p-card, p-dataview)

My observation: The problem gets fixed, if I add an template variable to the template, even though it is not used.

So maybe give this a try

`<ng-template let-selectedCountries pTemplate="selectedItems" #selectedItems>`

instead of

`<ng-template let-selectedCountries pTemplate="selectedItems">`

**Comment by egorbwork** [comment]
It works only with `selecteditems`. Looks as documentation is deprecated.

**Comment by Delagen** [comment]
Seems also typo in css https://github.com/primefaces/primeng/blob/master/packages/primeng/src/multiselect/style/multiselectstyle.ts#L72

**Comment by femangl** [comment]
I wanted to point out that, even though closed, the issue remains the same.
The documentation says, that the template is called `selectedItems` (see [here](https://primeng.org/multiselect#api.multiselect.templates.selectedItems), but you need to use `selecteditems` in order to get it working (at least with version 19.0.6).
