### ISSUE TITLE
Stop closing issues without fixing them

### ISSUE THREAD

**Issue by puschie286** [primefaces/primeng#17065]
### Describe the bug

Hundreds of issues gets closed with message like “this might not be related anymore”.

It’s extremely annoying and disrespectful for all people that report bugs and trying help

Closing the issue does not fix the problem! Most of the issues are still valid and the problem exists till today.

**Comment by mertsincan** [comment]
We have made so many changes that it is very difficult to determine whether the problem persists or not. Therefore, if your problem persists, please open a new issue with appropriate issue templating so that we can include it in our roadmap as soon as possible.

https://github.com/orgs/primefaces/projects/4

**Comment by puschie286** [comment]
So how about checking the issues ? Behind every issue are people that took time to test, verify and report it. So if you don’t answer the issue you should at least test it once before closing it
