### ISSUE TITLE
ConfirmDialog: icon has wrong size

### ISSUE THREAD

**Issue by Timmeeeey** [primefaces/primeng#17087]
### Describe the bug

The icon in the confirmation dialog has the wrong size when the InputGroupAddonModule is used.

![image](https://github.com/user-attachments/assets/1b27c2c1-b8a4-42ca-a066-feacc5a1e893)

### Environment

NA

### Reproducer

https://stackblitz.com/edit/github-n6fwtktk-1dgsramq

### Angular version

18.2.x

### PrimeNG version

18.0.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.14.0

**Comment by aimanicose** [comment]
Hello,

Facing same issue and made the same remark as @imaksp. The issue is not noticeable in the documentation page as the order of the styles is probably different.
Moving the confirmdialog-style bellow inputicon-style manually seems to remove the .pi class override but I can't do it programmatically.

**Comment by imaksp** [comment]
Hi all, as a workaround you can add this to your style.css file, it should fix priority issue:
```css
.p-confirmdialog-icon {
  font-size: var(--p-confirmdialog-icon-size);
}
```

**Comment by sale1234** [comment]
I’m experiencing the same issue. Notably, a hard refresh temporarily resolves it.
