### ISSUE TITLE
FileUpload: Empty template not working

### ISSUE THREAD

**Issue by alainosorio** [primefaces/primeng#17152]
### Describe the bug

FileUpload empty template was working in previous version 17.
FileUpload empty template is not working in current version 18-19.

It is also not working in the primeng examples.

Working here: https://v17.primeng.org/fileupload#template
<img width="404" alt="image" src="https://github.com/user-attachments/assets/83b0e12c-6142-4f36-969c-375d9f898a04" />

Not working here: https://primeng.org/fileupload#template
<img width="427" alt="image" src="https://github.com/user-attachments/assets/81281d09-fe61-4bd0-8c2f-70efb0e76855" />

### Environment

windows 11

### Angular version

19.0.4

### PrimeNG version

19

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

22.10.0

### Browser(s)

Chrome

### Expected behavior

FileUpload empty template should be working with custom content like previous version 17

**Comment by awdorrin** [comment]
Will this be back-ported to PrimeNG 18 LTS?

**Comment by PeterSisovsky** [comment]
@awdorrin and anyone looking to make the "empty" template work in v18: the fix introduced in v19:

`@if ((emptyTemplate || _emptyTemplate) && !hasFiles() && !hasUploadedFiles())`
has not been implemented in v18. In v18, the old code remains:
`@if (emptyTemplate && _emptyTemplate && !hasFiles() && !hasUploadedFiles())`
This means you need to use both approaches for template to make it work. Here's a hackfix:

```
<p-fileupload ... >
  <ng-template pTemplate="empty" #empty>YAY! Empty state works!</ng-template>
</p-fileupload>
```
Both `pTemplate="empty"` and `#empty` are necessary in the template until this issue is resolved in v18.

**Comment by awdorrin** [comment]
@PeterSisovsky thanks, i will try that out tomorrow!
