### ISSUE TITLE
pButton label render

### ISSUE THREAD

**Issue by ar53n** [primefaces/primeng#1911]
Hello i have a problem with pButton component label rendering with ng2-translate. In Appcomponent i set language, but button label is empty string.

Result:
![buttons](https://cloud.githubusercontent.com/assets/7085102/22286897/be9d5f22-e301-11e6-934a-2a9745c72eac.jpg)

When you navigate in system return this page correctly work

Correct:
![image](https://cloud.githubusercontent.com/assets/7085102/22286976/1ad6e8c6-e302-11e6-8812-f0fb57dc7f4e.png)

**Comment by SirDieter** [comment]
It will be fixed in 2.0. See #1685 
https://github.com/kryzys69/primeng/commit/3a34aef4f59608f986f882cd05b2b164bb1b57ca

**Comment by lebnic** [comment]
@SirDieter Thanks for the info. Can you explain this to me (I am fairly new to this repo): If it is already fixed in 2.0, why is'nt there a "hotfix" version for 1.1.3 ? I am currently implementing a new features in my solution (chips) that requirement 1.1.3; My new feature is implemented and I am ready to deploy, but this bug prevents me from doing so, because it would "break" the rest of my application... What do you think is best way I could deal with this situation? Should I fork 1.1.3 and make the fix on my own? Thanks :-)

**Comment by SirDieter** [comment]
@lebnic If you upgrade to the current version (2.0.0-rc.3), the bug will be fixed. But that version is not the final 2.0 yet, just a RC (release candidate).

**Comment by cagataycivici** [comment]
This should be fixed in recent PrimeNG release, please try with them and if issue persists drop a comment and we'll reopen.
