### ISSUE TITLE
ui-datatable-scrollable-header-box   margin-right: 17px;

### ISSUE THREAD

**Issue by Danieleeee** [primefaces/primeng#2057]
**I'm submitting a ...**  (check one with "x")
```
[ X] bug report => Search github for a similar issue or PR before submitting
```

**Current behavior**

ui-datatable-scrollable-header-box  have this style: **margin-right: 17px** that is set at runtime.

[Image](http://i.imgur.com/xTLz5gZ.jpg)

**Expected behavior**
NO margin-right: 17px

**Minimal reproduction of the problem with instructions**
`<p-dataTable [value] = "RecRemiDett" rowHover="true" scrollable="true" >`

* **Angular version:** 2.4.6

* **PrimeNG version:** 2.0.0

* **Browser:** [all ]

 
* **Language:** [ ES5]

**Comment by Danieleeee** [comment]
It happens when the scroll bar is not visible, because not necessary.
If you restrict table space, scroll bar appear and margin-right diappear

**Comment by ryanpm40** [comment]
This issue is still present.

**Comment by cagataycivici** [comment]
This should be fixed in recent PrimeNG release, please try with it and if the issue persists drop a comment with along with a test case based on plunkr below and we'll review again.

http://plnkr.co/edit/Wj39h1?p=preview

Note that it is the width of the scrollbar that depends on the environment so needs to be calculated.

**Comment by xeleoss** [comment]
Now if the scroll appears after rendering, the margin is not added and the fields are removed
