### ISSUE TITLE
Datatable nested datatable not showing header

### ISSUE THREAD

**Issue by sivanandanr** [primefaces/primeng#2090]
Im using datatable with nested datatable. On row expand I will retrieve the data from service and bind result in inside the datatable. When I use nested datatable, header are not displaying correctly. Im using primeng 1.1.0

**Comment by sivanandanr** [comment]
Add below class in top of the template

table thead tr th span.ui-column-title {
    display: block !important;
}

This works

**Comment by Mrtcndkn** [comment]
@sivanandanr  I tried this locally and it seems normal to me. See the screenshot below.

https://pasteboard.co/2ecVlblWZ.png

Could you please create a plunkr?

http://plnkr.co/edit/Wj39h1?p=preview

**Comment by Mrtcndkn** [comment]
If issue persists on the latest version of primeng 4.1.0-RC2 please provide a plunkr so we can reopen the issue.

**Comment by karthiks3000** [comment]
I encountered the same problem in one of my tables. It seems like a bug to me because I was able to resolve the issue by removing   [responsive]="true" from my table definition

Maybe this helps -

This does not work:
`<p-dataTable #dtPrograms [value]="programRecords" expandableRows="true" 
                resizableColumns="true" columnResizeMode="expand"
                reorderableColumns="true" exportFilename="Content Catalog"
                [(selection)]="selectedProgramRecords" [responsive]="true"              
                > `

This works:
` <p-dataTable #dtPrograms [value]="programRecords" expandableRows="true" 
                resizableColumns="true" columnResizeMode="expand"                
                reorderableColumns="true" exportFilename="{{TaskType}} Tasks" 
                  [(selection)]="selectedProgramRecords"    
                > `

I am using Angular 4 with Primeng 4.0.2

**Comment by Mysame** [comment]
Definitely to do with the [responsive] attribute, also happens with 4.1.3

**Comment by brianjly** [comment]
This is still an issue.  Have my DataTable placed in side a TabView Component, and the headers are not displaying.  This class is setting the display to none:

` .ui-datatable-reflow .ui-datatable-data td .ui-column-title`

I have to use sivanandanr's hack in order to get around this.  I'm not using the responsive attribute and I'm still getting this issue.  Also have the latest version as of today.

**Comment by sivanandanr** [comment]
@Mrtcndkn I have created Plunker and able to reproduce.

http://plnkr.co/edit/D0OiCf?p=preview
