### ISSUE TITLE
[DEPRECATED] <template> -> <ng-template>

### ISSUE THREAD

**Issue by eXXeption** [primefaces/primeng#2257]
**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

* **Angular version:** 4.x.x

* **PrimeNG version:** 2.x.x

* **Browser:** [all]
 
* **Language:** [all]

The <template> tag is deprecated with angular 4.
<ng-template> is the way to go now.

Angulars template parser throws a warning for each <template> on console, kind of annoying.
```
Template parse warnings:
The <template> element is deprecated. Use <ng-template> instead ("mplate" class="ui-autocomplete-token-label">{{field ? val[field] : val}}</span>
                    [ERROR ->]<template *ngIf="selectedItemTemplate" [pTemplateWrapper]="selectedItemTemplate" [item]="val"></templ"): AutoComplete@10:20
The <template> element is deprecated. Use <ng-template> instead ("      <span *ngIf="!itemTemplate">{{field ? option[field] : option}}</span>
                        [ERROR ->]<template *ngIf="itemTemplate" [pTemplateWrapper]="itemTemplate" [item]="option"></template>
        "): AutoComplete@23:24
```

**Comment by upmauro** [comment]
I wont create PR because, I don't know about @cagataycivici plans for Angular 4 (new branch or migrate). In my opnion we can migrate to 4, because not have many break changes.

By the way reading the doc https://github.com/angular/angular/blob/master/CHANGELOG.md#features we can se compilation flag now we have:

compiler: Add a enableLegacyTemplate option to support <template> (e99d721)

**Comment by cagataycivici** [comment]
This is fixed already at master. (4.0)
