### ISSUE TITLE
ToolTip for Tab-Panel

### ISSUE THREAD

**Issue by karthiks3000** [primefaces/primeng#2262]
**I'm submitting a ...**  (check one with "x")
```
[X ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**

Tool tip on a tab panel does not work

` <p-tabPanel  header="Vendors" leftIcon="fa-youtube" pTooltip="Tooltip text" >`

**Expected behavior**

When a mouse hovers over the tab header, the tooltip should appear

**Comment by mronus** [comment]
Is there any progress on the subject? TabViewNav can be overridden somehow but I would like to use the official solution if this feature will be available in the near future.

**Comment by pujansrt** [comment]
When I use tooltip over tabView tooltip show event hovering over TabContent not on just Header. It would be nice if we can know any workaround or official guide for this.

`<p-tabView pTooltip="Filename" tooltipPosition="top" showDelay="1000">`

**Comment by riccardomariani** [comment]
Same problem here. What about using an ng-template to define a custom header? This way we could use pTooltip assigned to an inner component. Something like this:
`<ng-template>
         <div pTooltip>tab text</div>
</ng-template>`
It would be even better if the pTooltip was a Component so that we can internationalize it using i18n! Or is there any different ways to internationalize the pTooltip using i18n?

**Comment by rajkumar-surnar** [comment]
Hi Prime-ng team,

First of all, thanks for a wonderful open-source and free component library. I have been using the library for an year or so.

Lately, I have had a customer requirement asking for tooltips to be shown in a UI piece developed using p-tabview and p-tabpanel. I went through documentation and found that such facility does not exist.

I was navigating through the issue tracker and was hoping to find a solution around this. Unfortunately, I could't find any solution. I found this issue relevant to my requirements and I could see that this issue was logged in May, 2017. However, I do not see any commits around this issue. It will be great to know if there has been any development around this topic on your side. Do you have any plans about when this feature may be available.

If there isn't any committed plan for this, I will be highly thankful to know any possible workaround for now.
Thanks once again for feature component set. Speedy reply will be really appreciated.

Regards,
Rajkumar

**Comment by Pilukina** [comment]
I also believe that It could be very useful to have the internationalization on the pTooltip

**Comment by cagataycivici** [comment]
Here we go;

<img width="877" alt="screen shot 2018-08-02 at 11 40 21" src="https://user-images.githubusercontent.com/686247/43572840-1ab534be-9649-11e8-8dee-0d686f9f6ba7.png">

**Comment by madhav5589** [comment]
@cagataycivici Thanks for this great feature. I was curious that can we make this tooltip show as conditional? For example, only show tooltip when a specific condition met.
Thank you.
