### ISSUE TITLE
Autocomplete limit on multiple selected items

### ISSUE THREAD

**Issue by om3** [primefaces/primeng#2299]
Hi, I need to limit the number of inputs in autocomplete component configured with multiple parameter.

<p-autoComplete [(ngModel)]="textAutoComplete" [suggestions]="veiculos" (completeMethod)="search($event)" [multiple]="true"></p-autoComplete>

**Comment by failpunk** [comment]
I also need this feature.  

I can't use `[(ngModel)]` because it doesn't work with **reactive forms and the parent formGroup directive**

Currently I have to use the `onSelect` event to set the parent form when the user selects an item. The value of the form will not be updated again until the `onSelect` event fires again. This is very confusing as the input can be modified by the user without selecting another auto-complete item and the underlying parent for will still have the original selection in the background.

1.  I need to either use the `multiple` input with a limit of 1 so that when the chip is removed the parent form will be updated.
2. I need a way to hook into the `(change)` event of the autocomplete so I can manually clear the value in the parent form when the user changes the autocomplete input.

**Comment by cagataycivici** [comment]
Sure we can do it, chips has it already.

**Comment by kareljan** [comment]
Any Idea when this will be in?

**Comment by Meberem** [comment]
I have 1/2 a solution
```
<p-autoComplete #pAutocomplete (onSelect)="myFilteringEvent($event)" [formControlName]="myFormControlName"></a-autoComplete>

interface IMyType {
	value: string;
}

class MyComponent {
	@ViewChild("pAutocomplete") autoComplete: AutoComplete;

	myFilteringEvent(myType: IMyType) {
	    this.autoComplete.value = this.autoComplete.value.filter((val, i) => myType.value === val.value);
        this.autoComplete.onModelChange(myType.value);

}
```

This will set the myFormControlName form control to be the value of the IMyType chosen. It is a bit of a bodge as it will overwrite the existing data, so observables will probably fire mutiple times one with an array of options then with the single value. But it did get me what I needed, hope it helps someone

**Comment by cjsmith87** [comment]
Did this ever get implemented or is there a workaround I can use?

**Comment by danyalfaro** [comment]
A workaround I found to have the autocomplete limited to one selection and work with reactive forms is the following:

1. Add the (onSelect) event to the autoComplete component:

`<p-autoComplete
              [suggestions]="var"
              (completeMethod)="foo($event)"
              (onSelect)="onSelect($event)"
              formControlName="xyz"
              [multiple]="true"
              ...
            >`
           

2. Create a onSelect(event) method that sets the reactive form's Control Value to the selected item each time.

`onSelect(value): void {
    this.form.controls.agents.setValue([value]);
  }`            
  
  This way you can leverage the templates that are only usable with the autocomplete set to multiple, and still always have only one selection.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,

**Comment by cjsmith87** [comment]
My fix for this was never implemented. Do you have any plans to add this fix or to provide your own code to provide a MaxSelection property for Autocomplete when Multiple=True
