### ISSUE TITLE
Improve selection comparison in tree

### ISSUE THREAD

**Issue by canghaizhiyue** [primefaces/primeng#2427]
Hi,thank you for your job.I want to know how to initialize a Multiple Selection Tree with selected node? additional,I want to select the parent node which not all of it's children is selected.

**Comment by britvik** [comment]
They use object reference comparison to select nodes. That means you need to initialize **selection** input model from the same objects you provide as **value** input to p-tree component.

If you want to select parent with only some children, then children should have parent property pointing to a parent node, which should have **partialSelected** = true.

Hope I was clear enough :). If not, use augury extension or just debugging to see how **selection** model changes when you check/uncheck nodes and initialize them accordingly.

**Comment by canghaizhiyue** [comment]
Hi,britvik! Thanks for your reply.
first,I try to initialize the selected data to selection ,but in frontend,the tree not select the node,then I  look at the source , I see they initialize the tree like this 'if(this.selection[i] == node) ', and the selection and the treenode is not a same object which I initialized in backend,so it not select.there are two way to solve this question,one  modify the source code where i mentioned above,the other initialize the selection in frontend follow your reply.
second,I want to push the partialSelected node to selection,I must modify the source, and I have realized this.
all, thank you again.

**Comment by canghaizhiyue** [comment]
Hi,@britvik! Thanks for your reply.
first,I try to initialize the selected data to selection ,but in frontend,the tree not select the node,then I look at the source , I see they initialize the tree like this 'if(this.selection[i] == node) ', and the selection and the treenode is not a same object which I initialized in backend,so it not select.there are two way to solve this question,one modify the source code where i mentioned above,the other initialize the selection in frontend follow your reply.
second,I want to push the partialSelected node to selection,I must modify the source, and I have realized this.
all, thank you again.

**Comment by cagataycivici** [comment]
We will review it as an enhancement.

**Comment by antialiasis** [comment]
Hi,

I've just bumped into this and it's incredibly inconvenient. The actual data that I'm storing in a database is only the `data` property of the node (which is unique); I assumed that controlling the value that Primeng will use as the model value was the whole point of the data property. Instead, it insists on storing the entire node (meaning I can't use the two-way binding and instead have to override the onNodeSelected event to pick out the actual data property that I want), and in order to properly initialize the selection, I'd have to write code to walk the entire node tree to find the exact node object with that data property, instead of just passing in the actual value that matters. I'm probably not going to do that and instead will just modify the library in a fork to work with the data value instead, but I really wish I (and other users) wouldn't have to.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
