### ISSUE TITLE
Feature Request: Pagination using <link rel="next" > <link rel="prev">

### ISSUE THREAD

**Issue by vitorstick** [primefaces/primeng#2610]
I'm submitting a 

[X] feature request 

Use the "prev" and "next" link relations accordingly with:

https://msdn.microsoft.com/library/jj883726(v=vs.85).aspx

Probably it would be something like:

`<a rel="next" class="ui-paginator-next ui-paginator-element ui-state-default ui-corner-all" href="#" tabindex="0">`

`<a rel="prev" class="ui-paginator-prev ui-paginator-element ui-state-default ui-corner-all" href="#" tabindex="0">`

**Comment by upmauro** [comment]
This is a wrong use to "rel" attribute I guess because this is used when you have a link to another linked page with your content.

For example, if you have A.html and B.html, in A you put `<a rel="next" href="A.html">`.

I searched on internet about googlebots crawling and not found explanation about how the engine works with this property when is ajax pagination.

Please if you have ideias about how it's work, so we have a cool discussion :)

**Comment by cagataycivici** [comment]
Not sure about this, needs more discussion.
