### ISSUE TITLE
Pass rowIndex to column template

### ISSUE THREAD

**Issue by cagataycivici** [primefaces/primeng#268]
Expose rowIndex as a template variable in addition to existing column and rowdata;

```xml
<p-column field="color" header="Color">
            <template #col #car="rowData" #ri="rowIndex">
                {{ri}}
                <span [style.color]="car[col.field]">{{car[col.field]}}</span>
            </template>
        </p-column>
```

**Comment by ilianiv** [comment]
I've noticed that `rowIndex` is actually an absolute row index: 
```
((page_number - 1) * items_per_page + row_number)
```

It's nice but if I use lazy loaded datatable rowIndex can't help me a lot because it doesn't match item's index in component's collection.

**Example:**
I'm lazy loading events in datatable with 5 items limit and I want to be able to remove an event from events array by index.
 - On first datatable page there is no problem with rowIndex. We can delete some event with events.splice(rowIndex, 1) for example.
```
events: [ {event a}, {event b}, {event c}, {event d}, {event e} ];
```
Clicking on 2nd row's delete button will remove events[1] element - Great!
![image](https://cloud.githubusercontent.com/assets/3925630/17615914/f80de322-6079-11e6-8c0a-41ef1234cbc0.png)
 - But on page two events array gets filled with other 5 events (lazy loaded from an API) indexed from 0 to 4 again
```
events: [ {event f}, {event g}, {event h}, {event i}, {event j} ];
```
Clicking on 2nd row's delete button will remove events[6] element - but no! There is no event at position 6 :cry: 
![image](https://cloud.githubusercontent.com/assets/3925630/17616051/eddac432-607a-11e6-8166-e2152c267086.png)

So I suggest renaming `rowIndex` to `absRowIndex` and adding `relRowIndex` variable that will return relative row index for current datatable page.
