### ISSUE TITLE
Starting application with primeNG using Bootstrap theme.

### ISSUE THREAD

**Issue by ryanfrnnds** [primefaces/primeng#2793]
Hello! I'm starting a project with primeNg and would like to use it with the Bootstrap theme. I found this project in gitHub but I did not understand how it works. Would you like to set the primeNg theme to use it with bootstrap? Or would I simply have to add class to the components of primeNG? And if I would have to add class to its components where do I find a "Documentation"? For example: I created the first demo project with primeNg and added the class "btn-btn-secondary" and it did not work. In this project I checked the demo folder for the button HTML and I saw that the class is "ui-button-secondary" ... Anyway, do I need to add the class or just need to define a theme? If I need to define the class I'm based on?

**Comment by unimatrix27** [comment]
dont have an answer but the same issue. I am using bootstrap default theme (my project is based on yo aspnetcore-spa template) and I put the autocomplete from primeNG in there. functionality works but I have also no clue about css. For example the autocomplete when it openes moves down all other components below instead of showing an overlay. 
I am using both bootstrap.css as well as primeng bootstrap css (through webpack) and I know that this works because when i change primeng theme i can see that the button color changes etc. but the autocomplete overlay itself shows bullets (li tags?) and also the button has a text that i found out is somewhere hidden on the demo page. There seems to be no documentation?

https://snag.gy/kF7xrl.jpg

**Comment by unimatrix27** [comment]
i figured out why i had a problem...i am using webpack and it seems the primeng.css was not parsed due to an error with the gif images. as a hack i just removed those gif references out of the .css file and run webpack again, and e voila - it works. 

@ryanfrnnds PrimeNG comes with a bootstrap them as a css file. Just add this on top of the normal bootstrap css files and the normal primeng file and you should not have to do anything manually. 
My webpack.config.vendor.js just has those lines:

                'bootstrap',
                'bootstrap/dist/css/bootstrap.css',
                'font-awesome/css/font-awesome.css',
                'primeng/resources/primeng.css',
                'primeng/resources/themes/bootstrap/theme.css',

**Comment by cagataycivici** [comment]
Please use forum for questions, thank you.
