### ISSUE TITLE
How do we stop the default functionality of expanding while clicking anywhere on the header, as I  Need to bind button inside header for this job?

### ISSUE THREAD

**Issue by vimalvaira** [primefaces/primeng#2844]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

http://plnkr.co/edit/VZbdZfQ7SuTV87tTkbYR?p=preview

**Current behavior**

**Expected behavior**

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.X

* **PrimeNG version:** 2.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by sudheerj** [comment]
Please use forum for any kind of questions. Also the issue didn't explain what kind of component used, no description and plunker example too.

**Comment by vimalvaira** [comment]
Sorry I forgot this repos represent all Primeng component. I was talking about 'accordion'
I have content on 
<p-accordionTab [selected]="istrue">
<p-header>
<button (click)="checkIfCanOpen()" >open?</button> 
<button  >info</button>//nothing should happen on clicking this
</p-header>
</p-accordionTab >

**Comment by cwistedt** [comment]
@werts @vimalvaira You guys ever solved this? I also ran in to this problem but eventually had to abandon it and put my button elsewhere.

**Comment by cwistedt** [comment]
Ill put this here in case someone else i interested:

As it turns out the accordion.js file responsible for handling behaviour of toggling the tab does not respect if preventDefault has previously been called (like in a click method for button inside the Accordion header).

It looks something similar like this:

>   AccordionTab.prototype.toggle = function (event) {
> 
>         if (this.disabled || this.animating) {
>             return false;
>         }
> 

When i change to this:

>   AccordionTab.prototype.toggle = function (event) {
> 
>         if(event.defaultPrevented)
>             return false;
>         if (this.disabled || this.animating) {
>             return false;
>         }
> 

It works. But since i dont want to change the source code of PrimeNg i added this in boot.ts

> // Override Accordion Toggle to prevent toggle if preventDefault has been called
> var originalAccordionToggle = AccordionTab.prototype.toggle;
> AccordionTab.prototype.toggle = function(event: Event) {
>     if(!event.defaultPrevented)
>         return originalAccordionToggle.call(this, event);
>     event.preventDefault();
> };

Links i found interesting investinagting this:
 * Link about extending a prototype function - https://stackoverflow.com/questions/11381437/extending-prototype-function-without-overwriting-it
 *  Why you should not use stopPropagation - https://css-tricks.com/dangers-stopping-event-propagation/
