### ISSUE TITLE
Data table with filter and sort does not work with headerColumnGroup

### ISSUE THREAD

**Issue by panakour** [primefaces/primeng#2900]
**I'm submitting a**
```
[x] bug report 
```

**Plunkr Case (Bug Reports)**
http://plnkr.co/edit/R5dhGSESVX5qqaCxUz55?p=preview

**Current behavior**
It doesn't do anything

**Expected behavior**
Filter and sort columns of the data table

**Please tell us about your environment:**

* **Angular version:** 4.1.3

* **PrimeNG version:** 4.0.1

**Comment by mpulido73** [comment]
Same issue happens to me. Header with rowspan with sort functionality does not work properly.

**Comment by Mrtcndkn** [comment]
The problem here is that sort and filter function requires a field attribute for their functionality. And that field should match with your data at the first place. For example

    <p-column field="advertName" header="Advert Name" rowspan="2" [filter]="true" filterPlaceholder="Search"
                      filterMatchMode="contains"></p-column>
    <p-column field="advertName" header="Advert Name" rowspan="2" [sortable]="true></p-column>
Both of these will work inside a headerColumnGroup in your plunkr you don't have any fields on your columns which is inside of the headerColumnGroup's.

Try these out please if the issue will persist feel free to open this ticket anytime.
@panakour @mpulido73
