### ISSUE TITLE
p-menubar with sublinks does not open on android

### ISSUE THREAD

**Issue by ASK83** [primefaces/primeng#2931]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

This behavior can be seen at the website with the following url: 
https://www.primefaces.org/primeng/#/menubar

**Current behavior**
The menus with a submenu does not show by touching them on my phone when using MenuBar and tieredMenu. But this is working for megamenu correctly. 

**Expected behavior**
Touching menus with submenu has to show the submenu list. 

**What is the motivation / use case for changing the behavior?**
Important for screens that require touch.

**Please tell us about your environment:**
Android

* **Angular version:** 4.1.3

* **PrimeNG version:** 4.0.2

* **Browser:** Chrome 
 
 Thanks

**Comment by cagataycivici** [comment]
@mertsincan Can you check this on android?

**Comment by sourdoth** [comment]
i have the same issue
[problem with menuBar](https://github.com/primefaces/primeng/issues/2944)

**Comment by cagataycivici** [comment]
Review for 4.1.1

**Comment by cagataycivici** [comment]
Tracked at #2449

**Comment by cwadrupldijjit** [comment]
This issue actually is slightly different, as pointed out by @Venthe in the linked issue.  AutoDisplay might work just fine (I've not really tested `[autoDisplay]="true"`, but the desired effect in my case would be `[autoDisplay]="false"`).  Sub-menus don't display at least with menu bars in android.  I'm seeing the same behavior, where the main menu dropdown opens just fine, but sub-menus close since hovering doesn't exist and it sounds like the `p-menubarsub` (or `MenubarSub`) doesn't actually have the ability to not close when clicked.  In fact, even if I'm not on a mobile device, the fact that when I click on an item with a submenu and it closes is actually aggravating.  Including some logic to detect if the current item has sub-items when clicking and toggling the open state would be much more desirable than closing the entire menu system.

Could this issue be re-opened?  Or should a new issue be added?  Or is it not priority enough that it might make life easier to just fork and adjust it myself?
