### ISSUE TITLE
Datatable columns should have option for exporting

### ISSUE THREAD

**Issue by pantonis** [primefaces/primeng#2945]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[X ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
When working with Datatable and use export functionality all columns are exported and there is no option (attribute) to exclude a column from exporting.

* **Angular version:** 
4.0.3

* **PrimeNG version:** 
4.0.2

**Comment by kenisteward** [comment]
dupe #1567 @cagataycivici 

Also is there a roadmap / changelog somewhere?  I'm considering contributing export changes but don't know where I can.

**Comment by cagataycivici** [comment]
Duplicate yes, please see wiki for roadmap.

**Comment by kenisteward** [comment]
@cagataycivici Ahh I see
DataTable

More export options like pdf and excel
State saving featuring across views
Cell Selection
Frozen Rows

is planned and i see that might be for 4.1.1 but I don't know how long major/minor patches take. 
As a part of it I would also suggest an onExport callback be created in order to change the way the field is exported as well as changing the default export to use JSON.stringify() because currently objects are exported as [object: OBJECT] unless you explicitly implement .toString()
