### ISSUE TITLE
Compatibility for Scrollable and Responsive datatable

### ISSUE THREAD

**Issue by erkancinar** [primefaces/primeng#2980]
```
<p-dataTable [value]="rows" (onRowDblclick)="DoubleClick($event)" selectionMode="single" [(selection)]="selectedRow" dataKey="id" scrollable="true"  scrollHeight="200px" [responsive]="true" [stacked]="stacked">
            <p-header>Stoklar</p-header>
            <p-footer>Toplam {{ rows.length }} adet stok mevcut</p-footer>

            <p-column *ngFor="let column of columns" [header]="column.header" [field]="column.field" sortable="true" filter="true"></p-column>

            <p-column header="Sıra">
                <ng-template let-rownumber  let-index="rowIndex" pTemplate="body">
                    <span>{{ index+1 }}</span>
                </ng-template>
            </p-column>
        </p-dataTable>
```

When resize the page , responsive table works , but huge gap between scroll bar and rows.

Below 557px scroll true responsive true

![557px](https://cloud.githubusercontent.com/assets/8149345/26753850/50064a92-4878-11e7-94fb-20fe80d79e7a.PNG)

Below 557px responsive true scroll false

![557px_withoutscroll](https://cloud.githubusercontent.com/assets/8149345/26753860/74fe97b4-4878-11e7-9b80-24c9b4d019de.PNG)

Normal width (119px)

![1119px](https://cloud.githubusercontent.com/assets/8149345/26753870/8f6ede56-4878-11e7-99d2-c5e42dccfc03.PNG)

**Comment by kenisteward** [comment]
I investigated this and for some reason it is taking the width of the first column to be the new body width and not the original body width with all the columns

**Comment by kenisteward** [comment]
Upon further investigation it turns out all that needs to happen is when the columns are stacked it needs to do a width 100% !important in order to override the styles set on the columns initially with  [style]

When i applied this
``
.ui-datatable-reflow .ui-datatable-data > tr > td {
        width: 100% !important;
      }
``

everything worked fine.  in the actual library we'd want to add either that or add to the existing lib style
``
@media ( max-width: 35em ) {
    .ui-datatable-reflow .ui-datatable-data > tr > td {
        text-align: left;
        display: block;
        border: 0 none;
        width: 100% !important;  // <---------- HERE
		-webkit-box-sizing: border-box;
		-moz-box-sizing: border-box;
		box-sizing: border-box;
		float: left;
		clear: left;
    }
}
``

@cagataycivici  this is a very easy fix if you would like to to make a PR for it.

**Comment by cagataycivici** [comment]
Thank you, will review
