### ISSUE TITLE
Datatable resizableColumns and selectionMode="multiple" incompatibility. Datatable resizableColumns make selectionMode multiple checkbox column width equal to page width

### ISSUE THREAD

**Issue by imranshafqat** [primefaces/primeng#2987]
Without applying resizableColumns property on datatable.
```
<p-dataTable [value]="dataTableRows" scrollable="true" [rows]="10" [paginator]="true" [pageLinks]="3" [rowsPerPageOptions]="[5,10,20]"
    [headerCheckboxToggleAllPages]="true">
     <!--resizableColumns="true">-->
    <p-column [style]="{'width':'30px'}" selectionMode="multiple"></p-column>
    <p-column *ngFor="let col of dataTableCols; let i = index" [field]="col.ColumnName" [header]="col.ColumnDisplayName" [hidden]="col.Hidden"
        [style]="{'width':'200px'}" [sortable]="true">
        <ng-template pTemplate="header">
            {{col.ColumnDisplayName}}
            <i class="fa fa-cog column-chooser-button" aria-hidden="true" (click)="setCurrentlySelectedColumnIndex(i);colToglPnl.toggle($event);"></i>
        </ng-template>
    </p-column>
</p-dataTable>
```
![image](https://cloud.githubusercontent.com/assets/3274225/26774338/40f4fdf6-49e9-11e7-9813-e6d5390fc6f4.png)

After applying the resizableColumns property on datatable.
```
<p-dataTable [value]="dataTableRows" scrollable="true" [rows]="10" [paginator]="true" [pageLinks]="3" [rowsPerPageOptions]="[5,10,20]"
    [headerCheckboxToggleAllPages]="true" resizableColumns="true">
    <p-column [style]="{'width':'30px'}" selectionMode="multiple"></p-column>
    <p-column *ngFor="let col of dataTableCols; let i = index" [field]="col.ColumnName" [header]="col.ColumnDisplayName" [hidden]="col.Hidden"
        [style]="{'width':'200px'}" [sortable]="true">
        <ng-template pTemplate="header">
            {{col.ColumnDisplayName}}
            <i class="fa fa-cog column-chooser-button" aria-hidden="true" (click)="setCurrentlySelectedColumnIndex(i);colToglPnl.toggle($event);"></i>
        </ng-template>
    </p-column>
</p-dataTable>
```
![image](https://cloud.githubusercontent.com/assets/3274225/26774522/13334aac-49ea-11e7-8a21-d1d6caf52556.png)

**Comment by fberthel** [comment]
Hey,

Can you provide a MWE (minimal working example) from plnkr or codepen?

We're using the dataTable with several features (`multi-selection`, `sorting`, `filtering`, `pagination`) and I even included the `scrollable` feature and set the witdh so the scrollbar is shown for reproducing this bug, but it's working properly.

Are you sure the bug is a result of the combination of `resizableColumns` and `selectionMode="multiple"`?
Did you already tried it without `selectionMode="multiple"` and it worked?

My guess would be it is rather the combination of using `ngFor` with `scrollable` and `resizableColumns`, but I can't tell without the MWE.

**Comment by cagataycivici** [comment]
Unable to replicate, please provide a test case based on plunkr below and we'll review again.

http://plnkr.co/edit/6q5v84DWolH6DeAdi70w?p=preview
