### ISSUE TITLE
Angular AOT + Rollup Error on PrimeNG Module

### ISSUE THREAD

**Issue by mustafaekim** [primefaces/primeng#3064]
Hi, I am getting an error on primeng module when I try to rollup my angular app.

```ts
⚠️   'default' is imported from external module 'rollup' but never used

�   A module cannot import itself
src\aot\weby\peoplive\spa\src\aot\weby\node_modules\primeng\components\growl\growl.ngfactory.js (10:0)
 8: import * as i1 from 'primeng/components/growl/growl';
 9: import * as i2 from '@angular/common';
10: import * as i3 from './growl.ngfactory';
    ^
11: import * as i4 from 'primeng/components/dom/domhandler';
12: export var GrowlModuleNgFactory = i0.ɵcmf(i1.GrowlModule, [], function (_l) {
```

I use primeNG 4.0.3

**Comment by cagataycivici** [comment]
Please use forum for cases like these. Seems like a config issue on your side.

**Comment by mustafaekim** [comment]
OK, I've posted on forum but it will be a surprise for me if it is a configuration issue because nothing has changed as far as I know.

**Comment by ajshapiro** [comment]
I have the same "module" cannot import itself, using Angular 4.2.2.  I rolled Angular back to 4.1.3 and the problem went away.

Note that I am using PrimeNG 2.0.6 because I have problems with the carousel in 4.0.x.  I noticed a similar error posted very recently in Angular Material, so I think this has something to do with Angular 4.2.x.
