### ISSUE TITLE
Adding data in DataTable not reflecting on UI

### ISSUE THREAD

**Issue by kamran-pervaiz** [primefaces/primeng#3070]
Hi,

I upgraded primeng from version 1.0.0 to 4.0.3 because it contains a fix which I did for fileupload (#2745). When i regression tested my site, it seems adding data to DataTable is not working anymore. did you guys change the behaviour. it doesnt update the UI.

As below Gif file shows that its not refreshing the UI although I can see the object is added in the array in console. If i save the record, it does save it in database and will show on next refresh. I believe its not calling updateDataToRender but could be wrong.

I can provide the code if its necessary but is it a known bug?

![2017-06-12_15-48-11](https://user-images.githubusercontent.com/2331946/27039979-90592fd6-4f87-11e7-82c0-828cf5c8fef4.gif)

primeng: 4.0.3
angular:  4.0.0

**Comment by ctrl-brk** [comment]
https://github.com/primefaces/primeng/issues/2219#issuecomment-300739505

**Comment by nag0538** [comment]
same issue:)

any way i used following code for temp solution.Hope this will resolve in feature updates.

//ngif
visible: boolean = true;

place this in your btn click action

 this.visible = false;
setTimeout(() => this.visible = true, 0);

**Comment by kenisteward** [comment]
@kamran-pervaiz Make sure when you do the add it is using an IMMUTABLE object.  What I mean by that is when you add the data you should not use

``
data.push({});
``

you should instead use

``
data = data.concat({});
``
or 

``
data = [...data, {}];
``

This is explained under managing data
https://www.primefaces.org/primeng/#/datatable
``
DataTable uses setter based checking to realize if the underlying data has changed to update the UI so your data changes such as adding or removing a record should always create a new array reference instead of manipulating an existing array. For example, use slice instead of splice when removing an item or use spread operator instead of push method when adding an item.
``

The reason is all the components use ChangeDetectorStrategy.OnPush in order to not update too many components when adding or removing elements.

**Comment by kamran-pervaiz** [comment]
@kenisteward I did use spread operator and it was not working. I will try to concat and see if it fixes the problem.

**Comment by cagataycivici** [comment]
https://github.com/primefaces/primeng/issues/3227 will also help.

**Comment by devevderyadav** [comment]
Hi guys, I ran into the same issue, till yesterday  data.push({}) was working BUT today it jus don't add into table view when new data is added.  Any help is much appreciated

**Comment by devevderyadav** [comment]
[immutable]="false" works with  4.1.0.rc3 :)

**Comment by chanakyanet** [comment]
@devevderyadav thanks for the soln, this fixed my problem with IE browser
