### ISSUE TITLE
[Feat] Improve theming with SCSS default properties

### ISSUE THREAD

**Issue by Luchillo** [primefaces/primeng#308]
I will use the Ionic 2 approach as example since is the one i took this out.

In Ionic 2 you can define in SCSS certain variables above the import of the Ionic styles, this variables are used in the styles with the `!default` flag? option? idk how is it called.

This approach let the styles being override without touching the SCSS code by just overriding the variables above the SCSS import, thus allowing for a lot of freedom as much as the library owner allows to customise.

This would be a great feature since it would allow to pick a theme and then tweak a bit the styles to your specific app/use case, refer to: [sass-default](https://robots.thoughtbot.com/sass-default)

**Comment by cagataycivici** [comment]
Thanks, we'll consider.

**Comment by koen-serneels** [comment]
Hi. Is there any news if this request will be implemented and if so the roadmap?
We are facing the same issue as that altering the theme comes down to (correct me if I'm wrong) re-defining styles. The issue is that if the Primefaces team would make changes in newer releases we will always have to manually diff to see if there are differences and import them manually. Imho it would already be helpful if the themes would be presented in SCSS to start with. Adding properties for customization are an added bonus. Compare it to what the Vaadin team does for their themes

**Comment by Luchillo** [comment]
I would also like to have this feature in the near future.

About your use case, i feel like you're directly editing the css provided by the `primeng` package, am i right?

In my case i don't alter the teme exactly because your issue, instead i override the theme which in most cases it comes down to redefining those properties with an `!important` property, and before anyone yell at me, yes i know that's a bad design, but is better that editing the original theme and in each update having to scan changes, make edits or god knows what other witchery can be done.

**Comment by cagataycivici** [comment]
We'd like to avoid rewrite of all themes so decided to keep them as they are and keep using sass on premium themes only so idea is community themes use css and premium themes use scss.

**Comment by Luchillo** [comment]
@cagataycivici Wow, i guess those premium SCSS themes need's some appeal to sell huh?

@koen-serneels Did i nailed it with you editing the css inside the npm module? i think my approach would be better for your case too, still making diffs?
