### ISSUE TITLE
AOT compilation issues

### ISSUE THREAD

**Issue by cagataycivici** [primefaces/primeng#3122]
A couple of components fail under AOT compilation.

**Comment by andregs** [comment]
When fixing this, please also consider declaring modules and components on different files, so we can customize the components without breaking AoT compilation.

**Example:**

I have to customize the data table paginator according to my project's needs, so I could simply override DataTableModule to declare my custom paginator, like this:

```ts
// the original (in primeng/src/app/components/datatable/datatable.ts)
@NgModule({
    imports: [CommonModule,SharedModule,PaginatorModule,FormsModule],
    exports: [DataTable,SharedModule],
    declarations: [DataTable,DTRadioButton,DTCheckbox,ColumnHeaders,ColumnFooters,TableBody,ScrollableView,RowExpansionLoader]
})
export class DataTableModule { }

// my-custom-datatable.module.ts
@NgModule({
  imports: [CommonModule, SharedModule, FormsModule],
  exports: [DataTable, SharedModule],
  declarations: [DataTable, DTRadioButton, DTCheckbox, ColumnHeaders, ColumnFooters, TableBody, ScrollableView, RowExpansionLoader,
    MyCustomPaginator, // <- my single change
  ],
})
export class MyCustomDataTableModule { }
```

However, since primeng declares both `DataTable` component and `DataTableModule` in the same file, I can't AoT compile `MyCustomDataTableModule`. Here's the error I get:

```
Error: Type DataTable in .../datatable/datatable.d.ts is part of the declarations of 2 modules: DataTableModule in .../datatable/datatable.d.ts and MyCustomDataTableModule in .../table/my-custom-datatable.module.ts!
```

The thing is: I never imported `DataTableModule` in my project. AoT compiler finds it because it's declared in the same file where `DataTable` component is declared. So by removing it from that file, the error is gone.

**Comment by cagataycivici** [comment]
This is fixed, to only import a specific module, don't import from primeng/primeg but from;

//import {ComponentModule} from 'primeng/components/componentname/componentname';
//import {InterfaceName} from 'primeng/common/api';

import {AccordionModule} from 'primeng/components/accordion/accordion';
import {MenuItem} from 'primeng/components/common/api';

More info at;

https://www.primefaces.org/primeng/#/setup

**Comment by andregs** [comment]
Unfortunately, that's exactly what I'm doing. Look:

```ts
import {
  DataTable,
  DTRadioButton,
  DTCheckbox,
  ColumnHeaders,
  ColumnFooters,
  TableBody,
  ScrollableView,
  RowExpansionLoader,
} from 'primeng/components/datatable/datatable';
```

But this import line also brings `DataTableModule` into the context of AoT compilation, since it's present into the `datatable.metadata.json` file. In fact, if I remove the references to `DataTableModule` from `datatable.metadata.json`, the AoT compilation works successfully.

**Comment by andregs** [comment]
What I'm trying to say is: the only way I know to avoid that error when creating my own modules is to import only prime's components without importing prime's modules. And that's impossible because prime declares both on the same file.

**Comment by Tahiche** [comment]
Did you find a solution for this?. I´m in the exact same situation trying to customize the table paginator. It fails under AOT complaining about components being declared twice eventhough I removed every ref to "primeng/primeg" (which took a while ;( )

If i do this...

```
@NgModule({
    imports: [
         TableModule,
  ...],
    declarations: [
      MyCustomOverridePaginator
]
```
p-table is not aware of my component...

But i try to declare PrimeNg´s components (plus my own)....

```
    declarations: [
         ...primengDeclared, // this includes Table, and so on.... 
        MyCustomOverridePaginator

    ],
    exports: [
     ...primengExported, // this includes Table, and so on.... 
    MyCustomOverridePaginator]
```
It complains about the components being declared twice...
