### ISSUE TITLE
contributing

### ISSUE THREAD

**Issue by cghislai** [primefaces/primeng#315]
I cannot build master and there is no instruction anymore.

Errors seem to come from commit 77cdcafb6b2b6f956246eb6288fdb07f99108b70 in which angular dependencies have been removed/moved.
Should the wiki be updated?

**Comment by cagataycivici** [comment]
Yes, I'll update the wiki now.

**Comment by cagataycivici** [comment]
I quickly came up with this, please see;

https://github.com/primefaces/primeng/wiki/Building-From-Source

**Comment by harilal** [comment]
@cagataycivici i would like to contribute to primeng. Since we are using primeng for projects i think i could help in adding some features. I already forked and cloned the repo and my setup is working. My doubts are;
1. are we working on a single branch "master"
2. Do i need to create any hotfix or branch?
