### ISSUE TITLE
Life property for messages

### ISSUE THREAD

**Issue by kamran-pervaiz** [primefaces/primeng#3232]
is there a way we can have fade effect for p-messages? I am using it to display errors and it stays there until user clicks cross. it would be great if there is alternate approach to fade it?

**Comment by kamran-pervaiz** [comment]
any update on it @cagataycivici

**Comment by TheParad0X** [comment]
This feature would be nice to have.

**Comment by andi-dev** [comment]
Is there still a plan to implement this eventually? I think it is really odd that this works with toasts but not with messages.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,

**Comment by BallisticPain** [comment]
I do not understand why you have closed this ticket and not checked your own documentation... however, let me go ahead and confirm for you, this has not been implemented, and if so it isn't included in your documentation. :( 

I do not understand why it isn't implemented, especially considering `p-toast` has this functionality and `p-messages` and `p-toast` seem to use the same underlying service?

Would love to see this implemented. I'm using other code bits from other component frameworks because they have this functionality.
