### ISSUE TITLE
Datatable virtual scrolling doesn't show data while using high number of total records

### ISSUE THREAD

**Issue by N1MA** [primefaces/primeng#3276]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**

http://plnkr.co/edit/ZPYbjWMTdnNTGlrMMmhY?p=preview

**Current behavior**
virtual scrolling in datatable doesn't show data after scrolling when total records number is big (in this case 1.5 million records)

**Expected behavior**
it's expected that table doesn't go completely white after scrolling   

**Minimal reproduction of the problem with instructions**

http://plnkr.co/edit/ZPYbjWMTdnNTGlrMMmhY?p=preview

**What is the motivation / use case for changing the behavior?**

can't use datatable's virtual scrolling for high number of data

**Please tell us about your environment:**

Operating system: Windows 10 (creators edition)
IDE: Webstorm 2017.1.4
package manager: npm

* **Angular version:** 2.0.X

Angular version: @4.0.X

* **PrimeNG version:** 2.0.X

PrimeNG version: @4.1.0-rc.2

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 Browser: Chrome  59.0
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Language:  TypeScript 2.0.3

* **Node (for AoT issues):** `node --version` =

**Comment by cagataycivici** [comment]
I think there is a dom limit on the virtual height so 1.5 million is too much for the browser, we'll reopen if we can find a workaround.

**Comment by lukaszbachman** [comment]
Hello,

I'd like to vote for reopening of this issue. We are using p-table in our NGv8 project to display large data sets in various places of the app, and current limit on the maximum number of rows is hurting us badly. Other then that - this component is really solid (thanks!) and we would like to keep using it across the entire app. I think there is an elegant solution to this, so please keep reading.

So first of all - current behavior is not well documented and it caught us by a surprise at the possible worst timing (just before a release). So at the minimum I'd like to ask for an update in docs where you say that the maximum amount of virtual rows which ptable can display is dependent on the virtual row height. You should also mention that this will vary across browsers (Chrome & Safari are outperforming FireFox and IE here).

Now, by trial and error, we determined that with `virtualRowHeight` being equal to `34px`, Firefox can render at most 526344 entries. Make it one more and the entire table is completely gone. That is because the height of `div.ui-table-virtual-scroller` is set to 17895700px, which apparently is too much for FireFox to chew. If we reduce it by a few pixels, then the table will reappear! Don't focus on these numbers too much, they don't really matter. What matters is that the height of the scroller is very big and it is interfering with the table.

I think there are two possible solutions to this problem:

1. Extend the public API of p-table so that parent components (or services) can control its scrolling position, ex: `table.setFirstVisibleRow(0)` or `[(visibleRow)]='myRow'`. Then we should also have the ability to conditionally add a scrollbar, ex. `[showScrollbar]='false'`. This would allow me to create my own div which acts as an external scrollbar and I could configure its behavior according to my likening.

2. The second option is to fine-tune the scrollbar itself. When the dataset grows big, scrollbar's knob would be too small, so a common practice in tables which support virtual scrolling is to add a max-height on the div which controls the scrollbar and set it to some safe value respected by all browsers. That of course means, that a single click on a UP or DOWN arrow (in the scrollbar) does not shift the view by one element, but proportionally to the amount of rows stored in table. Example: 

- if (rowsCount < 500k) -> one click means scrolling by one element (current behavior)
- if (rows > 500k) -> one click means scrolling by two or more elements

I hope you will consider this addition to the otherwise perfect p-table component. Thank you!

**Comment by lukaszbachman** [comment]
Any update on this? I recently upgraded PrimeNG to V10 and noticed issues on FireFox with as "little" as 530k items.
