### ISSUE TITLE
DataTable: Sorting with custom function

### ISSUE THREAD

**Issue by mecheri** [primefaces/primeng#3464]
Hi,
Sorting single columns with custom function not working since 4.0.0.
Can you fix it please.

Thanks

**Comment by adrianabreu** [comment]
Working fine on 4.1.2. 

Did you set the sort type to 'custom' ?

**Comment by mecheri** [comment]
Hi,
Thanks for reply
Yes, i set the sort type to 'custom', maybe it is the syntax that is not good (can you show me an example)
Or the problem is related to ng CLI

**Comment by cagataycivici** [comment]
Provide a plunkr please;

http://plnkr.co/edit/Qi2Nw2imLpDUF8NJinYw?p=preview

**Comment by dolf-o-matric** [comment]
Same problem here since PrimeNG 4:
http://plnkr.co/edit/R1CA3nLbBtBgPGIB9X3H

**Comment by adrianabreu** [comment]
The function is being called properly, the error resides in that you need to change the data object reference in order to trigger the change detector. It can be as easy as adding: 

`this.data = [...this.data]` 

At the end of your sortByName function. 

You can check the code working here @dolf-o-matric 
http://plnkr.co/edit/vccp8YqlEY2dMuktNxrL?p=preview

**Comment by dolf-o-matric** [comment]
Thanks a lot, it's working! :)

**Comment by tL4302** [comment]
One of the very few working examples of datatable custom sorting that I could find. Thanks for posting.

**Comment by mecheri** [comment]
Thanks a lot
