### ISSUE TITLE
DataTable with *ngIf

### ISSUE THREAD

**Issue by vitalii-tsybran** [primefaces/primeng#373]
I'm having troubles with making the DataTable work correct inside *ngIf. What I'm trying to do is simply display "loading" text while data is being fetched from the server and display the table when data arrives. Here is my template.

`<div *ngIf="! loading">
  <p-dataTable  [value]="leagues">
    <header>
      Total records: {{totalRecords}}
      <div class="btn-group pull-right" role="group" aria-label="...">
      <button (click)="reloadLeagues.emit()" type="button" class="btn btn-default">
        <i [class.fa-spin]="loading" class="fa fa-refresh" aria-hidden="true"></i>
      </button>
      <button (click)="addLeague.emit()" type="button" class="btn btn-default">
        <i class="fa fa-plus-circle" aria-hidden="true"></i>
      </button>
      <button type="button" class="btn btn-default">Right</button>
    </div>
    </header>
    <p-column field="id" header="ID"></p-column>
    <p-column field="iid" header="IID"></p-column>
    <p-column field="name" header="Name"></p-column>
    <p-column field="actions" header="Actions">
      <template let-league="rowData">
        <a class="btn btn-default" [routerLink]="['../LeaguesDetails', {id: league.id}]">Details</a>
      </template>
    </p-column>
  </p-dataTable>
</div>`

(Sorry, couldn't make the snippet look nice here for some reason. )

The problem is that when data is loaded, the table only renders header without the actual entries. The "total records" number is also loaded from serever, so the data is surely present on this stage.

![datatable-issue](https://cloud.githubusercontent.com/assets/6648912/15353397/87ccc3a6-1cf1-11e6-9416-9578ff0cf099.png)

I couldn't find any clues on this in docs and this looks like a bug to me.

**Comment by pdudits** [comment]
If you look at your DOM, do you have empty <tr>s in the TBODY of the component?

If yes, you might be using non-default change detection strategy up your component tree. The somehow mislabeled fix for this issue is in #379, specifically in commit 9f884ca6c2f.

The point is, that component gets its column list first after it is fully initialized. With default change detection strategy, this triggers another tick and component is fully redrawn. If you've got OnPush in any of you parent components, the change detection is skipped, because there was no event originating in the component, it was just observable being delivered.

**Comment by cagataycivici** [comment]
Let's track at 405
