### ISSUE TITLE
p-calendar: restricting  selectable dates function does not respect the time

### ISSUE THREAD

**Issue by mmlitvin** [primefaces/primeng#3894]
Plunkr Case (Bug Reports)
http://plnkr.co/edit/vUgX8KyJhNneWyVIndkW

Current behavior
User needs to provide a range of dates (in a form of timestamps) to search database 
p-calendar provides minDate and maxDate options to restrict dates to valid range. 
However timepicker that is intergrated into p-calendar does not utilize  minDate and maxDate.  As a result there are 2 bugs:
Use case 1:
1. Select date in From field
2. Click on the calendar widget for To field
3. Select the same date and select time earlier than the on in From field

Use case 2:
1. Select tomorrow as a date in From widget 
2. Click on the calendar widget for To field. All days prior to tomorrow are greyed out
3. Without selecting a date go ahead and click on the time. That will set your value to today's date with selected time even thought today is greyed out

Please tell us about your environment:
PrimeNG version: primeng@4.1.0
Browser: Chrome

**Comment by KatzeKahn** [comment]
Some additional notes on that issue:

I experienced the following buggy behavior: For example, you set minDate to"10h:00m" (defaultTime set to the same).

- clicking on the calendar the time field appears with "10:00" (good)
- clicking on the hour arrow down, nothing happens because minDate == defaultTime (good)
- then clicking hour arrow up, it increments the hour correctly (good)
- but when it comes to the next step after '23:00', it sets '00:00' (bad, '23:00' should be the last step)
- if hour time is wrongly '00:00' now, it's not possible to decrement the time again, it stays at '00:00' when clicking the hour arrow down again (bad)

I just explained for hours but I assume the issue also occurs for minutes and millseconds arrows.

_I'm using PrimeNG version: primeng@5.2.0 on Chrome_

**Comment by rfmatos** [comment]
I'm using PrimeNG version: primeng@5.2.6 on Chrome

I have also noted weird behavior with the time controls when setting minDate on a p-calendar.  Not 100% sure it's related to this issue, but I will note my issue here as well.  I am working on creating a plunk to reproduce it, but was having some issues getting the plunk to work.  Once I get that working I will submit a more detailed report, but here's what I am seeing.  

In our use case we have two p-calendar controls to represent a start and end date.  At the component init, the bound variable set to minDate for the start date p-calendar is set to the current date/time and the one for minDate for the end date p-calendar is set to current date/time plus one day.

On changing the value of the start date, we update the bound variable set to minDate for the end date control to be the current start date plus one day.

If you then try to interact with the time controls on the end date p-calendar control we have weird behavior similar to what's reported above but I have also seen other things intermittently like the time controls being all greyed out and not responding to clicks, but then randomly responding to clicks despite still being greyed out.  Sometimes some are greyed out but others not. I have also seen the hour change to 24hr format randomly while clicking the minutes and also have seen the calendar increment the selected day as I incremented the minutes up or down.

So far the only thing that seems to stop this weird behavior is if I stop updating minDate on the end date control dynamically when the start date value changes.

**Comment by yigitfindikli** [comment]
I’m unable to replicate with the latest PrimeNG. If the issue still persists with the new version please create a new issue with our stackblitz template.
