### ISSUE TITLE
Slider Component

### ISSUE THREAD

**Issue by cagataycivici** [primefaces/primeng#39]

**Comment by zamrokk** [comment]
Hi Cagatay,

It would be really great to display the scale over the slider. Like this :

1   2   3   4   5
(    o              )

As it we can see where to click and what is the value pointed

Thanks

You do really a good job

**Comment by cagataycivici** [comment]
Thank you, is there an example slider somewhere that has a scale?

**Comment by TekSiDoT** [comment]
I see several possible implementations:
![](https://infoactive.co/data-design/images/sections/03/likert-vs-slider.png)

![](https://manual.limesurvey.org/images/6/68/Button_slider.jpg)

**Comment by zamrokk** [comment]
Slider Scale is great  :+1:

**Comment by cagataycivici** [comment]
Thank you, there is also;

http://simeydotme.github.io/jQuery-ui-Slider-Pips/

**Comment by TekSiDoT** [comment]
Yep, that looks pretty sweet.

**Comment by cagataycivici** [comment]
Let's track at https://github.com/primefaces/primeng/issues/118

**Comment by Glenndejaeger** [comment]
I prefer to have a label (= fixed tooltip) above the handle with the current selected value in it (cfr option 1 of slider scale) because if you use the slider within a small component (eg. search facets of 300px wide), the scale cannot be displayed, unless you only can select 3 values in range or so.

It would be great if both solutions (fixed scale + label above handle) would be implemented and users can select which solution they want to use via attributes on the component
