### ISSUE TITLE
MessageService - overwriting previous message

### ISSUE THREAD

**Issue by sgentile** [primefaces/primeng#3931]
When using the MessageService from multiple places in my application, when I call messageService.add it doesn't show the messages under the current, instead it replaces the current message.

ie. one component throws an error, then another throws an error - the first message is overwritten and quickly flashes - vs. showing them in a list and then fading away.

Looking at the code - the messageSource is overwriting the message with next - shouldn't these be an array of messages that are added ?

**Comment by UrzaUrza** [comment]
Hello, 
I added a similar issue two weeks ago with a work around similar to what you suggest. https://github.com/primefaces/primeng/issues/3784

**Comment by pstawik** [comment]
Hi All,
I want to work with MessageService, but I don't understand its description provided by PrimeTeam:
"MessageService alternative does not require a value binding to an array. In order to use this service, import the class and define it as a provider in a component higher up in the component tree such as application instance itself so that descandant components can have it injected."
For example, in my application I have root AppComponent and other AComponent, BComponent, CComponent, whose invoke AService, BService and CService. Services can return errorMsg which I want present on the screen.
How can I configure MessageService to present errorMsg without code duplication?
Can I include <p-messages [(value)]="msgs"></p-messages> only in AppComponent html template and pass to it errorMsg from AComponent, BComponent, CComponent?
The example from showcase works in my app, but it is very simple: MessageService is invoking in the same component which have p-messages in its template.
Do you know where can I find some example with MessageService. Maybe you can help me? 
Regards
Piotr

**Comment by cagataycivici** [comment]
Duplicate https://github.com/primefaces/primeng/issues/3784
