### ISSUE TITLE
How to extend the PrimeNG component

### ISSUE THREAD

**Issue by chawla0410** [primefaces/primeng#3993]
I need to extend datatable module of PrimeNG.Is there any way to extend this component to incorporate custom features?How to add custom changes to it?

**Comment by machfalcon** [comment]
I also need this ability.  It seems like the way the columns and column templates are pulled in through @ContentChildren does not allow extending the datatable (as far as I can tell, Angular doesn't seem to be passing the @ContentChildren through to the extended component).  Would it be possible to pass the columns and column templates as inputs so that my extended datatable can pass them in?

**Comment by cagataycivici** [comment]
Please use forum for questions.
