### ISSUE TITLE
Floating labels for autocomplete component

### ISSUE THREAD

**Issue by ccasallas** [primefaces/primeng#4339]
I'm submitting a:
```
[ ] bug report
[x] feature request
[ ] support request
```
I create a separated ticket to track floating labels enhancement on autocomplete component according to  #4011  (at least in ultima theme).

**Comment by VNYoeri** [comment]
@ccasallas, I also created a separate issue: #4319, with a plunkr case. The plunkr case confirms that the current behaviour is not limited to Ultima, it uses Omega and still behaves the same way.... Bug report or new feature request is the only difference :)

**Comment by ccasallas** [comment]
@VNYoeri I'm not sure if omega theme follow the material design guidelines, currently, does any component support floating labels?

**Comment by VNYoeri** [comment]
@ccasallas using Ultima, I got the datepicker working with floating labels out-of-the-box. Can't prove it right now (mobile and all that), but I'll get back to this asap.

**Comment by VNYoeri** [comment]
@ccasallas alright, so I got it working with a simple date-component. Codewise, in Ultima, it's the same as any `<input>` with a floating label, but instead of using `<input>` you just have to use the calendar-selector `<p-calendar>`.  
Plunkr is failing me at the moment, so have a GIF as proof :)
![p-calendar-autocomplete-works](https://user-images.githubusercontent.com/28541690/32364931-ee40fe92-c077-11e7-929a-348ce327a0ca.gif)

The template-code:
`<span class="md-inputfield">`
  `<p-calendar showIcon="true" id="someDate"></p-calendar>`
  ` <label for="someDate">Have a label</label>`
`</span>`

**Comment by cagataycivici** [comment]
Duplicate  #4319
