### ISSUE TITLE
AutoZIndex and CloseOnEscape problems

### ISSUE THREAD

**Issue by AndreaBarbasso** [primefaces/primeng#4394]
**I'm submitting a ...**
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**

http://plnkr.co/edit/C4jKMlXaxZ8BGSkXvbvP?p=preview

**Current behavior**

Since `DomHandler `is a singleton and has a shared zindex attribute, this causes problems with dialogs that could be closed by hitting the Escape button. For example, if `blockUI` or any other element with autoZIndex is called while a dialog is open, you can't close that dialog anymore with Escape, unless you click on it before trying.

**Expected behavior**

`DomHandler.zindex` should not be increased for elements that will go away on themselves. Maybe using a custom attribute that does not increase `DomHandler.zindex` (but simply creates the new element with `z-index = DomHandler.zindex + 1`) could be enough.

**What is the motivation / use case for changing the behavior?**

In my project I'm using a few dialogs that call my back end on show. While there is a back end call unanswered, I use blockUI to avoid user input. Someone could open a dialog and try to close it right away with the Escape button, with no success. Right now I'm setting blockUI's z-index manually without autoZIndex to avoid any problem, but I think some more documentation on autoZIndex or a simple fix should be added.

* **Angular version:** 4.4.6
* **PrimeNG version:** 4.3.0
 
* **Language:** TypeScript

**Comment by busucu** [comment]
Hello,

I have a similar problem. Actually mine is more like https://github.com/primefaces/primeng/issues/7407 but since it is closed, I wanted to post here. Once the option list of a dropdown in a dialog is shown, dialog cannot be closed with escape key. 

I am not very knowledgeable about Angular, but I tried adding a few lines and it worked:

First is [here](https://github.com/primefaces/primeng/blob/aee61bc2f1c0646b8f24413151e19578b01ba768/src/app/components/dropdown/dropdown.ts#L536)

    onOverlayAnimationStart(event: AnimationEvent) {
        switch (event.toState) {
            ...
            break;

            case 'void':
                this.onHide.emit(event);
                this.onOverlayHide();
                --DomHandler.zindex;  // << added this line
            break;
        }
    }

and second is [here](https://github.com/primefaces/primeng/blob/aee61bc2f1c0646b8f24413151e19578b01ba768/src/app/components/dropdown/dropdown.ts#L748)

    onKeydown(event: KeyboardEvent, search: boolean) {
        ...
        switch(event.which) {
            ...
            //escape and tab
            case 27:
            case 9:
                if (this.overlayVisible) { // << added condition
                  this.hide();
                  event.stopPropagation();  // << added this line
                }
            break;
            ...
        }
    }

Of course this should be applied to all other similar components like calendar, multiselect, etc. If this is not an acceptable way, could someone explain why? If it is acceptable, I would love to see it merged :)

**Comment by denny99** [comment]
Yeah. I have the same issue as busucu. The Z-Index is always increased when new overlays open, but never decreased again.

Right now im using some old primeng code scanning for z-index +-10. But thats not a great solution

So this line from the dialog fails as soon as another overlay appears. Even a toast

`if (parseInt(this.container.style.zIndex) === (DomHandler.zindex + this.baseZIndex)) {`

**Comment by ModestinoAndre** [comment]
This still applies to the latest Version of PrimeNG 13.0.0

**Comment by cetincakiroglu** [comment]
Fixed in the current version.
