### ISSUE TITLE
Calendar ISO date issue still remain with the latest version

### ISSUE THREAD

**Issue by szanellato93** [primefaces/primeng#4421]
this issue still remain in the latest version:

https://github.com/primefaces/primeng/issues/1895

i use reactive form if can help.

**Comment by cagataycivici** [comment]
With 5.0.0-RC?

**Comment by serlopez46** [comment]
Is there any way we can use Date objects as input value (dateType) but be able to use an ISO 8601 string to set the value?
We get dates as ISO 8601 strings in JSON from the server and it would be very helpful to be able to set that data as the form control value.
**What we want to do:**
dateControl.setValue("2018-01-09T23:00:00.000Z")
**What we want to see:**
![image](https://user-images.githubusercontent.com/33145561/34777760-a6877732-f61b-11e7-9246-a96d3a1a21a1.png)

I added a plnkr as example:
http://plnkr.co/edit/tECz5ldrJeqj7voWr3Ta?p=preview

Maybe convert the value to a Date object if value is a string, then when we stringify the formGroup to JSON in order to send the data to a server it will be converted to ISO 8601.

**Comment by AtzederSerbe** [comment]
The issue is still present in v13.0.0. It would be really neat if this could be fixed. ISO 8601 is the gold standard in date communication

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
