### ISSUE TITLE
Calendar picking different times with same configuration.

### ISSUE THREAD

**Issue by SchneMa** [primefaces/primeng#4468]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
http://plnkr.co/edit/CcS7JJjawAcbrPyVRfk5?p=preview

**Current behavior**

two Calender pcik different times even if they are configured identical

**Expected behavior**

both get the same time 
**Minimal reproduction of the problem with instructions**
just check the plunker and select both dates (star and endDate)
http://plnkr.co/edit/CcS7JJjawAcbrPyVRfk5?p=preview

**What is the motivation / use case for changing the behavior?**

PrimeNG: 5.0.0-rc.0
Angular 5.0.2

I'm unable to find out why my second Calender is picking Time 00:00 instead of the current time like the first Calendar does. 
Even if I'm just picking a Date and not specific time shouldn't there be such a different. 
Seems a bit confusing to me.

Maybe there should be an attribute to define a default time when just picking Dates?

**Comment by AndreaBarbasso** [comment]
Both calendars actually behave the same, just try picking today's date in both.

If you pick today's date, I think your variable `todayDate` is used, and since it's a `new Date()` object, it has both date and time. If you pick it again on the second calendar, `startDate` is used, which is `todayDate` itself, and so has the time again.

Otherwise, a new Date object is created, given the day you selected and no time whatsoever (since there is no timePicker here).

I haven't read the code since I'm quite in a hurry, but that's what I recall from my previous experience on PrimeNG's calendar!

**Comment by SchneMa** [comment]
@AndreaBarbasso yeah you're right. So it seems like this isn't any PrimeNG Error or Bug rather a self produzed one. going to close this issue.

Thanks a lot!
