### ISSUE TITLE
SelectButton does not support OnPush ChangeDetection

### ISSUE THREAD

**Issue by hanouard** [primefaces/primeng#4520]
**I'm submitting a ...**  (check one with "x")
```
[ X ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

Im using p-selectButton in a component that have OnPush detection strategy.

On component init, i update the options and the selected value with data fetched via rest web service.

After manually marking the component for check: `this.changeDetectorRef.markForCheck()`, the options are updated but not the selected value.

**Plunkr Case (Bug Reports)**
http://plnkr.co/edit/1Dqj1sZWPmIGWKu9FNm5?p=preview

Im using angular 4.0.x with primeNG 4.3.0

**Comment by pdhamija** [comment]
Hello cagataycivici, 
We are using Angular 4.3.x and primeNg 4.2.x. We really need this fix. But it seems that you have added this in 5.1.x? To use that version, we will have to move to Angular 5, which we cannot, since we have other compatibility issues and restrictions. 
Can you please also put this fix in a primeNg version (4.x) that works with Angular 4. Please! 
Thank you
