### ISSUE TITLE
p-colorPicker: How to change/reset the default color?

### ISSUE THREAD

**Issue by YichenMao** [primefaces/primeng#4556]
Is there a way to change/reset the default color in the p-colorPicker? The default one in the typescript file is always black.

**Comment by cyberrranger** [comment]
use [(ngModel)]="color"

and color: String = "your color"

**Comment by YichenMao** [comment]
thank you very much for the reply~ 
I used this way as well, it doesn't work because I set color to 'black' instead of '#000'.
it works now~

**Comment by cyberrranger** [comment]
yes, the default format ist "hex", and black in hex ist #000

https://www.primefaces.org/primeng/#/colorpicker
https://www.w3schools.com/colors/colors_hexadecimal.asp

if your ticket is answer, pls close this issue.

**Comment by bernstar** [comment]
i had the same problem. I solved it with binding the ngModel to a custom function:

`<p-colorPicker [ngModel]="getSafeColor(myColorfield)" (onChange)="onChangeData($event)">`

and then

```
getSafeColor(color: string) : string
{
  return (color != undefined) ? color : "#000";
}
```

However, you'll then need to handle data changes on your own and cant use two-way binding.

**Comment by alex-ninenine** [comment]
I solved handling and visualizing undefined by using the photoshop visual (white box with red slash). It felt a bit more intuitive then having red, since our preferred behaviour when undefined is for the system to later select the color by other visual cues. Here is the CSS I used to get this working:

```
<p-colorPicker [ngClass]="(!color) ? 'undef-color-colorpicker' : 'def-color-colorpicker'"
                         [(ngModel)]="color"
                         appendTo="body"></p-colorPicker>
```

with

```
.undef-color-colorpicker {
      .p-colorpicker-preview {
        background: white linear-gradient(to top left,
        rgba(0, 0, 0, 0) 0%,
        rgba(0, 0, 0, 0) calc(50% - 2px),
        rgba(255, 0, 0, 1) 50%,
        rgba(0, 0, 0, 0) calc(50% + 2px),
        rgba(0, 0, 0, 0) 100%) !important;
      }
    }
```
![image](https://user-images.githubusercontent.com/59851258/185507291-e4308052-495f-43dd-a4c1-1e84b36cbec4.png)
![image](https://user-images.githubusercontent.com/59851258/185507411-b50b6172-d054-4760-8b43-2f3fea727ec4.png)

**Comment by Tazaf** [comment]
@alex-ninenine Awesome! This is a very clever (and simple) way of handling this use case.

In fact, that should probably be the default for this component. You should definitily propose this change through a PR 👍
