### ISSUE TITLE
Datatable row expansion does not work when ng-content used in ng-template

### ISSUE THREAD

**Issue by davidzick** [primefaces/primeng#4573]
### There is no guarantee in receiving a response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**

http://plnkr.co/edit/L1lQ5HoQjxd3baLYz5CA?p=preview

**Current behavior**
Currently when you expand a row and then expand a row above, the datatable fails to properly collapse the originally expanded row and you are left in a state where you cannot expand any other row.

**Expected behavior**
To be able to expand any given row in any order.

**Minimal reproduction of the problem with instructions**

- Click the button with the label "PrimeNG" to populate the table with 4 rows
- Expand the second row
- Expand the first row
You now are in a state where you cannot expand any other row. You'll also notice the text from the second row is gone but the arrow was not properly collapsed (arrow is still down).

**Misc Comment**
This problem only occurs when an ng-content is used inside an ng-template (see datatable definition in app/app.carwrapper.html).

**Please tell us about your environment:**

* **Angular version:** 4.1.0 (There is a similar issue at 4.4.4 where when you expand a row above the content of the new row is not displayed)

* **PrimeNG version:** 4.1.0 (this is still an issue as of 5.0.2)

* **Browser:** Chrome 62.0.3202.94 64-bit
 
* **Language:** TypeScript 2.3.4

**Comment by cagataycivici** [comment]
I don't think it is valid to use ng-content inside ng-template at all.

**Comment by ryanwawr** [comment]
I think this is a valid issue. If you change the version of primeng in the plunk to 4.1.0-rc.2 (link below), everything works correctly.

http://plnkr.co/edit/qKr1apIOG2NKqHJqFnTp?p=preview

That seems to indicate that the problem is not having an ng-content element inside an ng-template, but rather, something that changed between primeng 4.1.0 RC2 and RC3. The error I'm seeing in my project occurs when this.view.destroy() is called inside ngOnDestroy in datatable.ts. This line was added between the two aforementioned releases, so I'm guessing it may be the source of the problem.

The specific error message I get is:

```ERROR DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.```

Would appreciate if this issue could be reopened and addressed.
