### ISSUE TITLE
NPM type script compilation errors

### ISSUE THREAD

**Issue by felixpes** [primefaces/primeng#484]
Hi,

I've downloaded the project.
Executed:
**npm install
tsc**

and getting compilation errors (please see attached file)

Can you please advise?

[tsc.txt](https://github.com/primefaces/primeng/files/314110/tsc.txt)

**Comment by fooflare** [comment]
Hi,
that is because package.json is in distribution mode by default in the repo. Here you can find the explanation about how to build from source: https://github.com/primefaces/primeng/wiki/Building-From-Source

In the package.json  of primeng-quickstart ( https://github.com/primefaces/primeng-quickstart/blob/master/package.json ) you can find a complete list of the dependencies, just remove the primeng dependency that is not needed.

**Comment by felixpes** [comment]
Thanks!
