### ISSUE TITLE
Assign value and display column to Input Dropdown should be dynamic.

### ISSUE THREAD

**Issue by nsksaisaravana** [primefaces/primeng#4879]
Like below I am not able to assign the value column and display column dynamically to the dropdown.

<select id="department"  name="department" [(ngmodle)]="department" class="form-control">
      <option *ngFor="let dept of department" [value]="dept.id">
                 {{dept.name}}
      </option>
</select>

**Comment by nsksaisaravana** [comment]
This should be like p-autocomplete field property, dropdown also should have field or label and value property.

**Comment by serlopez46** [comment]
Related to #4295 i guess. After 4.3.0 they added _optionLabel_ property to Dropdown, MultiSelect, Listbox and SelectButton when using an array of objects as options.
A new property _optionValue_ needs to be added to set a field from the selected object as value instead of the whole object (primary key comes to mind).
AutoComplete has the _field_ property to define which of the object fields to show from the suggestions array when using objects but still lacks a _valueField_ property to define the object's field to set as the value instead of the whole object.

**Comment by fplini** [comment]
Any news about an "optionValue"?

**Comment by cagataycivici** [comment]
#4295
