### ISSUE TITLE
Import TableModule not working 

### ISSUE THREAD

**Issue by GUEYEDSMF** [primefaces/primeng#4904]
Hello,
I've updated the primeng to the latest version (5.2.0-rc.1) to use the new TableModule  feature.
But i get the following error whem importing from app.module.ts file

**ERROR in src/app/app.module.ts(26,39): error TS2305: Module '"C:/@web/tontinapp/node_modules/primeng/primeng"' has no exported member 'TableModule'.**

What is going wrong with it. Even when cheking with node module i've found that the table module is here

**Comment by cagataycivici** [comment]
#4841

**Comment by jjayaraman** [comment]
import { TableModule } from 'primeng/table';
gets this error.. I tried with "primeng": "^5.2.0-rc.2" and 5.0.2 both same error.

ERROR in src/app/app.module.ts(16,29): error TS2307: Cannot find module 'primeng/table'.

**Comment by jjjackpeterson** [comment]
Hello All, 
I updated the latest version of primeng for Turbo table but I couldn't I get a compile-time error like 'has no exported member 'TableModule'.

**Comment by tvl83** [comment]
I am having a similar problem but it's saying MouseEvent is not defined.

`An unhandled exception occurred while processing the request.
NodeInvocationException: Prerendering failed because of error: ReferenceError: MouseEvent is not defined at ...\ClientApp\dist\main-server.js:48947:42`

this only happens when I import the TableModule even if I do not use it.

**Comment by RobertVogt** [comment]
This is still an issue since 2018 that has not been resolved??
I just upgraded to "primeng": "^12.0.0",
I am importing TableModule like import { TableModule } from 'primeng/table/table';
and getting the error, "Error: Module not found: Error: Can't resolve 'primeng/table/table'"
