### ISSUE TITLE
Accordion children elements receive keyboard focus even when the panel is collapsed

### ISSUE THREAD

**Issue by skhattry** [primefaces/primeng#4986]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
The children of a collapsed panel receive keyboard focus.

**Expected behavior**
Items present inside a collapsed accordion panel should not receive keyboard focus.

**Please tell us about your environment:**

* **Angular version:** 2.0.X
4.1.3

* **PrimeNG version:** 2.0.X
4.2.1

* **Browser:** 
Tested on Microsoft Edge and Mozilla Firefox

**Comment by peaverok** [comment]
As of 10.0.03 this is still not fixed. As a federal employee this is crucial for us because of accessibility reasons. This is not how accordions are supposed to function:

[https://www.w3.org/TR/2019/WD-wai-aria-practices-1.2-20191218/#accordion](https://www.w3.org/TR/2019/WD-wai-aria-practices-1.2-20191218/#accordion)

[https://www.w3.org/TR/2019/WD-wai-aria-practices-1.2-20191218/examples/accordion/accordion.html](https://www.w3.org/TR/2019/WD-wai-aria-practices-1.2-20191218/examples/accordion/accordion.html)

Use the example link above and you will see that it does not tab to items inside collapsed accordions.
