### ISSUE TITLE
Add showClear property to Dropdown

### ISSUE THREAD

**Issue by brian428** [primefaces/primeng#5285]
The new clear icon for Dropdown is a nice feature, but I don't think it should just automatically be applied. We have plenty of dropdowns where a value **must** be chosen, so the new clear icon is confusing and also breaks our logic (before the clear icon, there was no way for the user to select "nothing").

I would say make the clear functionality opt-in via an input property. Or, less desirable would be an input property to turn it off (but that would mean we'd have to manually go through and disable it throughout our code).

**Comment by ASK83** [comment]
I came across the similar issue (#5286) and making it optional would solve that one too.

**Comment by hughanderson4** [comment]
Agree with @brian428 that this should be opt-in.

In addition, please consider adding a css class to the parent ui-dropdown, whenever the child contains the clear icon (suggest `ui-dropdown-clearable`).  That way my app's css can adjust, or even hide, the presentation of the clear icon based on the parent class, instead of having to target all dropdowns.
