### ISSUE TITLE
Autoresize of TextArea does not resize correctly if width is 100 percent

### ISSUE THREAD

**Issue by bsivakiran** [primefaces/primeng#5342]
I'm submitting a issue with text area where the width is defined as 100%. There is already similar issue posted earlier, but as it was closed I am submitting a new issue here.
The issue which is posted earlier : issue number: #1439

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

https://plnkr.co/edit/FMiGoSmiBGPIIe4QDjpo?p=preview ( this is the plunker from previous ticket itself)

**Current behavior**
when ever we typed more data, or copy and paste lot of data, the text area is growing very rapidly. it is taking more space than expected. 

**Expected behavior**
it should take the space based on the content available.

* **Angular version:** 5.2.7

* **PrimeNG version:** 5.2.0

<img width="943" alt="text_area_issue_with_100 _width" src="https://user-images.githubusercontent.com/9642721/37386865-3f7aad70-2780-11e8-9194-97a67df1381a.PNG">

Thanks & Regards
sivakiran B

**Comment by npoirey** [comment]
As a temporary workaround, you can set [cols] to a higher value.
Right now the component add a line each time a line contains [cols] characters, so setting it to 100 instead of the default value of 20 will effectively divide the number of extra lines added by 5.

If you really need it to adapt to wildly different sizes, you probably could use elementRef to get the size of the element, then divide by whatever the median character width is, and bind this to [cols].

It does need a proper fix though.

**Comment by stephanie-dm** [comment]
Can you check with PrimeNG 6.1.5 or higher? It was fixed for us since that version.

**Comment by yigitfindikli** [comment]
fixed in https://github.com/primefaces/primeng/commit/f6c1ddc7f7be75cce98343645b1a22d8ab8dbcd1
