### ISSUE TITLE
p-table with selection and lazy

### ISSUE THREAD

**Issue by giorgiootto** [primefaces/primeng#5766]
p-table with selection and lazy don´t work.

**Comment by giorgiootto** [comment]
Version 5.2.7

**Comment by noamichael** [comment]
You have to give us more information about the error you're getting in order to determine if this is a bug or if you're misusing the component. Does the browser console have any information about the stack trace? Can you reproduce the bug in a plunkr?

**Comment by reneefeng** [comment]
@noamichael I have same issue.How can I get selectedFile in component? 

<p-tree [value]="files" selectionMode="single" [(selection)]="selectedFile" (onNodeExpand)="loadNode($event)"></p-tree>

ERROR TypeError: Cannot read property 'getCheckedNodes' of null;

**Comment by noamichael** [comment]
@reneefeng This bug is about the `<p-table/>` component. Your issue seems to be with the `<p-tree/>` component, so this bug is unrelated. Please open up another bug if you feel you found an error with the framework. Otherwise, if you're just having trouble configuring the component and need support, [open up a thread on the user forum.](https://forum.primefaces.org/viewforum.php?f=35&sid=b70b3e31c89a42a9ea7f8b2f08f7e36f) In either case, you'll have to share more code in order to receive help. You can use [this stackblitz as a template to demonstrate your issue.](https://stackblitz.com/github/primefaces/primeng-issue-template)

**Comment by cagataycivici** [comment]
Invalid issue ticket.
