### ISSUE TITLE
InputMask with ngModel not updating first character

### ISSUE THREAD

**Issue by andrevcf** [primefaces/primeng#587]
`<p-inputMask mask="(99) 9999[9]-9999" [unmask]="true" name="cel" [(ngModel)]="cel" required></p-inputMask>`

With the example above,  when i type 2 digits the model is updated with 1 digit only.
For example: I type "4", the model is blank. When I type "34" the model is now 3. When I type "342" then the model is 34. 
The backspace is working fine and updating correctly

**Comment by KonbOgonb** [comment]
Current implementation onKeyDown event as time moment when to fetch masked or unmasked value. This approach is wrong because when onKeyDown is fired value does not contain newly added character. So if we perform validation on the fly with each change of text, we are going to receive text without last character. Due to it we have this bug, when first character is not validated when it is entered. Possible solution could be to used key up event of <input> to flash text to value.

**Comment by ryanwawr** [comment]
Having the same problem. Would definitely like to see this fixed soon, since it's a fairly significant issue when trying to use p-inputMask with a search element.
