### ISSUE TITLE
feature request: Use angular i18n API

### ISSUE THREAD

**Issue by cghislai** [primefaces/primeng#5951]
Angular provides a way to obtain the locale with the LOCALE_ID injection token and localized components using the getLocale* functions of `@angular/common`.

It would be nice if primeng would make use of them so that the developers do not have to maintain locale data themselves. This would possibly reduce the bundle size as well. This angular API is still marked experimental though.

Im thinking of the calendar component but there might be others impacted.

**Comment by apiweb** [comment]
I think this is very interesting.
Because Angular, already built in methods to work with dates formats, month/week names, etc....
Example:
[getLocaleFirstDayOfWeek()](https://angular.io/api/common/getLocaleFirstDayOfWeek)
[getLocaleMonthNames()](https://angular.io/api/common/getLocaleMonthNames)
[getLocaleDateFormat()](https://angular.io/api/common/getLocaleDateFormat)
And much more, in [https://angular.io/api/common](https://angular.io/api/common)
Using this and another methods prevents developers from maintaining multiple variables only with the names of the months and weeks.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
