### ISSUE TITLE
TreeTable stop propigation

### ISSUE THREAD

**Issue by ShortBusKing** [primefaces/primeng#6024]
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35

Angular 4.4.7
PrimeNG 4.2.0 

Hello,
I would like to propose an additional flag within the treetable library which limits propagation to its child nodes. If this is already accomplished in later versions, please correct me.

In my application, I leverage the TreeTable to control the showing of different tabs of various documents. However, when a user selects a section with child element, it also selects and opens all its child elements. I need to select only the element itself and not its children as well.

My current solution is a simple hack which involves commenting out these propagate functions

`// this.propagateSelectionUp(node.parent, false);`

```
    TreeTable.prototype.propagateSelectionDown = function (node, select) {
        var index = this.findIndexInSelection(node);
        if (select && index == -1) {
            this.selection = (this.selection || []).concat([node]);
        }
        else if (!select && index > -1) {
            this.selection = this.selection.filter(function (val, i) { return i != index; });
        }
        node.partialSelected = false;
        // if (node.children && node.children.length) {
            // for (var _i = 0, _a = node.children; _i < _a.length; _i++) {
                // var child = _a[_i];
                // this.propagateSelectionDown(child, select);
            // }
        // }
    };
```

What I'm ideally looking for would be something close to this:
```
    TreeTable.prototype.propagateSelectionDown = function (node, select, **propagate**) {
        var index = this.findIndexInSelection(node);
        if (select && index == -1) {
            this.selection = (this.selection || []).concat([node]);
        }
        else if (!select && index > -1) {
            this.selection = this.selection.filter(function (val, i) { return i != index; });
        } **else if(propigate){**
          if (node.children && node.children.length) {
            for (var _i = 0, _a = node.children; _i < _a.length; _i++) {
                var child = _a[_i];
                this.propagateSelectionDown(child, select);
            }
          }
        }
        node.partialSelected = false;
    };
```

Thanks for the great project!

**Comment by umdstu** [comment]
I too would also appreciate this. I use the treetable for an actual directory tree. With the current implementation, selecting a file, or all immediate child files for a 'directory', the list of selected files includes an entry for each name of the parent nodes, which is kind of silly.

My current work-around is to filter the array of TreeNodes to remove those that are 'parents', as well as using CSS to style 'parent' nodes in the tree so that they do not look selected.

However, the code above seems dated. When reviewing where this would be possible it seemed likely it would be done in the `toggleNodeWithCheckbox()` function, specifically, around line 1050:

https://github.com/primefaces/primeng/blob/master/src/app/components/treetable/treetable.ts#L1050

Happy to attempt this myself if open to PRs.

Thanks

Angular 6.1.9
PrimeNG 6.1.2

**Comment by cagataycivici** [comment]
I'm unable to replicate with the latest PrimeNG. If the issue still persists with the new version please create a new issue with our stackblitz template.
