### ISSUE TITLE
Deprecate Free Themes in favor of Nova Free Theme Family

### ISSUE THREAD

**Issue by cagataycivici** [primefaces/primeng#6198]
Deprecate all free themes and remove them in PrimeNG 7.0

Introduce a new Nova free theme generated by the PrimeNG Theme Designer to give free themes a premium look, Nova has 3 alternatives;

- nova-light
- nova-colored
- nova-dark

**Comment by cagataycivici** [comment]
![primeng-nova-release-1](https://user-images.githubusercontent.com/686247/43542115-d5aa1e08-95d4-11e8-87dc-74cf14e1e9af.png)

**Comment by Da13Harris** [comment]
I'm working on upgrading our enterprise application from Angular/PrimeNG 7 to 8. The Angular upgrade was quick and efficient, but the PrimeNG upgrade gave me an error that the CLI can't resolve the location of the `node_modules\primeng\resources\themes\omega\theme.css`. It turns out the free omega stylesheets are no longer included.

It's unfortunate that these kinds of things are deprecated without sufficient communication. I can't seem to find anything about this deprecation other than this year-old, closed GitHub issue. It would be nice if things like this could be communicated via other channels, like the PrimeNG blog, Twitter, or a regularly updated changelog.

This type of issue was handled reasonably well when the DataTable was deprecated in favor of the Turbo Table. As a result, we were able to plan our refactors and work through the issues over the course of time, where this stylesheet issue came out of left field.

**Comment by armoucar** [comment]
Until v7: Enjoy templates my fellow devs, this is opensource.

v8: 'Purchase the Designer API to get full access to the theme engine.'
