### ISSUE TITLE
[6.0.2 p-dialog p-footer border]

### ISSUE THREAD

**Issue by liuyichuanfeng** [primefaces/primeng#6223]
<div class="ui-dialog-footer ui-widget-content ng-tns-c4-20 ng-star-inserted" style="">
         <p-footer......</p-footer>
</div>
.ui-dialog-footer{
    padding: 1em;
    border-width: 1px 0 0 0;
    text-align: right;
}

border-width: 1px 0 0 0;
This does not work.

**Comment by itanex** [comment]
How does it not work?

1) Does it not get applied to the footer at all? Then there really is an issue! 

Verify if you have a true footer element being rendered in the DOM.

2) Are you using a Theme?

If you are then, the values you are applied are being overridden due to selector specificity.

* Bring in your style sheet AFTER the Theme stylesheet, if you are concating them, then make sure the concat order makes your sheet last.
* Update the selector to be the same as the Theme selector, when adjusting a Theme for anything you should always place your overrides last so they are applied correctly. The selector your looking for is `body .ui-dialog .ui-dialog-footer`

3) Your not using a theme

Just correcting the order your stylesheets are delivered in will fix this. [see above]

**Comment by cagataycivici** [comment]
Not a valid issue report, please provide stackblitz next time.
