### ISSUE TITLE
Arrow of p-dropdown is not shown

### ISSUE THREAD

**Issue by alfredods** [primefaces/primeng#6226]
Hello,

I installed the new version of fontawesome (version 5) and use successfully these icons in buttons or other controls.

The problem is that after I migrate to this new version the arrow of the dropdown or other controls will no more be shown. It appears a strange symbol.

I installed angular 6, primeng 6 and primengicons.

Any idea?

Alfredo

**Comment by cagataycivici** [comment]
Please use forum for support requests.

**Comment by sourav-patra** [comment]
Found a bug with p-dropdown 'ui-dropdown-trigger' element. 
It appears that the classes 'pi pi-caret-down' are not added to it and hence the drop down icon is not visible.

![pdropdown](https://user-images.githubusercontent.com/35057258/45548077-a1fe1080-b840-11e8-8b5b-0ee16021211e.PNG)

For the other components like check boxes and radio buttons, prime icon classes are properly added, This bug seems to be limited to p-dropdown.

Could anyone follow-up on this?
