### ISSUE TITLE
Sidebar autoZIndex and baseZIndex doesn't add z-index to component

### ISSUE THREAD

**Issue by damatano** [primefaces/primeng#6295]
**I'm submitting a ...**  (check one with "x")
```
[X ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

https://stackblitz.com/github/primefaces/primeng-issue-template

**Current behavior**
After adding autoZIndex to false and setting baseZIndex, sidebar doesn't show up. DOM doesn't have property z-index.

**Expected behavior**
Sidebar should be adjusted. I belive problem is in if else condition: 
https://github.com/primefaces/primeng/blob/d7dffe2c2543b5043b809c4230d9f93645d5950d/src/app/components/sidebar/sidebar.ts#L123

**Minimal reproduction of the problem with instructions**

<p-sidebar [(visible)]="sidebarAppSettings" (onShow)="showAppSettings()" styleClass="ui-sidebar-lg" position="right" appendTo="body"
    [autoZIndex]="false" [baseZIndex]="3">

* **Angular version:** 5.X

* **PrimeNG version:** 6.10

* **Browser:** [Chrome]
 

PS. This is my first time submitting issue sorry if i did something wrong

**Comment by damatano** [comment]
any updates on this issue?

**Comment by cagataycivici** [comment]
This is by design as other components, baseZIndex is only used when autoZIndex is enabled, you can just use style property to define a fixed zindex.

**Comment by alpayoguz** [comment]
There is something wrong with this style and z-index. 
When I make autozIndex = 'true' , it gives z-index to first child of p-dialog and working correctly. But when I make autoZIndex="false" and give baseZIndex to p-dialog, it is exactly being applied to p-dialog component and that's why not being applied to element. Even ıf I give style with [style] property. Nothing has changed. Because [style] property is being applied to grandchild of p-dialog component(second inner element) and again its not working. Because even if z-index is being applied to grandchild of p-dialog component  it doesn't matter because z-index of a DOM element cant be higher than its parent
