### ISSUE TITLE
Table: EmptyMessage template doesn't work for lazy with binded totalRecords

### ISSUE THREAD

**Issue by sharok** [primefaces/primeng#6380]
**Plunkr Case (Bug Reports)**
[DEMO](https://stackblitz.com/edit/github-fvrewd)

**Current behavior**
Empty message template does not appear when there is no data and `totalRecords` is 0. But template is visible when there is no data and `totalRecords` > 0.

**Expected behavior**
Empty message should be visible when there is no data and `totalRecords` = 0.

**Minimal reproduction of the problem with instructions**
[DEMO](https://stackblitz.com/edit/github-fvrewd)

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

Windows 10, WebStorm 2018.2, npm
* **Angular version:** 5.2.10

* **PrimeNG version:** 6.1.2

* **Browser:** [all]

 
* **Language:** [all]

* **Node (for AoT issues):** `node --version` = 9.11.1

**Comment by yigitfindikli** [comment]
’m unable to replicate with the latest PrimeNG. If the issue still persists with the new version please create a new issue with our stackblitz template.

**Comment by idsplus-carlos** [comment]
@yigitfindikli I'm seeing the same problem here.
I've been digging around the code, the explanation is simple: when virtualScroll is used, table body's height is calculated based on totalRecords. However, when there's no data, totalRecords is 0, so `0 * rowHeight = 0` and no emptymessage is shown (even thought it's rendered, just not visible).
I'm not sure where to fix it in your code since adding a min(1) in the height calculation **only when emptymessage template is present** seems a bit hackish to me.

As a workaround, adding min-height to .ui-table-scrollable-body fixes it.
