### ISSUE TITLE
Dropdown: styling

### ISSUE THREAD

**Issue by MarcelCremer** [primefaces/primeng#642]
Hello everyone,

I have a dropdown and a button which should take up all the space needed (or at least look good somehow). It's included in a responsive table col.

However: If I don't supply a width and set autoWidth, the dropdown looks like:

![broken_dd](https://cloud.githubusercontent.com/assets/6123724/17056188/0047cd82-5012-11e6-8bba-e1bb5510158c.png)

If I supply width:100%, it looks like this:

![broken_dd2](https://cloud.githubusercontent.com/assets/6123724/17056199/12b45698-5012-11e6-8518-c7824d018e82.png)

The dropdown is in a col-10 and the button in a col-2. It would be great, if autowidth works like bootstrap inputs.

Cheers,
Marcel

**Comment by ryanwawr** [comment]
I was having similar problems, stemming from changing the options in the dropdown dynamically. Initially, there were no options until I made an asynchronous call to a REST service to get the values, so the dropdown autosized to around 50px, since there was no content. Calling updateDimensions in AfterContentChecked() resized it appropriately after the options had been loaded. Not sure if there's a better way to handle it in dropdown.ts so that I don't need to make an explicit call to updateDimensions, but it seems to be a viable workaround for the moment.

**Comment by LinqBeast** [comment]
@ryanwawr Would you mind sharing an example of how you did this?

**Comment by ryanwawr** [comment]
Pretty much just called the updateDimensions function on the p-dropdown element from the ngAfterContentChecked life cycle hook in the component containing the dropdown. This was with primeng 1.0.0 and Angular 2.0.0 though, so no guarantees that nothing has changed.

``` 
...

@ViewChild(Dropdown) dropdown: Dropdown;

...

ngAfterContentChecked() {
    if (someConditionIndicatingThatDropdownOptionsHaveChanged) {
        this.dropdown.updateDimensions();
    }
}
```

**Comment by LinqBeast** [comment]
Great.  That worked.

**Comment by cagataycivici** [comment]
Shoud be fixed in recent releases, please drop a comment if issue still persists and we may reopen.
