### ISSUE TITLE
TurboTable column text overflow problem 

### ISSUE THREAD

**Issue by pantonis** [primefaces/primeng#6540]
When using Primeng table and set the table as scrollable the table should show the scrollbar and the text inside the cells should not be overflown or hidden but instead column must preserve its size. Instead this does not happen. An example of what I mean is the bootstrap table example [here](https://getbootstrap.com/docs/4.0/content/tables/#always-responsive)

I created a sample of TurboTable to demonstrate the issue on [stackblitz](https://stackblitz.com/edit/primeng-tables-tfbdgt?file=src/app/app.component.html)

**Comment by viswa-optimusprime** [comment]
any update on this issue please? its happening for me too

**Comment by pantonis** [comment]
@cagataycivici Any estimate on fixing this issue?

**Comment by JacobSiegle** [comment]
I'm unsure of what you're saying the issue is here, but if you want a min column size set the col group?
`    <ng-template pTemplate="colgroup" let-columns>
        <colgroup>
            <col style="width:250px">
            <col style="width:250px">
            <col style="width:250px">
            <col style="width:250px">
            <col style="width:250px">
            <col style="width:250px">
        </colgroup>
    </ng-template>`

**Comment by pantonis** [comment]
@JacobSiegle I have over a hundred tables with over a thousand columns in total. Setting minimum height for each of these columns is not usable at all. So your proposed solution is not something that really helps.
Hope you understand.

**Comment by JacobSiegle** [comment]
I would assume you must not of set the cols prop on many of these tables and they are hard coded like in the example otherwise it would seem like an easy fix to just add the colgroup with an ngFor for all the tables.

Since the scrollable table is detached on the head and body I believe there would need to be some sort of sync where it has to scan the header cols (which would still require you to set the cols prop which brings us back to my prev note), figure out a min length based on the text sizing (?), and pass it to the head and body table to setup each cols min length. 

Honestly it seems easiest to me to just suggest setting the colgroup as I mentioned earlier instead of possible performance issues and complexity of trying to sync the state of the col min widths between two tables. You'll have to wait for @cagataycivici maybe he knows some other way to work around your issue i'm not seeing.

**Comment by JacobSiegle** [comment]
The tables that have the feature you're talking about (like your bootstrap example) are simple tables that do not have to implement all the features the primeng table has like a floating header, frozen cols, etc. I believe this isn't a bug but a defect from a design choice to make all those features work in a single component. When they chose to use multiple tables for the header, body, frozen body, etc when scrollable is enabled they made a disconnected between the tables and it's not easily possible to sync up the expected col widths automatically. That's why setting the colspan is the fix they suggest. The old p-datatable worked the same way, they rewrote the file into turbo table and they made the same design choice and it has the same defect.

There are a number of other issues closed that say the same thing where the col widths don't match up and they suggest setting the colgroup because they cannot sync the state of the width of the cols between the two tables unless you set the colgroup -
#4927, #5041

**Comment by pantonis** [comment]
@JacobSiegle 
````The tables that have the feature you're talking about (like your bootstrap example) are simple table``` 
No they are not. I have seen tables with more features than TurboTable that support this functionality.

```I believe this isn't a bug but a defect from a design choice```
The end result is the same. Workaround is hack fix

Thanks

**Comment by JacobSiegle** [comment]
OK maybe you can provide the library that has similar features to PrimeNG as I mentioned earlier like scroll, float header, frozen cols, frozen rows, etc and they could look at the design architecture of that library and see how they are syncing up the col widths and possibly port it over here.

**Comment by cagataycivici** [comment]
The scrollable tables require fixed width columns and table-layout: fixed, cannot be auto due to technical reasons so we are unable to provide a built-in solution. There are workarounds like wrapping the cell content in a div with overflow though.
