### ISSUE TITLE
CSV export support for Safari

### ISSUE THREAD

**Issue by cheng1994** [primefaces/primeng#659]
ExportCSV for DataTable does not work on Safari. It will open in a new tab with the csv seen as text and not cause the download to occur.

**Comment by raaaste** [comment]
This feature could probably be improved to take advantage of the "download" attribute of an \<a\> tag in html. That way we could specify a name and an extension for the file to be downloaded instead of just getting "download" (in chrome), making it easier to open with a spreadsheet program.

Instead of just providing a stream of data with headers, the function exportCSV could for example give a variable with the data so that we could use it in code. 

See [http://stackoverflow.com/questions/283956/is-there-any-way-to-specify-a-suggested-filename-when-using-data-uri](http://stackoverflow.com/questions/283956/is-there-any-way-to-specify-a-suggested-filename-when-using-data-uri)

**Comment by yigitfindikli** [comment]
We'll reconsider if there is more community feedback on this. Thank you for your report.
