### ISSUE TITLE
Dropdown menu does not open

### ISSUE THREAD

**Issue by carlbonsu** [primefaces/primeng#6802]
![primeng_dropdown_bug](https://user-images.githubusercontent.com/17915106/47803189-d6af2400-dd29-11e8-9ffa-e612252b3270.PNG)
After upgrading to PrimeNG 7, clicking on p-dropdown fails to open the dropdown menu. Close inspection of the html and css shows the display declaration for the dropdown menu panel is set to none by default (display: none), overriding this and setting it to block (display: block) fixes the issue.

I believe this is a bug, unless I'm missing something?

* **Angular version:** 7.0.3

* **PrimeNG version:** 7.0.0-beta.1

* **Browser:** [ Chrome 70.0.3538.77 (Official Build) (64-bit) | Firefox 63.0 (64-bit) | IE 11.345.17134.0 ]

**Comment by burgertm** [comment]
I'm also experiencing this issue.  I'm able to reproduce it from 6.0.2 onward.  6.0.1 and before work fine.

**Comment by neergaard79** [comment]
Same problem for me.

**Comment by cagataycivici** [comment]
Provide a stackblitz template please, unable to replicate.

**Comment by roldengarm** [comment]
> Provide a stackblitz template please, unable to replicate. Live demos seems to be fine;
> 
> https://www.primefaces.org/primeng/#/dropdown

Here you go @cagataycivici : https://stackblitz.com/edit/github-otpuub?file=src%2Fapp%2Fapp.component.html

**Comment by cagataycivici** [comment]
At line 12 of index.html, using;

Replacing this;

```html
<link rel="stylesheet" href="https://unpkg.com/primeng@6.0.0/resources/primeng.min.css" />
```

with

```html
  <link rel="stylesheet" href="https://unpkg.com/primeng@7.0.0-rc.2/resources/primeng.min.css" />
```

Fixes it.

**Comment by TheeRFG** [comment]
I don't actually package primeNG's stylesheet with our app, because it absolutely obliterates a lot of our other in place styles. Is there no other way around this, or a reason this is set to `display: none;` to begin with? 

I'll look and open a PR later if I get a chance, but it seems strange that this is set at all, and the only acceptable solution is to overwrite the property with CSS. 
Also worth noting that this is still "broken" in `7.0.3`
