### ISSUE TITLE
Listbox custom filter

### ISSUE THREAD

**Issue by axinedy** [primefaces/primeng#6994]
Hello

**I'm submitting a ...**  (check one with "x")
```
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
```
Currently p-listbox filters its contents according to the label only. Would be nice to attach a callback which will decide to filter item or not depending on other fields of item.

**Comment by tigrenok00** [comment]
+1
Am I right that without this there is no option for filter on listbox with custom template?

**Comment by OriolInvernonLlaneza** [comment]
I think adding the "filterBy" property used in the Tree component would be useful too.

**Comment by lnikolic** [comment]
+1 for this. A custom filter option would be super useful.

**Comment by scunningham777** [comment]
In case anyone else stumbles on this, I found a workaround that allows for passing in a function to the `optionLabel` input property that will receive the option object/value as an argument. Looking at listbox.ts, `optionLabel` is typed as "string" (line 123), but it is primarily accessed via the function `getOptionLabel()` (line 253), which internally uses the utility function `ObjectUtils.resolveFieldData()`, passing in the option object and `optionLabel`. Heading over to this function definition in src/app/components/objectutils.ts, line 60, we see that there is actually a check to see if the "field" passed in is a function, and if it is, it will pass the data object into that function as an argument and return the results. 

In order to pass in a function, you'll have to use a property binding, and in my case the compiler complained due to `optionLabel` being typed as a string, so I had to take advantage of the `$any()` directive. 

Here's a quick example:
in component.html:
```
<p-listbox
    [options]="optionsList"
    [optionLabel]="$any(buildOptionFilterString)"
    [filter]="true"
>
    <ng-template let-option pTemplate="item">
        <div class="w-full flex justify-content-between">
            <span>{{option.propertyOne}}</span>
            <span>| {{option.propertyTwo}}</span>
        </div>
    </ng-template>
</p-listbox>
```
And in component.ts:
```
@Component({
  selector: 'component',
  templateUrl: './component.html'
})
export class Component {
  public optionsList: {propertyOne: string, propertyTwo: string}[];
  public buildOptionFilterString(option: {propertyOne: string, propertyTwo: string}): string {
    return option.propertyOne + option.propertyTwo;
  }
}
```

My case is a pretty simple one, so be warned that I haven't tested out any more complex examples. I do also see that `optionLabel` is accessed directly a few times in the ListBox class, including in the `activateFilter()` function in the case that the `group` property is set to true (around line 544). I haven't tested this out with a grouped options list so you may run into issues in that case. Ultimately, this is definitely a hack, but it's at least a half-step up from modifying the imported primeng code...

**Comment by muhammedmisir** [comment]
Are there any updates on this feature ?

**Comment by Xriuk** [comment]
> I think adding the "filterBy" property used in the Tree component would be useful too.

Yep, this would be useful, as MultiSelect has it too

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
