### ISSUE TITLE
ERROR in primeng/.../picklist.d.ts.PickList.html(43,69): Expected 3 arguments, but got 4.

### ISSUE THREAD

**Issue by mseemann** [primefaces/primeng#6998]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
**Current behavior**
compilation error if `angularCompilerOptions.fullTemplateTypeCheck` and aot is `true`:
`ERROR in node_modules/primeng/components/picklist/picklist.d.ts.PickList.html(43,69): : Expected 3 arguments, but got 4.`

**Expected behavior**
no error in aot builds with `angularCompilerOptions.fullTemplateTypeCheck=true` 

**Minimal reproduction of the problem with instructions**
Template Error is in this line: https://github.com/primefaces/primeng/blob/01b4eb0dce26467dd37639a5cb207fb1b9c69877/src/app/components/picklist/picklist.ts#L52

(keyup)="onFilter($event,target,TARGET_LIST,onTargetFilter)"  has a 4th parameter the called method onFilter https://github.com/primefaces/primeng/blob/01b4eb0dce26467dd37639a5cb207fb1b9c69877/src/app/components/picklist/picklist.ts#L289 has only 3 parameters.

**Please tell us about your environment:**

* **Angular version:** 7.1.2

* **PrimeNG version:** 7.0.1

**Comment by pulkitnandan** [comment]
I'm facing a similar issue with angular version 9.1.9 &  "primeng": "^9.1.0"

`ERROR in node_modules/primeng/dropdown/primeng-dropdown.d.ts.Dropdown.html(17,83): Expected 0 arguments, but got 1.
node_modules/primeng/table/primeng-table.d.ts.ScrollableView.html(18,63): This condition will always return 'true' since the types 'boolean' and 'string' have no overlap.
node_modules/primeng/table/primeng-table.d.ts.ScrollableView.html(27,75): This condition will always return 'true' since the types 'boolean' and 'string' have no overlap.`
