### ISSUE TITLE
Add yearRange to calendar

### ISSUE THREAD

**Issue by MLC1435** [primefaces/primeng#709]
I have a problem with p-calendar I want to define a year range to the year dropbox but I don't know how, does any body here knows how to do?

Thanks in advance.
Mo

**Comment by cagataycivici** [comment]
With beta12, it is defined like;

http://api.jqueryui.com/datepicker/#option-yearRange

.e.g

```xml
yearRange="2002:2012"
```

**Comment by Glenndejaeger** [comment]
I've logged an issue related to yearRange: https://github.com/primefaces/primeng/issues/5476
The only way to make the user select a specific year in the popup is by setting yearRange. The problem is that when you manually enter a year outside of the range, it's not displayed in the popup (however ngModel is set correctly)
