### ISSUE TITLE
Issue in AutoComplete - Advance 

### ISSUE THREAD

**Issue by yashjangid1** [primefaces/primeng#7223]
After selecting the suggestion button from autocomplete too many times then sometimes it gets stuck and doesn't give any suggestions but when we write something on it and simply remove that then suggestions come back.

**Comment by igortg** [comment]
We had the same problem using p-autocomplete inside a p-dialog. Closing the dialog without hiding the option list first messes up with z-index calculation, and when we reopened the dialog, suggestions won't appear.

We fixed by forcing the autocomplete to loose focus before closing the dialog, so we make sure the autocomplete option list is always hidden.

**Comment by cagataycivici** [comment]
Unable to replicate with PrimeNG 9, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
