### ISSUE TITLE
TurboTable multiple selection with shift key not working with lazy load (event.data is undefined)

### ISSUE THREAD

**Issue by gojas** [primefaces/primeng#7226]
**I'm submitting a ...
```
[x ] bug report

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/github-yphbz7

**Current behavior**
When page is changed selection using the keyboard shift key is not working

**Expected behavior**
On every page selection with shift key should work

**Minimal reproduction of the problem with instructions**
1. Page 1 loads
2. Use keyboard shift key to select multiple rows - works
3. Load page 2 or 3
4. Use keyboard shift key to select multiple rows
5. Not working, also check onRowSelect, and onRowUnselect events - event.data is undefined

* **Angular version:** 7.X

* **PrimeNG version:** 7.0.7

* **Browser:**: Chrome

**Comment by cagataycivici** [comment]
This is expected, shift key is not supported in multiple pages as it is not intuitive. If more users demand it, we'll reconsider for sure.

**Comment by roukaour** [comment]
I am one of the users who would greatly appreciate this feature. Our application uses lazy-loading out of necessity due to working with large datasets, but still wants to support intuitive user interaction with tables so that lazy-loading is effectively an invisible implementation detail. That includes standard row selection with Ctrl and Shift.

PrimeNG's TurboTables have been very effective at meeting our needs so far with their performance and flexibility, and I hope you do reconsider this Shift key support.
