### ISSUE TITLE
Add key option to TreeNode API

### ISSUE THREAD

**Issue by mertsincan** [primefaces/primeng#7237]
If users have filter and checkbox selection features on Tree, they have to use 'key' option for these features to work correctly. The 'key' option is a unique value.

```
export interface TreeNode {
    label?: string;
    data?: any;
    icon?: any;
    expandedIcon?: any;
    collapsedIcon?: any;
    children?: TreeNode[];
    leaf?: boolean;
    expanded?: boolean;
    type?: string;
    parent?: TreeNode;
    partialSelected?: boolean;
    styleClass?: string;
    draggable?: boolean;
    droppable?: boolean;
    selectable?: boolean;
    key?: string;
}
```

**Comment by kievsash** [comment]
if user just used tree filter and then lazyLoaded some additional nodes - onNodeClick may not emit event on newly added nodes click since treeRef.value is not same as treeRef.filteredNodes anymore

https://github.com/primefaces/primeng/blob/16.9.1/src/app/components/tree/tree.ts#L1247
Solution: If add node.childre after filtering add them to respective node in treeRef.value  as well
