### ISSUE TITLE
Selected values in multiselect label are (null) when list of options loaded *after* bound selectedValue

### ISSUE THREAD

**Issue by tbertran** [primefaces/primeng#725]
Title is a bit convoluted but this [plunker ](http://plnkr.co/edit/ds1QX7) illustrates the problem.
Note that if `selectedCars` is populated **before** `cars`, it works fine.

FYI, I'm having this issue because, in my case, those two come from two different GET requests.

**Comment by michalig** [comment]
I'm not sure if this is the same issue but I have similar problem when using multiselect together with ng-translate. If I use translated string as a label, after refreshing the page (with F5) it is not displayed at all. I've tried to fix that somehow but I guess this is because ng-translate loads translation asynchronously and multiselect is rendered before it finishes.

@tbertran did you have a similar problem with multiselect?

**Comment by tbertran** [comment]
I did not use it with `ng-translate` so I don't know.

**Comment by mozdynjr** [comment]
I've also had this problem with **@angular/*=2.4.7** and **primeng=^2.0.1**.
But I guess it works as suppose to. If you want to assign/reference selected values to/from a collection, you first need to fetch this collection.

My case was in general like this:
There was a component with standard binding:
`<p-multiSelect [options]="brandOptions" defaultLabel="All Brands" [(ngModel)]="preselectedBrands" (onChange)="onCarBrandChange($event)"></p-multiSelect>`

and I was fetching options by service like so:
```
private prepareBrandOptions() {
        this.carService.getBrands()
            .then(brands => this.convertToOptions(this.brandOptions, brands));
    }
```
and at the same time doing `this.restoreBrandFilter();` which actually populated `this.preselectedBrands` from local storage.
`this.preselectedBrands` was always faster than REST call from `this.carService.getBrands()` and as an end result I'd always got nulls as labels (but the selections in drop-down were ok).

So I've moved `this.restoreBrandFilter();` simply like so
```
private prepareBrandOptions() {
        this.carService.getBrands()
            .then(brands => {
                this.convertToOptions(this.brandOptions, brands);
                this.restoreBrandFilter();
            });
    }
```
Probably could be done more intelligently, but was sufficient at that time.
Hope it helps, because the issue is not so obvious at the first sight.
It would be nice to have some warning or reminder in the docs...

**Comment by giscafer** [comment]
i got the same issue

**Comment by broweratcognitecdotcom** [comment]
This problem exists in version 4.1.0. We tried 5.0 also. Still a problem.
