### ISSUE TITLE
selectedItemsLabel for Multiselect component plain text bug

### ISSUE THREAD

**Issue by Pikadili83** [primefaces/primeng#7324]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://vbwilqlo.github.stackblitz.io

**Current behavior**
Plain text can't be used as "selectedItemsLabel".

**Expected behavior**
Accept plain text for "selectedItemsLabel".

**Minimal reproduction of the problem with instructions**
Set something like this:
[maxSelectedLabels]="1"
[selectedItemsLabel]="Multiple"
Select more then 1 item from the list.

**Please tell us about your environment:**
Windows 10, Web Storm

* **Angular version:** 7.2.4

* **PrimeNG version:** 7.0.5

* **Browser:** all
 
* **Language:** TypeScript 3.1.6

**Comment by nitoloz** [comment]
Unfortunately this is due to lines 676-678 in [multiselect.ts](https://github.com/primefaces/primeng/blob/master/src/app/components/multiselect/multiselect.ts#L676). In case `selectedItemsLabel` parameter doesn't contain pattern-matching string, where pattern is `/{(.*?)}/` the label isn't changed.

I would propose to have an `else` condition that would assign current filter label to `selectedItemsLabel` in case no matches have been found.
