### ISSUE TITLE
Virtual scrolling support without lazy loading

### ISSUE THREAD

**Issue by JacobSiegle** [primefaces/primeng#7419]
The ability to use virtual scroll in the turbo table without lazy loading. Scenarios exist where the data in the table is laggy because a huge number of rows exist, but data doesn't need to be loaded dynamically from an API. An example is a local excel file being loaded in.

I'm currently using pagination to solve this problem but virtual scroll seems so much nicer.

If lazy is set to false the table should assume all the rows were passed in and use the rows prop (like paginator) to paginate the dataset for virtual scrolling.

Related - https://github.com/primefaces/primeng/issues/4584

**Comment by sunnyyadav100** [comment]
This is the same thing I was trying to explain in https://github.com/primefaces/primeng/issues/7120, even when pagination is enable and table has approximate 50 columns. On changes of page size 50 to 100 table rendering times is increasing.

**Comment by JacobSiegle** [comment]
Reading over #7120 a few more times to try to understand it, the request seems like the ability to use lazy loading with pagination for records already loaded. For example if you load 500 records you could lazily show 100 of them. 

It seems like a very similar request, i'm not sure if they are the same thing. Hopefully fixing one of them would just naturally fix the other.

**Comment by MarkJungeblut** [comment]
What is the state here? 
We also need the ablitity to implement infinite scrolling without relying on lazy load. 
We have about 10000 datasets in the table which results in big performance leaks. 
Pagination is no option in our case. 

Any recommendations?

**Comment by JacobSiegle** [comment]
You can still make it work by slicing your dataset and using lazy load, it's just a lot more ceremony. The status is unknown unless a maintainer responds or someone puts in a PR.

**Comment by MarkJungeblut** [comment]
Thank you for the quick response.
Currently slicing is no option in our case. 
Are there any other options? 
I dont understand why the functionality is just available in combination with lazy loading. 

In my opinion there should be no negative impact if infinite scrolling is enabled by default.

And its also very easy to implement it with angular 7 cdk 
https://angular-yni1jw.stackblitz.io/

**Comment by JacobSiegle** [comment]
There are no other options right now besides using lazy and slicing and doing more cermony. You can try to look into it and PR it yourself if you would like. I'm sure it's not just as easy as throwing the CDK in because turbo table is probably the most complex component in PrimeNG.

**Comment by kayvanbree** [comment]
We have an API that gives us our data at once. 8000 rows can't be dealt with by PrimeNG as is. We don't want to add lazy loading. We found that the Angular CDK virtual scroll does wonders for PrimeNG but the only way to implement it seems to be to copy paste the classes for treetable and ttBody, which we don't want to do. 

Adding CDK virtual scroll would be awesome!

**Comment by mvorisek7** [comment]
We're in the same boat here. We have our data available up front but would like to use the virtual scroll without lazy loading and slicing. 

Hopefully somebody will tackle this issue soon as this seems like such a basic thing to have.

**Comment by mvorisek7** [comment]
Ok, so I think I got a working example using cdk virtual scroll without lazy load.

1. You'll want to duplicate 'primeng/src/app/components/table/table.ts' and put it somewhere in your angular directory.

2. In the duplicated file, change the bad import paths to their respective paths in node_modules

3. Import the ScrollingModule from '@angular/cdk/scrolling' and make sure to add it to the imports and exports at the bottom of the file.

4. In the template for 'pScrollableView', wrap the div called '#scrollBody' with <cdk-virtual-scroll-viewport> Make sure that you give the view port an item size and class with a set height so that the view port doesn't have a height of '0'.

5. In the template for 'pTableBody', you'll have to decide how you're using the rows for the table. In our case we didn't need the expanding rows, so we only modified the first part of the template for when the rows are not expanded. Modification involved swapping the ngFor directive to the cdkVirtualScroll equivalents.
```
<ng-container *ngIf="!dt.expandedRowTemplate">
    <ng-template cdkVirtualFor let-rowData let-rowIndex="index" [cdkVirtualForOf]="(dt.paginator && !dt.lazy) ? ((dt.filteredValue||dt.value) | slice:dt.first:(dt.first + dt.rows)) : (dt.filteredValue||dt.value)" [cdkVirtualForTrackBy]="dt.rowTrackBy">
        <ng-container *ngTemplateOutlet="template; context: {$implicit: rowData, rowIndex: dt.paginator ? (dt.first + rowIndex) : rowIndex, columns: columns, editing: (dt.editMode === 'row' && dt.isRowEditing(rowData))}"></ng-container>
    </ng-template>
</ng-container>
```

6. Now for your app.module, instead of importing TableModule from the primeng node_module package, import it from the duplicated file.

You shouldn't have to modify any of your template code for the actual implementation of the table, 

Hopefully, that helps anyone who's been waiting on a solution.

**Comment by jucasoft** [comment]
There are updates?
solution?

**Comment by cagataycivici** [comment]
Will check this for next week's 9.0.2

**Comment by andriikuts** [comment]
Any updates?

**Comment by jacqueslareau** [comment]
Would like some updates too. I've tried to implement mvorisek7's solution and it seems it could work just fine but has small bugs. I have a table with just over 1000 lines and it's REALLY slow.

**Comment by cagataycivici** [comment]
VirtualScrolling for Table is reimplemented from the ground up (#8855) and this particular case i no longer an issue with the new implementation. There is also a demo for VirtualScroller without lazy.

**Comment by wondie** [comment]
@cagataycivici I have used this example, I guess the new implementation but data loads very slowly. The table has about 60 columns, with row and cell edit.
