### ISSUE TITLE
VirtualScroller for Autocomplete items

### ISSUE THREAD

**Issue by SDLTechnology** [primefaces/primeng#7442]
If you have a PrimeNG PRO Support subscription please post your issue at;

https://pro.primefaces.org 

where our team will respond within 4 business hours.

If you do not have a PrimeNG PRO Support subscription, fill-in the report below. Please note that
your issue will be added to the waiting list of community issues and will be reviewed on a first-come first-serve basis, as a result, the support team is unable to guarantee a specific schedule on when it will be reviewed. Thank you for your understanding.

Current Waiting Time: ~8 weeks.

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[ x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
**What is the motivation / use case for changing the behavior?**
When using Autocomplete with 9000 or more items the control takes 8-10 seconds to open the suggestions panel. Adding in Virtual Scrolling would make this control faster with large data. Dropdown component already support it.

**Please tell us about your environment:**
Windows 10, Webstorm

* **Angular version:** 7.2.9

* **PrimeNG version:** 7.1.0

* **Browser:** all

* **Language:** TypeScript 3.3

* **Node (for AoT issues):**  10.15

**Comment by Laoujin** [comment]
Is this on the roadmap?

**Comment by Laoujin** [comment]
So... I created an implementation... Any chance this will get merged? :)

**Comment by Laoujin** [comment]
I'm guessing there is no interest in this functionality?

There is a merge conflict now. If this PR could be merged, I shall resolve the conflict.
I assume that in order to have this merged, we'd need to buy the "professional primeNG" first?

**Comment by brian428** [comment]
Would be very helpful to have the same virtual scroll option that was added to Dropdown. The same issue (slow render with a large list) affects Autocomplete as well.

**Comment by agrinko** [comment]
I totally support this feature request. It's becoming critical for us now, in some instances autocomplete dropdown freezes the whole UI for 10+ seconds because there are thousands of items...

**Comment by meta-akshita-agrawal** [comment]
Yes, this is needed. The whole page gets unresponsive in my case.

**Comment by fernandocode** [comment]
This is something really important to have native support, I am trying an alternative approach, with autocomplete + virtualscroller, if someone has a working example it would be interesting to post here. :sweat_smile:

**Comment by kareljuricka** [comment]
Looking forward to official support.

**Comment by GaurangDhorda** [comment]
@yigitfindikli [As in this commit](https://github.com/primefaces/primeng/commit/57bc25f8a375f2e7ee0ce03e6f94a3facee3970b) You have updated autocomplete with virtual-scroll. but I have found one minor visual effect is that in your commit on-line number 67 , you have this on <li> tag, `[ngStyle]="{'height': itemSize + 'px'}"` . When we use autocomplete component and sets itemSize property `[ itemSize = 4 ]` then based on ngStyle the height of <li> is also  gona be 4px , so, we can not see proper list when autocompelete list is opened , if we set itemSize = 25 then <li> height will be 25px, and thats okay.. So for lower < 15 itemSize you need to set height of <li> default.. Otherwise inside our style.css we manuaaly have to set <li> height: auto !important , .. please update it and commit
