### ISSUE TITLE
Default focus button should be configurable

### ISSUE THREAD

**Issue by earshinov** [primefaces/primeng#7622]
**I'm submitting a ...**

[x] feature request

**Current behavior**

In https://github.com/primefaces/primeng/issues/2119, ConfirmDialog learned to automatically focus the first button inside a dialog when it opens.

However, in some cases, some other button should receive focus by default.

Perhaps, the most common of these cases is dialogs which ask the user to confirm some destructive actions. In this case, it is widely accepted that "No" button should be focused by default, rather than "Yes", which happens to come first.

Here is a demo:
https://stackblitz.com/edit/primeng-confirmdialog-default-button

I have found a similar request/question for PrimeFaces:
https://stackoverflow.com/questions/29811925/in-primefaces-4-0-confirm-dialog-how-do-i-ensure-no-is-in-focus-by-default

**Expected behavior**

The default button should be configurable. The invocation could look like this:

```
this.onfirmationService.confirm({
  // ...
  defaultButton: 'reject' // undefined|'accept'|'reject'
});
```

Perhaps, it could be useful to also allow default button configuration in the HTML template:

```
<p-confirmDialog ... defaultButton="reject"></p-confirmDialog>
```

When the `defaultButton` is not configured, the implementation could focus the first button like it does now. It will provide backward compatibility.

**Minimal reproduction of the problem with instructions**

Please visit the demo page:
https://stackblitz.com/edit/primeng-confirmdialog-default-button

1. Click the 'Drop database button'
2. Press Enter when the dialog opens

As the default button is 'Yes', the database is dropped (see console output).

**What is the motivation / use case for changing the behavior?**

Many people habitually press Enter. Destructive actions should require more actions than pressing Enter, so that users pay more attention to what he/she is doing.

**Please tell us about your environment:**

* Angular version: 7.2.8
* PrimeNG version: 7.1.0
* Browser: all
* Language: TypeScript 3.3

**Comment by dmytro-gokun** [comment]
I would like to second this

**Comment by Cito** [comment]
This feature is seriously missing. Like @earshinov said, it's too easy to just press enter and for some actions. Sometimes you want to be really sure the user made a concious decision.

Using the "accept" button for the non-desctructive action is not a good workaround, because the names become confusing and because then simply closing the dialog would trigger the destructive action, which makes things even worse.

Therefore I am currently using the following workaround:

```html
<p-confirmDialog #cd icon="pi pi-exclamation-triangle">
  <p-footer>
    <!-- workaround for primeng/issues/7622 (first button is always default) -->
    <div *ngIf="cd.acceptVisible && cd.rejectVisible && cd.acceptLabel.length > cd.rejectLabel.length; else cdStandardFooter" style="display:flex;flex-direction:row-reverse">
      <button type="button" pButton [icon]="cd.rejectIcon" [label]="cd.rejectLabel" (click)="cd.reject()" [class]="cd.rejectButtonStyleClass"></button>
      <button type="button" pButton [icon]="cd.acceptIcon" [label]="cd.acceptLabel" (click)="cd.accept()" [class]="cd.acceptButtonStyleClass"></button>
    </div>
    <ng-template #cdStandardFooter>
      <button type="button" pButton [icon]="cd.acceptIcon" [label]="cd.acceptLabel" (click)="cd.accept()" [class]="cd.acceptButtonStyleClass" *ngIf="cd.acceptVisible"></button>
      <button type="button" pButton [icon]="cd.rejectIcon" [label]="cd.rejectLabel" (click)="cd.reject()" [class]="cd.rejectButtonStyleClass" *ngIf="cd.rejectVisible"></button>
    </ng-template>
  </p-footer>
</p-confirmDialog>
```
A confirm dialog with buttons like accept = "Ok", reject = "Cancel", will show up as usual. But if the accept action is really destructive, I make the text of the accept button longer than the text of the reject button, e.g. accept = "Ok, destroy all my bases", reject = "Cancel". If this is the case, the reject button will automatically become the default one.

Let me know if a PR implementing a solution like suggested by @earshinov would be accepted, I would gladly contribute this feature so I don't need this workaround any more.
