### ISSUE TITLE
Link from p-calendar to the p-schedule

### ISSUE THREAD

**Issue by MLC1435** [primefaces/primeng#776]
Hello all,

Does anybody have an idea how to link the p-calendar to p-schedule; when I click on day on calendar open the schedule in this day date. for example when I click on "25/08/2016" on calendar I select the "25/08/2016" on schedule.

Thanks on advance.

**Comment by akshayextentia** [comment]
Hi PrimeNG team,

I am also trying same thing to bind calendar date with schedule day date. but unfortunately i did not get any solutions.
Actually the problem is, while the p-schedule loaded once after that it is not changed day view if you set any other date from back side dynamically or from .ts file, the same thing happened with minTime and maxTime. How can be achieve this thing from back side. There is any option to override schedule class or something else? Please let us know as soon as possible.

Thanks on Advance.

**Comment by akshayextentia** [comment]
Hi All, 
I found a solution which is like that and its work on my angular 2 project:

jQuery('.ui-widget').fullCalendar('gotoDate', date);

i founded from here :
https://github.com/primefaces/primeng/issues/495

**Comment by akshayextentia** [comment]
I all i found a solution from here please check it.

https://github.com/primefaces/primeng/issues/495

**Comment by cagataycivici** [comment]
Please use forum for cases like these.
