### ISSUE TITLE
Backward compatibility with v1.0.0-beta.12

### ISSUE THREAD

**Issue by idirouhab** [primefaces/primeng#789]
Hello,

The new  beta version of the primeng has breaking change because Angular 2-RC5's changes.

In some components you're using the new ngModule, and is a new feature of the RC5, not of the RC4.

In our case, we are using the beta.12 with RC4 but beta.13 are not compatible, for that reason I think that, maybe it's a major version instead of a patch.

**Comment by sdmoralesma** [comment]
That's a problem with angular2 because they introduced breaking changes (even although is in ReleaseCandidate). If Ang2 keeps adding more breaking changes primeng has nothing else to do than catch up and include them.

Remember that primeng is _currently_ in beta and shouldn't be used on production systems. Please update (and pray for ang2 won't break in the future.)

Note: Consider to close this issue giving that no action is needed.

**Comment by cagataycivici** [comment]
This is Angular2 related so had to close. We will do PrimeNG RC1 after NG2 goes final.
