### ISSUE TITLE
ConfirmDialog is blurry when opened

### ISSUE THREAD

**Issue by davisb10** [primefaces/primeng#7919]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

Visible from Showcase website

**Current behavior**

Open the ConfirmDialog. The text and lines are blurry.

**Expected behavior**

Not to be blurry.

**Minimal reproduction of the problem with instructions**

Tested on Chrome, Firefox and Edge. Just appears to be the ConfirmDialog. Other Dialogs seems to be fine.

When modifying the css through Developer Console, removing the translateZ(0px) value on the ui-dialog div, the blurriness goes away.

**Comment by JacobSiegle** [comment]
Was running into the same issue, added a quick PR about for removing translateZ.

**Comment by smorandi** [comment]
This has nothing to do with only translateZ. the whole transform/tranlsate expression will lead to a blurred dialog, and it is not just the Confirmation dialog. There seems to be a general issue with DynamicDialog which suffers from this issue. When i disable the transform expression in the css (at least in chrome) the blurriness disapears, but the dialog will not be centered anymore either.

**Comment by JacobSiegle** [comment]
Whatever you're running into i'm unsure if its the same error. I don't see any blurriness in chrome 75 with any of the dialogs besides confirm which removing the z-index does fix. Can you report your chrome version, screen resolution, etc. so maybe someone can replicate the blurriness?

Top is confirm, bottom is dynamic. I see no difference in dynamic removing the transform or changing the values to the suggested. Blurriness is fixed in confirm by removing z-index, I tested it just now.
![Untitled](https://user-images.githubusercontent.com/5766272/61795518-33d39400-ade9-11e9-8083-97d42f691d0b.png)

**Comment by smorandi** [comment]
Yeah, might well be another issue, however I am also using Chrome 75. And the issue i am facing is actually with the DynamicDialog. But that also is not really the problem.

The root problem for all this is just that there is an issue with how webkit renders items which after tranformation end up in "subpixels", i.e. positions which are expressed by fractions of pixels. This happens often when you use percentage based calculations on items whose dimesions are uneven.
So in those cases you may end up with blurred text and/or borders.

So dependening on the content of what you show it may or may not en up be blurred. The only reliable way is to with fix the size of content showing up to an even number of pixels, which is not really possible or desirable. or to remove the transformation and do a different way of centering the dialog (like using grid or flex or something).

For chrome, the issue seems to be around since 2014. There are myriad of threads about this very issue and it's still open for chromium.
