### ISSUE TITLE
TimeLine component for Angular UI

### ISSUE THREAD

**Issue by ferlolo** [primefaces/primeng#7936]
Hi, i have a doubt.
Why in PrimeNG, the component TimeLine like the primeFaces not exists, will be very usefull for Angular.

Do you plan to implement it in the future?
thx.
Regards.

**Comment by jmarmin** [comment]
Hi, it's already planned in the [roadmap](https://github.com/primefaces/primeng/wiki/Roadmap).

**Comment by wederer** [comment]
Is there any update on this? There is no mention of the TimeLine component on the roadmap.

**Comment by EliasDerHai** [comment]
Would be neat if something happend 👍

**Comment by cagataycivici** [comment]
We have this one now;

https://twitter.com/cagataycivici/status/1321136058046795782

**Comment by gustavobmichel** [comment]
Hi @cagataycivici, this component looks nice.

I have seen two issues with it though:

 Can't bind to 'value' since it isn't a known property of 'p-timeline'.
    1. If 'p-timeline' is an Angular component and it has 'value' input, then verify that it is part of this module.
    2. If 'p-timeline' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
    3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component.

When changing the custom timeline example for horizontal, the last item doesn't resize to follow the others. I changed the stackblitz to show the error. You need to resize the window on the right to see it:
[https://stackblitz.com/edit/primeng-timeline-demo-maayqe?file=src/app/app.component.html](https://stackblitz.com/edit/primeng-timeline-demo-maayqe?file=src/app/app.component.html)

![image](https://user-images.githubusercontent.com/14951413/100100123-39ffd780-2e58-11eb-910f-942b596f700a.png)

Happy to create a new issue for this.
