### ISSUE TITLE
Centered toast could be blurry

### ISSUE THREAD

**Issue by mickeyjohn** [primefaces/primeng#8101]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report

**Current behavior**
Toast with confirm message dialog shows blurry text in Chrome (current and most recent versions) when the browser is not maximized. 

**Expected behavior**
Should show clear text when Chrome browser window is not maximized.

**Minimal reproduction of the problem with instructions**
1. Open Toast demo page in Chrome, let the browser window not maximized.
2. Click on the "Confirm" button under Template, It shows blurry text in the dialog
![Toast_confirm_blurry_w_transform](https://user-images.githubusercontent.com/14140486/63860345-efeb2600-c976-11e9-8b0d-00562182ca85.png)

Using Chrome Dev Tools, remove the transforms css of the div contains ui-toast will make the dialog appears clearly as expected but the dialog message is not centered properly.
 
![Toast_confirm_clear_wo_transform](https://user-images.githubusercontent.com/14140486/63860664-828bc500-c977-11e9-8ae2-be4dfa38fca6.png)

**Comment by JacobSiegle** [comment]
The text looks the same to me in both scenarios. I'm assuming it's similar to the notes in issue https://github.com/primefaces/primeng/issues/7919.

I put the users issue below again because they messed up the formatting and it was annoying to attempt to read - 

**Current behavior**
Toast with confirm message dialog shows blurry text in Chrome (current and most recent versions) when the browser is not maximized. 

**Expected behavior**
Should show clear text when Chrome browser window is not maximized.

**Minimal reproduction of the problem with instructions**
1. Open Toast demo page in Chrome, let the browser window not maximized.
2. Click on the "Confirm" button under Template, It shows blurry text in the dialog
![Toast_confirm_blurry_w_transform](https://user-images.githubusercontent.com/14140486/63860345-efeb2600-c976-11e9-8b0d-00562182ca85.png)

Using Chrome Dev Tools, remove the transforms css of the div contains ui-toast will make the dialog appears clearly as expected but the dialog message is not centered properly.
 
![Toast_confirm_clear_wo_transform](https://user-images.githubusercontent.com/14140486/63860664-828bc500-c977-11e9-8ae2-be4dfa38fca6.png)

**Comment by mickeyjohn** [comment]
Thanks @JacobSiegle for making it clearer to read. Actually, I was truggling and could not find out how to show the attached pictures.

**Comment by digitalcraftco** [comment]
Try adding the following css. It fixed the blur for me and doesn't look like it effected any positioning.

`body .ui-toast {
  position: absolute;
}`

**Comment by mathieuAAA12** [comment]
You're probably having a problem with text rendering because of a rounding issue. [**Check out this article.**](https://keithclark.co.uk/articles/gpu-text-rendering-in-webkit/)

The confirm dialog should manage that. I tried to override the component, but unfortunately, the transform attribute is now nested in an animation state...

To fix your issue right now, make sure your popup's width and height have even values.

**Comment by cagataycivici** [comment]
We've resolved the same case with the blurry dialogs after migrating to Flex, @mertsincan will do the same for Toast as well, it is a known chrome issue.

**Comment by cagataycivici** [comment]
We'll apply a custom solution instead, flex is not really necessary here.

**Comment by yigitfindikli** [comment]
Unable to replicate with latest PrimeNG, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
