### ISSUE TITLE
Virtual Scroll for Listbox

### ISSUE THREAD

**Issue by aznmonkey** [primefaces/primeng#8133]
It would be nice if the the p-listbox component had a virtual scroll options for the display of larger lists. In lieu of that, it would be sufficient to have an onScrollEnd event emitted once the user has scrolled to the bottom of the list so that items could be retrieved incrementally.

**Comment by tim-boerner** [comment]
We are using listbox with around 3000 values and it is already slow. Virtual scroll would we very nice here.

**Comment by s0nnyhu** [comment]
up

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,

**Comment by MrBasque** [comment]
According to the latest documentation, virtualscrolling / lazy loading is still missing, but very much requested. The Multiselect component does have this feature, but the requested behavior of Multiselect does not match, since this behaves like a dropdown (opens on click), and what we need is a list that stays open and can contain a huge list of data.

**Comment by lixaotec** [comment]
+1

**Comment by cetincakiroglu** [comment]
Hi,

This feature has been added in v17
