### ISSUE TITLE
primeng responsive in build mode 

### ISSUE THREAD

**Issue by self-ads** [primefaces/primeng#8143]
hello, 
i have a problem with primeng, when i build my project with (ng build) , the application is not more responsive as it was in test mode can give me a solution pls

**Comment by JacobSiegle** [comment]
This is a question and not really an issue, it should be on the primeng forums not here. If your app is slow in dev it most likely won't be that much faster on prod. All that I can really suggest is to be sure you're building with the --prod flag. Otherwise there's no way of knowing what actually is slowing down your app.

**Comment by self-ads** [comment]
i'm talking about how fast is my app, i'm talking about responsive style is no more applicable

**Comment by JacobSiegle** [comment]
Do you have a specific component that causes issues or any way to replicate? It's really impossible to say what is wrong without more context.

**Comment by self-ads** [comment]
thank you for your replay, but its about all compenents

**Comment by cagataycivici** [comment]
Please use forum for support requests and questions.
