### ISSUE TITLE
Autocomplete with arrow down key gives items all over again.

### ISSUE THREAD

**Issue by navipegator** [primefaces/primeng#8179]
**I'm submitting a ...**  (check one with "x")
```
[X ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

Example case is in PrimeNG demo page
**Minimal reproduction of the problem with instructions**
**Current behavior**

Go to PrimeNg site and Autocomplete demo
https://www.primefaces.org/primeng/#/autocomplete

Type "a" to first autocomplete box
Hover with mouse over "Afganistan"
Press Arrow down from keyboard and repeat this.

You can browse 58 items staring with a (There are many dublicates)
**Expected behavior**
You can browse 15 items staring with a (No dubliates on the list)

** More info **
If you just press down arrow without hovering first item in the list, then everything works correctly.

**Comment by JacobSiegle** [comment]
The issue is not that duplicate items are in the list, it's that the scroll position when hitting the bottom is being reset to wherever the mouse currently is hovered over the dropdown. This makes it so that you have to rescroll to get the the bottom of the list again. To verify this put your mouse on the bottom element instead of the top and try it again.

**Comment by cagataycivici** [comment]
Unable to replicate with PrimeNG 9, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
