### ISSUE TITLE
selectOtherMonths is broken in multiple and range mode

### ISSUE THREAD

**Issue by azizparmaksiz** [primefaces/primeng#8349]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
PrimeNG version:** 8.1.0

Hi, I am using p-calendar with [selectOtherMonths]="true" [showOtherMonths]="true"    selectionMode="range"  properties. 
And when calendar dialog opened as 
![image](https://user-images.githubusercontent.com/29042929/69520545-0a30a200-0f6e-11ea-8541-b490015bd725.png)

 While I was picking the first date from other months value the calendar dialog is closed before I select the second date.

**Comment by minato-namikaze** [comment]
The issue I found in the code is the following:
Whenever we click even in a date range selection mode, we enter in this method **bindDocumentClickListener ** and proceed with the call of hideOverlay() because the condition **  if (_this.isOutsideClicked(event) && _this.overlayVisible) { ** is truthy whereas it should not.

Actually, looking at the method isOutsideClicked, the first statement checked is ** !(this.el.nativeElement.isSameNode(event.target)**. We clearly see the negation of the same node comparison will return true, which is wrong. So, removing the negative operator could help fixing the issue.

**Comment by zacharyfox** [comment]
I am also experiencing this issue.

**Comment by neergaard79** [comment]
Same issue for me.
