### ISSUE TITLE
Carousel  - Button inside carousel-item is not clickable in mobile phones

### ISSUE THREAD

**Issue by BissacM** [primefaces/primeng#8377]
**Current behavior**
When adding buttons to a carousel item, on mobile it's not clickable.

**Expected behavior**
Should be able to emit click events when the buttons were clicked.

**Please tell us about your environment:**
Any

* **Angular version:** 
latest Angular version

* **PrimeNG version:** 
latest PrimeNG version

* **Browser:**
 In any **mobile** browsers.
 
* **Language:** 
All

**Comment by suryamuppalla** [comment]
+ Same issue

**Comment by suryamuppalla** [comment]
Same Issue

**Comment by belialzxz** [comment]
Same here. The issue I see is that any click within the content area causes the "go to previous" event, as the carousel moves to previous item. I am able to replicate this on the showcase as well. I tried testing with Chrome dev console emulator, and no matter the viewport size, the bug was happening. I noticed it first on my Samsung Galaxy.
