### ISSUE TITLE
how about to rename the `onLabel` property of `p-toggleButton`

### ISSUE THREAD

**Issue by lymimt** [primefaces/primeng#8436]
when i use `p-toggleButton` like this:

```html
<p-toggleButton [(ngModel)]="checked" onLabel="I confirm" offLabel="I reject" onIcon="fa fa-check" offIcon="fa fa-times"
	[style]="{'width':'150px'}"></p-toggleButton>
```
sample: https://stackblitz.com/edit/angular-izgb41?file=app%2Fapp.component.html

problems:

![image](https://user-images.githubusercontent.com/37477603/71403344-63255000-266a-11ea-9892-ac63b600b418.png)

![image](https://user-images.githubusercontent.com/37477603/71403226-0de93e80-266a-11ea-955e-99f1f5cb705a.png)

i open an issue in vscode repos and got reply:

https://github.com/microsoft/vscode/issues/87631#issuecomment-568788584

> The built-in html language server thinks that `onLabel` and `onIcon` are script attributes

so how about to gives another name for that properties?

**Comment by Cito** [comment]
@lymint Is there a reason why you closed this issue?

I think your suggestion makes sense. I get similar errors from the linter because attributes starting with "on" are expected to contain JavaScript code, not text or classes.

How about adding `labelOn`, `labelOff, `iconOn`, `iconOff` as aliases for the existing attribute names, and deprecating the current attribute names?

**Comment by lymims** [comment]
@Cito 

you can use `iconOn` with binding, like this:

```html
<p-toggleButton [onIcon]="'fa fa-check'">
```

**Comment by Cito** [comment]
@lymims Right, that can be used as a workaround. But it's uglier than `iconOn="fa fa-check"`. The better solution would still be if the attributes were renamed.

**Comment by lymims** [comment]
@Cito I close this issue just because I found the solution, maybe you can open a new one.
