### ISSUE TITLE
Table state not saved when columns (input) changed

### ISSUE THREAD

**Issue by viceice** [primefaces/primeng#8902]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/github-81vgx6

**Current behavior**
When the `columns` input of the table changes, the state (new colum order / width) is not saved.

**Expected behavior**
Call save state when `columns` change.

**Minimal reproduction of the problem with instructions**
* use stateful table (i use lazy, reorderable, resizable)
* change column width -> save state called
* change input columns (eg with timeout) -> no save state called.

**What is the motivation / use case for changing the behavior?**
I have a custom column picker to change visible columns on the fly.

**Please tell us about your environment:**
vscode, windows (more not nessessary)

* **Angular version:**  9.1.x

* **PrimeNG version:** 9.0.x

* **Browser:** all
 
* **Language:** all

* **Node (for AoT issues):** `node --version` =  12.17.0

**Comment by dtaylor84** [comment]
I have a similar problem.

A fairly simple workaround for the problem described is to call table.saveState() when changing the columns manually.

The problem I have is when the table restores its state automatically:
- The onStateRestore event occurs when the value input is first set, before the columns have been set.
- The internal restoreColumnOrder method is called when the columns are first set.
- No event/output is emitted when the column order is restored (such as onColReorder)
- When columns are reordered interactively, the onColReorder event is fired and the columns input 
  array is mutated in-place.
- The columns input (technically its backing field _columns) is not mutated by restoreColumnOrder,
  but replaced with a new array.

As a result of all this, in order to see the restored column state I need to do a setTimeout() in the onStateRestore handler to wait for the next tick (where columns will have been set, triggering restoreColumnOrder) and grab the table.columns value.

Ideally restoreColumnOrder would mutate the columns array in-place. Alternatively, at least emitting an event when the order is restored would be helpful.

**Comment by viceice** [comment]
> A fairly simple workaround for the problem described is to call table.saveState() when changing the columns manually.

That's what i'm doing 😅

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,

**Comment by EstelonAgarwaen** [comment]
Hi,

I recently found this bug in v20. It is not fixed. I created a test case in the Table Component Tests to reproduce it. 
I can submit a PR with a fix for this bug as long as the PR is actually reviewed by someone and does not sit around for months.

[#8902-reproducing-test-case.patch](https://github.com/user-attachments/files/23848062/8902-reproducing-test-case.patch)
