### ISSUE TITLE
InputNumber control with Norway locale ('nb-NO') cannot input minus (-) sign for negative numbers.

### ISSUE THREAD

**Issue by dinhtruonggiang** [primefaces/primeng#8963]
I cannot put minus (-) sign for negative numbers with locale 'nb-NO' in InputNumber control. However, I can enter negative numbers with other locales, such as "en-US" or "de-DE":

<p-inputNumber name="total" [(ngModel)]="total" [minFractionDigits]="2" locale="nb-NO" suffix=" kr"></p-inputNumber>

**Comment by priyanhsu10** [comment]
i also getting the same for decimal input 
this control not allowed to enter minus sign initially but after number entered we can enter the minus sign at beginning

**Comment by mertsincan** [comment]
Hi,

As you know, InputNumber component uses Intl.NumberFormat API; 
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat
Could you please try it?
I think this issue is related to Unicode. Please see the minus signs in the screenshot. They are not the same. One of them is thin and the other is thick.
<img width="700" alt="locale_check" src="https://user-images.githubusercontent.com/11868120/91851664-42d17a80-ec68-11ea-9d17-ae036843d397.png">


Maybe, the minus sign can be Hyphen-minus; https://en.wikipedia.org/wiki/Plus_and_minus_signs
I'm not sure :/
