### ISSUE TITLE
9.1.2 p-table lazy loading virtual scroll not working

### ISSUE THREAD

**Issue by beleta** [primefaces/primeng#8990]
[x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35

**Current behavior**
p-table not fire event (onLazyLoad) when scroll to end

**Expected behavior**
When scroll to end of rows p-table must fire event onLazyLoad to load new records from remote data source.

Angular version: 9.1.11
PrimeNG version: 9.1.2
Browser: all

**Comment by ninjavis** [comment]
I second this, please.

I'm really thankful for this great plugin, awesome work you guys!

However, I don't understand the example on your page here: https://www.primefaces.org/primeng/showcase/#/table/lazy

You basically require us to pre-load all Cars from the db, and then merely display chunks of them on scroll...
This defeats the purpose of lazy loading pagination, doesn't it?

If I have 1 million Cars in my db, I don't want to query all 1 million, and then show 100 at a time via slicing. This defeats the purpose entirely.

The table should rather pre-load the first 100 Cars, and then as a person scrolls down, fire an event so that we can query the next 100 from the db using an offset. The table will of course need to know the total amount of available Cars, but that should merely be a number.

**Comment by cagataycivici** [comment]
Unable to replicate with PrimeNG 10, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.

**Comment by cagataycivici** [comment]
See https://github.com/primefaces/primeng/issues/8890
