### ISSUE TITLE
[p-table] Can't reset resizable column width to autolayout

### ISSUE THREAD

**Issue by viceice** [primefaces/primeng#8991]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**

Can be provided later if required

**Current behavior**

If i call `reset` on the table the column width are not reset to initial values.

**Expected behavior**

The column width should be reset to initial values. They should also reset when input columns change.
This is somehow related to #8902 

**Minimal reproduction of the problem with instructions**

* create persistant table with resisable cols
* resize cols
* call table.reset()

**What is the motivation / use case for changing the behavior?**

I've a function to completly reset the table to an initial state.
Everything excerpt the col sizes are reset.

**Please tell us about your environment:**

* **Angular version:** 9.1.11

* **PrimeNG version:** 9.1.0

* **Browser:** all

 
* **Language:** all

* **Node (for AoT issues):**  not relevant

**Comment by BhupathiReddyGaddam** [comment]
Hi,
I have the table layout resizing issues, could some one please help to resolve the below issue? thanks in advance.

Current behavior
By setting the [scrollable]="true" scrollHeight="200px" getting the vertical scroll to the table body with sticky header with equal width for all the columns.

By setting [autoLayout]="true" no change in the table behaviour.

By setting the CSS property table-layout: auto, the 'ui-table-scrollable-header>ui-table-scrollable-header-box>ui-table-scrollable-header-table>ui-table-thead' columns are resizing as per the character length of 'thead>tr>th' data.

Same thing happening for the table body data 'ui-table-scrollable-body>ui-table-scrollable-body-table>ui-table-tbody' columns are resizing as per the character length of 'tbody>tr>td' data.

The issue here is the thead column data and tbody column data is miss aligning because of the thead and tbody column data is resizing by their own character length but both should be in sync and align whichever's column data has highest character length

Expected Behaviour
By setting [autoLayout]="true" or CSS property table-layout: auto both the thead column data and tbody column data should resize based on the highest character length and align the thead and tbody data.

**Comment by Exlord** [comment]
The only solution that seems to be working for me :

```
<p-table stateStorage="local" stateKey="leadsTableState" *ngIf="leads; else leadsLoading" #dataTable [value]="leads" >
```

```
@ViewChild('dataTable', { static: false }) dataTable: Table;
```

```
this.dataTable.clearState();
//this is required to rerender the table
const leads          = this.leads;
this.leads           = null;
this.leads           = leads;
setTimeout(() => {
  this.saveTableState();
});
```

**Comment by viceice** [comment]
@Exlord This doesn't work for me.

I have some initial hidden columns, so they are not in the `columns` array. When i resize and save the state, everything looks ok. but if i add a column after all other columns have a fixed with, the new column gets zero width and is not visible and so not resizable too.

The only Workaround i see is to reset `columnWidthsState` to a working value and call `restoreColumnWidths` to hopefully force a autolayout. 😕

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
