### ISSUE TITLE
p-table selection is not updated in combination with context-menu

### ISSUE THREAD

**Issue by Michel73** [primefaces/primeng#9047]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**

https://stackblitz.com/edit/primeng-tablecontextmenu-demo-svrn3y?file=src%2Fapp%2Fapp.component.ts

**Current behavior**
A p-table with selection mode `mutliple` does not update its selection triggered by `onShow` of a context-menu.

**Expected behavior**
A p-table with selection mode `mutliple` should update its selection triggered by `onShow` of a context-menu. It should always update if its model of selection is updated. (Like the `select first line`-button)

**Minimal reproduction of the problem with instructions**
See the stackblitz example above. If you select some lines and make a right-click then the selection should change and only the first line should be selected.
In my concrete application I have to change the selection when the context-menu is opened on a hovered line so that the hovered line will be the selected one.
**What is the motivation / use case for changing the behavior?**
In my concrete application I have to change the selection when the context-menu is opened on a hovered line so that the hovered line will be the selected one.

**Please tell us about your environment:**

* **Angular version:** 
9.1.7

* **PrimeNG version:** 5.X
9.0.6

* **Browser:**
Chrome 83
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript 3.8.2

* **Node (for AoT issues):**
12.13.1

**Comment by ByronBurdette** [comment]
Really hoping for a solution to this one. Whether it be single or multi-selection; when using joint selection, the view should update when the selection object changes. I'm personally hoping this feature will just ends up working like selection in Windows. 

I just want to clarify one major point: **the issue seems to be just with how the p-highlight class is applied to rows. The table selection property itself appears to be functioning correctly**. It's just that which rows are being highlighted does not reflect the selection property appropriately. What's interesting is that in my [stackblitz example](https://stackblitz.com/edit/primeng-tableselection-bug-demo?file=src/app/app.component.html), you can see that if you start by selecting a row, then open the context menu for a completely different row, the first row will remain selected while the second row will remain unselected. This behavior is confusing already, but what's interesting is if you page over by 1, and then page back, now both rows will be highlighted. For me, this demonstrates the issue well.

When showing the context menu for a record which already exists in the selection array property of the table (whether we're talking single/multi-selection doesn't matter here), then the highlighted rows should not change at all. However, when showing the context menu for a record which is not currently stored in the selection array property, all of the currently highlighted rows should have the p-highlight class removed and the new row should have it added to it. This would reasonably emulate Windows selection behavior.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
