### ISSUE TITLE
datatable with editable dropdown

### ISSUE THREAD

**Issue by kkarandikar0807** [primefaces/primeng#925]
do u have datatable with editable dropdown..?

**Comment by Mrtcndkn** [comment]
Please try with the latest PrimeNG version and comment if the issue still persists.

**Comment by sudheerj** [comment]
It was added long back.There is already showcase example too [](https://www.primefaces.org/primeng/#/datatable/editable)

**Comment by kaushalkishorejaiswal** [comment]
Issue with editable datatable with dropdown. On editing the data from dropdown then the value of the shwoing in the table, which should be lable.

Example:
Dropdown Example
value    label
1              Newyork
2              Auli

On the selection of city id 1 Newyork (label) should be displayed there, not its value.

**Comment by seanonline** [comment]
The issue still persist 

Issue with editable datatable with dropdown. On editing the data from dropdown then the value of the shwoing in the table, which should be lable.

Example:
Dropdown Example
value label
1 Newyork
2 Auli

On the selection of city id 1 Newyork (label) should be displayed there, not its value. Currently its displaying 1 instead of Newyork

HAS SOMEONE FOUND THE SOLUTION ?
