### ISSUE TITLE
Remove functionality of locale property of Calendar

### ISSUE THREAD

**Issue by cagataycivici** [primefaces/primeng#9504]
Instead of locale property labels like dayName should be received from the new i18n API. Also firstDayOfWeek should be a property of Calendar and dateFormat should always use the existing property.

**Comment by zmara** [comment]
**This issue should be opened again**. Every modern UI library supports this type of localization (Kendo UI for example), because i18n is not the only way to set localizations. Changing locale during build time is not desired sometimes, look at Transloco, NgxTranslate and other libraries that change localization during runtime.

**Comment by Romulo-S** [comment]
Well i just see that is removed, there is no orientation whatsoever how to solve that, now i just have my calendar broken. Awful..
