### ISSUE TITLE
Pass the option as a template variable in Select Components without wrapping to SelectItem

### ISSUE THREAD

**Issue by cagataycivici** [primefaces/primeng#9505]
Due to 4295, we no longer wrap custom option objects as SelectItems so template variables no longer need to be SelectItems, this will introduce a breaking change because custom objects are now the variable themselves instead of getting accessed with the value property.

Before
```xml
<p-dropdown [options]="options" [(ngModel)]="modelValue">
    <ng-template let-option pTemplate="item">
          {{option.value.propName}}
    </ng-template>
</p-dropdown>
```

After
```xml
<p-dropdown [options]="options" [(ngModel)]="modelValue">
    <ng-template let-option pTemplate="item">
          {{option.propName}}
    </ng-template>
</p-dropdown>
```

**Comment by aznarepse** [comment]
I migrated my app from 10 to 11 and hit this rock.
To change all the templates to access the property without using 'value' in between should not be a drama.

However, in version 10, the selection was the whole object and, when bound to a reactive form, the forms control would get the whole object. Now, I am getting only a property of the object.
My objects have a property named 'value' and this one is being taken by default. I am aware I can set what property is used with **optionValue**, but I need the whole object.

This is breaking all the interface with the remote API when posting the DTO objects.

**Is there a quick way to store the object in the selection instead of a property only?**
