### ISSUE TITLE
p-table reset() causes errors in filter value binding

### ISSUE THREAD

**Issue by meistaiwan** [primefaces/primeng#9570]
**I'm submitting a ...**  (check one with "x")
```
[ X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://primeng-tablefilter-demo-h7jrf9.stackblitz.io/

**Current behavior**
Calling reset on the p-table causes the value for columnfilters to generate an error

**Expected behavior**
No error

**Minimal reproduction of the problem with instructions**
Click Reset Filters on stackblitz

* **PrimeNG version:** 5.X
Primeng 11.0.0-rc1

**Comment by ips219** [comment]
Same problem detected here with 11.0.0

It seems that model for the filter is stored directly in filters object 
https://github.com/primefaces/primeng/blob/b04aa55391fb3177074f17f401d6daf29f76172f/src/app/components/table/table.ts#L4096

Then when table is cleared after reset model is destroyed... From the UI it can be recovered by clicking on clear button on the column filter menu, but programatically seems to be difficult in order to implement a workaround (clear method should be executed on each column filter instance).

![Screenshot_3](https://user-images.githubusercontent.com/3368591/103567667-7f3a0f00-4ec4-11eb-8119-27a9daeadc7e.png)
![Screenshot_2](https://user-images.githubusercontent.com/3368591/103567669-806b3c00-4ec4-11eb-9b48-765107609bf3.png)

**Comment by Cito** [comment]
Just wanted to report the same and created a Stackblitz case, then found this issue.

Here is my Stackblitz if it helps: https://primeng-issue-9750.stackblitz.io

**Comment by Cito** [comment]
I'm currently using the following workaround: 

in the template:
```html
 <p-table #table ...>
   <ng-template pTemplate="header">
     <tr><th>heading</th>...<tr>
     <tr *ngIf="showFilters"><th>filter</th></tr>
  </ng-template>
  ...
</p-table>
```

in the component:
```js
  showFilters = true;
  
  @ViewChild('table') table: Table;
  
  constructor(private cd: ChangeDetectorRef) { }
  
  resetTable(): {
      this.showFilters = false;
      this.cd.detectChanges();  // cd = 
      table.reset();
      table.saveState();
      this.showFilters = true;
  }
```

I.e. I remove the filters temporarily while resetting the table and add them back afterwords. This will instantiate the filter components newly and they will work just fine. The problem only appears if you reset the table while the filter components are still alive.

**Comment by denny99** [comment]
Another issue is here:

```
<ng-container *ngTemplateOutlet="filterTemplate; context: {$implicit: filterConstraint.value, filterCallback: filterCallback}"></ng-container>
</ng-container>
<ng-template #builtInElement>
    <ng-container [ngSwitch]="type">
        <input *ngSwitchCase="'text'" type="text" pInputText [value]="filterConstraint?.value" (input)="onModelChange($event.target.value)"
```

For the default Inputs the filterContraint is optionally chained. For the filterTemplate not, which causes another error when resetting the table state.

**Comment by sadnahu** [comment]
> 

this.table.filters = {}; add this above of table clear or reset

**Comment by danbanswer** [comment]
> > 
> 
> this.table.filters = {}; add this above of table clear or reset

Thank you @sadnahu !! I don't understand what's going on enough to reopen this or enter a new bug, but even after upgrading to 13.3.3 I was still getting an error in on ModelChange() when typing in the filter's input box:
```
    onModelChange(value) {
        this.filterConstraint.value = value;
```
since this.filterConstraint was undefined. After adding Sadnahu's line of code, the filter is working.
