### ISSUE TITLE
Feature Request Custom Sort for DataView

### ISSUE THREAD

**Issue by jimmycartrette** [primefaces/primeng#9662]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[X ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
No custom sort for DataView is available, like is available in Table. So sorting by dates doesn't work

**Expected behavior**
Allow custom sort in DataView to allow custom sort function to sort dates, or change default sorts in Table/DataView to properly sort by date

* **Angular version:** 5.X
Angular 11

* **PrimeNG version:** 5.X
PrimeNG 11

**Comment by muuvmuuv** [comment]
Ah damn... Searching for that as well since Versions arent properly sorted by "localeCompare"...

DataTable already got such a feature. I am thinking of doing a PR but we are still unsure if we want to lazy load our stuff or not. If not we need this but in lazy mode you can compare yourself on the backend or client in the loader function.
