### ISSUE TITLE
The setup of primeng project is not complete

### ISSUE THREAD

**Issue by ribizli** [primefaces/primeng#967]
I've planned to contribute on an issue and set up a local development environment. This was a real mission.
- missing dependencies from package.json
- missing postinstall for typings
- missing css dependency: /resources/primeng.min.css
- we need to start tsc:w and webpack-dev-server parallel for live development

These are disappointing inconveniences for volunteers who want to contribute on the project.

**Comment by JakeSummers** [comment]
Agreed, contributing to PrimeNg is tricky and every release the steps for building it are different.  

Checkout my readme here for my (possibly outdated) steps to build the project: https://github.com/JakeSummers/primeng/tree/updatedReadme

Additionally, figuring out how to use a forked copy of PrimeNg is tricky.  I wasn't able to figure out how to use my fork of PrimeNg because the prepublish steps aren't in this repository.  Posted a question about it here: 

https://github.com/primefaces/primeng/issues/818

and here:

http://stackoverflow.com/questions/39237953/how-to-point-my-package-json-at-my-fork-of-primeng

Good luck

**Comment by qjlee** [comment]
You can also checkout my answer here to build the latest version  "4.0.0-rc.2-SNAPSHOT" https://github.com/primefaces/primeng/issues/2301

**Comment by cagataycivici** [comment]
Please use forum for cases like these. For 4.0.3, we've added dependencies as devDependencies by the way so no need to add the deps anymore and updated wiki according to @JakeSummers

**Comment by alexandremoore** [comment]
@cagataycivici, I think the documentation on the wiki still miss the css building part. In order to have it fully working, I had to go over this:
[https://github.com/primefaces/primeng/issues/2301#issuecomment-286870511](https://github.com/primefaces/primeng/issues/2301#issuecomment-286870511)

**Comment by cagataycivici** [comment]
Today I've converted the codebase as an Angular CLI project;

https://github.com/cagataycivici/primeng/

Will move to master tomorrow and update the wiki according to this big change.

**Comment by alexandremoore** [comment]
@cagataycivici, thanks for the update.
