### ISSUE TITLE
Calendar week days are never updated use i18n API.

### ISSUE THREAD

**Issue by Tigler** [primefaces/primeng#9689]
weekDays init in createWeekDays method with default traslate. After edit PrimeNGConfig translate weekDays not changed.
<th scope="col" *ngFor="let weekDay of weekDays;let begin = first; let end = last">
      <span>{{weekDay}}</span>
 </th>

Need use 
<th scope="col" *ngFor="let weekDay of getTranslation('dayNamesMin');let begin = first; let end = last">
      <span>{{weekDay}}</span>
 </th>

**Comment by Tigler** [comment]
weekDays init in createWeekDays method with default traslate. After edit PrimeNGConfig translate weekDays not changed.
"<th scope="col" *ngFor="let weekDay of weekDays;let begin = first; let end = last">"

Need use 
"<th scope="col" *ngFor="let weekDay of getTranslation('dayNamesMin');let begin = first; let end = last">"

**Comment by adessilly** [comment]
Find an example of the issue below : 

https://stackblitz.com/edit/primeng11-localization-bug?file=src%2Fapp%2Fapp.component.ts

The problem is the same if we want to dynamically change the firstDayOfWeek, it is never applied in the component.
There is also un bug if we change at runtime the dateFormat (it stays displayed with the previous dateFormat until we change the date).

Do you plan to fix this regression soon? Otherwise we would need to find other alternatives.

**Comment by adessilly** [comment]
Btw, for firstDayOfWeek, updateInputfield() update the field as expected :)
