### ISSUE TITLE
p-header and pTemplate=header treated differently in dialogs

### ISSUE THREAD

**Issue by Cito** [primefaces/primeng#9785]
**I'm submitting a ...**

... not sure if bug or feature. But if it's considered a feature, then it should be documented.

**Current behavior**

Currently, in a Dialog component, `<p-header>` and `<ng-template pTemplate="header">` behave differently.

If you use `<p-header>`, then its content will be rendered using the `p-dialog-title` class, in the same way as a `header` attribute value would be rendered. But if you use `<ng-template pTemplate="header">` then the header content will not get this class.

This is because the `p-dialog` template is defined like:
```html
    ...
    <span [attr.id]="id + '-label'" class="p-dialog-title" *ngIf="header">{{header}}</span>
    <span [attr.id]="id + '-label'" class="p-dialog-title" *ngIf="headerFacet">
        <ng-content select="p-header"></ng-content>
    </span>
    <ng-container *ngTemplateOutlet="headerTemplate"></ng-container>
    ...
```
As you see, the content of `p-header` and the content of `<ng-template pTemplate="header">` (the `headerTemplate`) are treated differently.

**Expected behavior**

I would expect that the two methods of specifying the header section behave the same, since the new method of using `ng-template` should be an equivalent replacement for `p-header` and `p-footer`.

If the different treatment is deliberate then this should be documented, at least in the changelog and migration guide.

* **PrimeNG version:** 11.1

**Comment by yigitfindikli** [comment]
Hi @Cito ,

p-header and p-footer are deprecated, they still exist because of backward compatibility.

**Comment by Cito** [comment]
> p-header and p-footer are deprecated, they still exist because of backward compatibility.

I know. But because they are deprecated, we need to migrate them to the new way using ng-template.

And the problem is that when you try to replace `p-header` with ` <ng-template pTemplate="header">` as the migration docs recommend, the styling of the header will suddenly be missing which is not what you expect. That's why I recommend to either document that it behaves differently for dialogs, or to make it behave the same.

**Comment by marcelro** [comment]
I think your problem is that the html tag for p-header is missing, and the new way with ng-template will not add any wrapping html-Tag.
I think the easiest way to fix this is to add an own "container" maybe div inside of the ng-template and assign a class to it. Then in the css instead of accessing p-header component use the class.

I think a bit better docu on how to migrate the things would be very great.

By the way, when it is deprectaed, but still in, becasue of compatibility will it ever be removed?
How do I see in the code that it is deprectaed, it is even not marked there as deprecated, or?

**Comment by bendehghan** [comment]
I don't know why this is closed. The issue is still there.
Currently the docs say this:

`<p-dialog [(visible)]="display">
    <ng-template pTemplate="header">
        Header content here
    </ng-template>
    Content
    <p-footer>
        //buttons
    </p-footer>
</p-dialog>`

which surprisingly is how the code behaves even though it looks like a mistake. The footer with ng-template does not show up but with p-footer does. 

This is the case for p-dialog but not for p-confirmationDialog which does behave properly with ng-template footer and header. It seems like this part of the code is still in flux and confusing to use.

**Comment by bendehghan** [comment]
Correction again. confimationDialog is also broken. p-footer behaves properly. ng-template footer does not. I'd expect the two to behave the same if you're shooting for some sort of deprecation process.

**Comment by Cito** [comment]
@bendehghan in any case, something needs to be done here, so asking @yigitfindikli to reopen and clarify:

* Is the different behavior of `p-header` and `pTemplate="header"` *intended* (it may well be, in order to make the new method more flexible)? Then the difference should be documented because it needs extra consideration when migrating.
* Is it *not intended*? Then it should be fixed so that the old and new method work the same.

**Comment by pouyababaie** [comment]
HI.
i dont know exactly it fits here , but how do i make the p-dialog templtaes customized when using a component as dialog , im openning it not in the view but in my class.
`
openModal(id) {
    this.dialogRef.open(ViewAndCreateStationTicketTypeComponent, {
      data: {
        programId: this.programId,
        ticketTypeId: id,
      },
      style: { 'min-width': '50%', 'min-height': '50%', overflow: 'auto' }
      modal: true,
      rtl: true,
    });
  }
`

i want to customize the header , content and footer  templates.
how do i do that?
