### ISSUE TITLE
Allow p-scrollPanel additional scroll options

### ISSUE THREAD

**Issue by fitness23** [primefaces/primeng#9940]
At present we can only use scrollTop to scroll the panel.
Please can you add 2 new features:

- Allow the scroll to animate smoothly such as when we want to do it on body
ie: `document.querySelector('#footer').scrollIntoView({ behavior: 'smooth' });`

- Allow the ability to scroll to the bottom of the panel.

**Comment by FreedomRings** [comment]
Let me second this.  I have to use a non-prime component to accomplish this on my software!

In fact, I am using yet another scroll panel to procedurally slow-scroll at a predefined speed to the bottom, then procedurally fast-scroll back to the top to do it over and over (so that users can watch for what they need on a monitor).

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
